import { assertValidTimeline, type Clip, type Timeline } from "../../timeline-core/src/public.js";
import { mapOriginalToProxy, type ProxyMap } from "../../timebase/src/public.js";
import { effectRegistry, validateRegisteredEffect } from "./effect-registry.js";
import { validateGrade, validateMask } from "../../timeline-core/src/public.js";
export { effectRegistry, validateRegisteredEffect, type EffectRegistryEntry } from "./effect-registry.js";
export { resolveExecutionPlan, semanticGraphManifest, semanticGraphPayload, type CapabilitySnapshot, type ExecutionPlan, type OutputManifest, type RenderDiagnostic, type ResolverDecision, type SemanticGraphManifest } from "./v2.js";
export { canonicalSerialize } from "./canonical.js";
import { canonicalSerialize } from "./canonical.js";

export type RenderTarget = "preview" | "master";
export type RenderNodeKind = "source" | "trim" | "speed" | "time_map" | "transform" | "color" | "mask" | "audio" | "transition" | "caption" | "effect" | "unsupported" | "composite" | "sink";
export type RenderScalar = string | number | boolean;
export type RenderSourceRef = Readonly<{ asset_ref: string; original_ref?: string; proxy_ref?: string; source_timescale: bigint; original_timescale?: bigint; proxy_timescale?: bigint; proxy_map?: ProxyMap; original_object_ref?: string; proxy_object_ref?: string }>;
export type RenderRange = Readonly<{ start_pts: bigint; end_pts: bigint; timescale: bigint }>;
export type RenderProfile = Readonly<{ name: string; width?: number; height?: number; fps?: number; video_codec?: string; audio_codec?: string; container?: string }>;
export type RenderNode = Readonly<{ node_id: string; kind: RenderNodeKind; capability: string; parameters?: Readonly<Record<string, RenderScalar>> }>;
export type RenderEdge = Readonly<{ from: string; to: string }>;
export type RenderCapability = Readonly<{ name: string; preview: boolean; master: boolean; fallback?: string; bake?: string; blocker?: string }>;
export type CapabilityDecision = Readonly<{ capability: string; target: RenderTarget; supported: boolean; fallback?: string; bake?: string; blocker?: string }>;
export type RenderGraph = Readonly<{ schema_version: 1; graph_id: string; timeline_version?: number; target?: RenderTarget; nodes: readonly RenderNode[]; edges: readonly RenderEdge[]; source_refs?: readonly RenderSourceRef[]; profile?: RenderProfile; range?: RenderRange }>;
export type RenderIssue = Readonly<{ code: "DUPLICATE_NODE" | "MISSING_NODE" | "CYCLE" | "UNSUPPORTED_CAPABILITY" | "NO_SOURCE" | "NO_SINK" | "MISSING_SOURCE_REF" | "MASTER_ORIGINAL_REQUIRED"; node_id?: string; message: string }>;

const pts = (value: bigint): string => `${value}n`;
const greatestCommonDivisor = (left: bigint, right: bigint): bigint => { let a = left < 0n ? -left : left; let b = right < 0n ? -right : right; while (b !== 0n) [a, b] = [b, a % b]; return a || 1n; };
const sourceFor = (source: RenderSourceRef, target: RenderTarget): { source_ref: string; source_kind: "original" | "proxy"; fallback?: string } => { if (target === "master") { if (!source.original_ref) throw new Error(`MASTER_ORIGINAL_REQUIRED:${source.asset_ref}`); return { source_ref: source.original_ref, source_kind: "original" }; } if (source.proxy_ref) return { source_ref: source.proxy_ref, source_kind: "proxy" }; if (source.original_ref) return { source_ref: source.original_ref, source_kind: "original", fallback: "proxy_missing_original_fallback" }; throw new Error(`RENDER_SOURCE_MISSING:${source.asset_ref}`); };
export function capabilityDecision(capability: RenderCapability, target: RenderTarget): CapabilityDecision { const supported = capability[target]; return { capability: capability.name, target, supported, fallback: capability.fallback, bake: capability.bake, blocker: supported ? undefined : capability.blocker ?? `capability unavailable for ${target}: ${capability.name}` }; }

export const timelineRenderCapabilities: ReadonlyMap<string, RenderCapability> = new Map([
  ["source.original", { name: "source.original", preview: true, master: true }],
  ["source.proxy", { name: "source.proxy", preview: true, master: false, fallback: "source.original", blocker: "master requires original source" }],
  ["timeline.trim", { name: "timeline.trim", preview: true, master: true }],
  ["timeline.speed", { name: "timeline.speed", preview: true, master: true, bake: "speed_filter" }],
  ["timeline.time_map", { name: "timeline.time_map", preview: true, master: true, bake: "segment_concat" }],
  ["timeline.transform", { name: "timeline.transform", preview: true, master: true, bake: "scale_pad" }],
  ["timeline.color", { name: "timeline.color", preview: true, master: true, bake: "eq_lut3d" }],
  ["timeline.mask", { name: "timeline.mask", preview: true, master: true, bake: "masked_filter" }],
  ["timeline.audio", { name: "timeline.audio", preview: true, master: true }],
  ["timeline.transition", { name: "timeline.transition", preview: true, master: true, bake: "xfade" }],
  ["timeline.caption", { name: "timeline.caption", preview: true, master: true, bake: "drawtext" }],
  ["timeline.effect", { name: "timeline.effect", preview: true, master: true, bake: "filter" }],
  ["timeline.unsupported", { name: "timeline.unsupported", preview: false, master: false, blocker: "UNSUPPORTED_CAPABILITY" }],
  ["timeline.composite", { name: "timeline.composite", preview: true, master: true }],
  ["sink.mp4", { name: "sink.mp4", preview: true, master: true }]
]);

export function buildTimelineRenderGraph(timeline: Timeline, sources: ReadonlyMap<string, RenderSourceRef>, target: RenderTarget, profile: RenderProfile = { name: target }, range?: RenderRange): RenderGraph {
  assertValidTimeline(timeline);
  const nodes: RenderNode[] = []; const edges: RenderEdge[] = []; const sourceRefs = new Map<string, RenderSourceRef>(); const compositeInputs: string[] = [];
  const soloActive = timeline.tracks.some((track) => track.enabled !== false && track.solo === true);
  const activeTracks = timeline.tracks.filter((track) => track.enabled !== false && (!soloActive || track.solo === true) && !(track.kind === "audio" && track.muted === true));
  const trackOrder = new Map(timeline.tracks.map((track, index) => [track.track_id, index]));
  const clips = activeTracks.flatMap((track) => track.clips.map((clip) => ({ track, clip }))).sort((left, right) => (left.track.z_index ?? 0) - (right.track.z_index ?? 0) || (trackOrder.get(left.track.track_id) ?? 0) - (trackOrder.get(right.track.track_id) ?? 0) || (left.clip.timeline_start < right.clip.timeline_start ? -1 : left.clip.timeline_start > right.clip.timeline_start ? 1 : left.clip.clip_id.localeCompare(right.clip.clip_id)));
  const timelineTickValue = timeline.sequence?.timebase?.value ?? 1n;
  const timelineTimescale = timeline.sequence?.timebase?.timescale ?? clips[0]?.clip.source.timescale ?? 1n;
  const timelinePts = (value: bigint): bigint => value * timelineTickValue;
  const timelineDuration = timelinePts(activeTracks.flatMap((track) => [...track.clips.map((clip) => clip.timeline_start + clip.timeline_duration), ...(track.gaps ?? []).map((gap) => gap.timeline_start + gap.timeline_duration), ...(track.captions ?? []).map((caption) => caption.timeline_start + caption.timeline_duration)]).reduce((maximum, value) => value > maximum ? value : maximum, 0n));
  for (let index = 0; index < clips.length; index += 1) {
    const { track, clip } = clips[index]; const source = sources.get(clip.source.asset_id); if (!source) throw new Error(`RENDER_SOURCE_MISSING:${clip.source.asset_id}`); const selected = sourceFor(source, target); sourceRefs.set(source.asset_ref, source);
    let sourceStart = clip.source.start_pts; let sourceEnd = clip.source.end_pts; let sourceTimescale = clip.source.timescale;
    if (target === "preview" && selected.source_kind === "proxy" && source.proxy_ref !== source.original_ref) {
      if (!source.proxy_map) throw new Error(`PROXY_MAP_REQUIRED:${source.asset_ref}`);
      const mappedStart = mapOriginalToProxy(source.proxy_map, { value: clip.source.start_pts, timescale: clip.source.timescale });
      const mappedEnd = mapOriginalToProxy(source.proxy_map, { value: clip.source.end_pts, timescale: clip.source.timescale });
      sourceTimescale = source.proxy_timescale ?? source.proxy_map.proxy_timebase; sourceStart = (mappedStart.value * sourceTimescale) / mappedStart.timescale; sourceEnd = (mappedEnd.value * sourceTimescale) / mappedEnd.timescale;
    }
    const base = `clip-${clip.clip_id}-${index}`; const sourceId = `${base}-source`; const trimId = `${base}-trim`; let previous = sourceId;
    nodes.push({ node_id: sourceId, kind: "source", capability: selected.source_kind === "original" ? "source.original" : "source.proxy", parameters: { asset_ref: source.asset_ref, source_ref: selected.source_ref, source_kind: selected.source_kind, selected_object_ref: selected.source_kind === "original" ? source.original_object_ref ?? "" : source.proxy_object_ref ?? "", track_kind: track.kind, clip_kind: clip.kind ?? "media", track_id: track.track_id, track_z_index: track.z_index ?? 0, track_order: trackOrder.get(track.track_id) ?? 0, track_enabled: track.enabled !== false, track_locked: track.locked === true, track_muted: track.muted === true, track_solo: track.solo === true, track_opacity: track.opacity ?? 1, track_blend_mode: track.blend_mode ?? "normal", audio_enabled: track.muted !== true, clip_id: clip.clip_id, source_start_pts: pts(sourceStart), source_end_pts: pts(sourceEnd), source_timescale: pts(sourceTimescale), semantic_source_start_pts: pts(clip.source.start_pts), semantic_source_end_pts: pts(clip.source.end_pts), semantic_source_timescale: pts(clip.source.timescale), timeline_start: pts(timelinePts(clip.timeline_start)), timeline_duration: pts(timelinePts(clip.timeline_duration)), timeline_timescale: pts(timelineTimescale), timeline_total_duration: pts(timelineDuration), ...(selected.fallback ? { fallback: selected.fallback } : {}) } });
    nodes.push({ node_id: trimId, kind: "trim", capability: "timeline.trim", parameters: { start_pts: pts(sourceStart), end_pts: pts(sourceEnd), timescale: pts(sourceTimescale), semantic_start_pts: pts(clip.source.start_pts), semantic_end_pts: pts(clip.source.end_pts), semantic_timescale: pts(clip.source.timescale) } }); edges.push({ from: sourceId, to: trimId }); previous = trimId;
    const block = (code: string): void => { const nodeId = `${base}-block-${code.toLowerCase().replaceAll("_", "-")}`; nodes.push({ node_id: nodeId, kind: "unsupported", capability: "timeline.unsupported", parameters: { blocker_code: code, clip_id: clip.clip_id, track_id: track.track_id } }); edges.push({ from: previous, to: nodeId }); previous = nodeId; };
    if (clip.kind === "nested") block("NESTED_SEQUENCE_RENDER_UNSUPPORTED");
    if (clip.kind === "compound") block("COMPOUND_CLIP_RENDER_UNSUPPORTED");
    if (clip.kind === "adjustment") block("ADJUSTMENT_CLIP_RENDER_UNSUPPORTED");
    if ((clip.automation_curves?.length ?? 0) > 0 || (clip.keyframes?.length ?? 0) > 0 || (track.automation_curves?.length ?? 0) > 0 || (track.keyframes?.length ?? 0) > 0) block("AUTOMATION_RENDER_UNSUPPORTED");
    if ((track.blend_mode ?? "normal") !== "normal") block("BLEND_MODE_UNSUPPORTED");
    if (clip.speed) { const nodeId = `${base}-speed`; nodes.push({ node_id: nodeId, kind: "speed", capability: "timeline.speed", parameters: { numerator: pts(clip.speed.numerator), denominator: pts(clip.speed.denominator) } }); edges.push({ from: previous, to: nodeId }); previous = nodeId; }
    if (clip.time_map) {
      const executionSegments = target === "preview" && selected.source_kind === "proxy" && source.proxy_map
        ? clip.time_map.segments.map((rawSegment) => {
          const segment = { ...rawSegment, timeline_start: timelinePts(rawSegment.timeline_start), timeline_end: timelinePts(rawSegment.timeline_end) };
          const proxyScale = source.proxy_timescale ?? source.proxy_map!.proxy_timebase;
          const mapPoint = (value: bigint): bigint => { const mapped = mapOriginalToProxy(source.proxy_map!, { value, timescale: clip.source.timescale }); return (mapped.value * proxyScale) / mapped.timescale; };
          const source_start = mapPoint(segment.source_start); const source_end = mapPoint(segment.source_end);
          if (segment.mode !== "speed") return { ...segment, source_start, source_end };
          const rawNumerator = (source_end - source_start) * timelineTimescale; const rawDenominator = (segment.timeline_end - segment.timeline_start) * proxyScale; const divisor = greatestCommonDivisor(rawNumerator, rawDenominator);
          return { ...segment, source_start, source_end, speed_numerator: rawNumerator / divisor, speed_denominator: rawDenominator / divisor };
        })
        : clip.time_map.segments.map((rawSegment) => {
          const segment = { ...rawSegment, timeline_start: timelinePts(rawSegment.timeline_start), timeline_end: timelinePts(rawSegment.timeline_end) };
          if (segment.mode !== "speed") return segment;
          const rawNumerator = (segment.source_end - segment.source_start) * timelineTimescale; const rawDenominator = (segment.timeline_end - segment.timeline_start) * sourceTimescale; const divisor = greatestCommonDivisor(rawNumerator, rawDenominator);
          return { ...segment, speed_numerator: rawNumerator / divisor, speed_denominator: rawDenominator / divisor };
        });
      const nodeId = `${base}-time-map`; nodes.push({ node_id: nodeId, kind: "time_map", capability: "timeline.time_map", parameters: { map_id: clip.time_map.map_id, pitch_policy: clip.time_map.pitch_policy, segments_json: canonicalSerialize(executionSegments), semantic_segments_json: canonicalSerialize(clip.time_map.segments) } }); edges.push({ from: previous, to: nodeId }); previous = nodeId;
    }
    if (clip.transform) { if (clip.transform.anchor_x !== undefined || clip.transform.anchor_y !== undefined) block("TRANSFORM_ANCHOR_RENDER_UNSUPPORTED"); if (clip.transform.fit === "original") block("TRANSFORM_ORIGINAL_SIZE_RENDER_UNSUPPORTED"); const nodeId = `${base}-transform`; nodes.push({ node_id: nodeId, kind: "transform", capability: "timeline.transform", parameters: Object.fromEntries(Object.entries(clip.transform).map(([key, value]) => [key, value])) }); edges.push({ from: previous, to: nodeId }); previous = nodeId; }
    if (clip.grade) { const gradeErrors = validateGrade(clip.grade); if (gradeErrors.length) throw new Error(`COLOR_INVALID:${gradeErrors.join(",")}`); const nodeId = `${base}-color`; nodes.push({ node_id: nodeId, kind: "color", capability: "timeline.color", parameters: { grade_id: clip.grade.grade_id, input_space: clip.grade.context.input_space, working_space: clip.grade.context.working_space, output_space: clip.grade.context.output_space, bit_depth: clip.grade.context.bit_depth, range: clip.grade.context.range, ...(clip.grade.exposure === undefined ? {} : { exposure: clip.grade.exposure }), ...(clip.grade.brightness === undefined ? {} : { brightness: clip.grade.brightness }), ...(clip.grade.contrast === undefined ? {} : { contrast: clip.grade.contrast }), ...(clip.grade.saturation === undefined ? {} : { saturation: clip.grade.saturation }), ...(clip.grade.gamma === undefined ? {} : { gamma: clip.grade.gamma }), ...(clip.grade.lut_path ? { lut_path: clip.grade.lut_path, lut_sha256: clip.grade.lut_sha256! } : {}) } }); edges.push({ from: previous, to: nodeId }); previous = nodeId; }
    if (clip.mask) { const maskErrors = validateMask(clip.mask); if (maskErrors.length) throw new Error(`MASK_INVALID:${maskErrors.join(",")}`); if (clip.mask.tracking_samples?.length) block("TRACKED_MASK_RENDER_UNSUPPORTED"); else if (clip.mask.shape === "ellipse") block("ELLIPSE_MASK_RENDER_UNSUPPORTED"); else if ((clip.mask.feather ?? 0) > 0) block("MASK_FEATHER_RENDER_UNSUPPORTED"); else { const nodeId = `${base}-mask`; nodes.push({ node_id: nodeId, kind: "mask", capability: "timeline.mask", parameters: { mask_id: clip.mask.mask_id, shape: clip.mask.shape, mode: clip.mask.mode, x: clip.mask.x, y: clip.mask.y, width: clip.mask.width, height: clip.mask.height, feather: clip.mask.feather ?? 0, lost_frame_policy: clip.mask.lost_frame_policy } }); edges.push({ from: previous, to: nodeId }); previous = nodeId; } }
    const routing = track.audio_routing?.find((item) => item.source_clip_id === clip.clip_id); const audioId = `${base}-audio`; nodes.push({ node_id: audioId, kind: "audio", capability: "timeline.audio", parameters: { track_kind: track.kind, track_id: track.track_id, clip_id: clip.clip_id, timeline_start: pts(timelinePts(clip.timeline_start)), timeline_duration: pts(timelinePts(clip.timeline_duration)), timeline_timescale: pts(timelineTimescale), source_start_pts: pts(sourceStart), source_end_pts: pts(sourceEnd), source_timescale: pts(sourceTimescale), semantic_source_start_pts: pts(clip.source.start_pts), semantic_source_end_pts: pts(clip.source.end_pts), semantic_source_timescale: pts(clip.source.timescale), gain_db: (clip.gain_db ?? 0) + (routing?.gain_db ?? 0), enabled: track.enabled !== false, muted: track.muted === true || routing?.muted === true, solo: track.solo === true, track_order: trackOrder.get(track.track_id) ?? 0, audio_role: routing?.bus ?? "embedded" } }); edges.push({ from: previous, to: audioId }); previous = audioId;
    for (const effect of [...(track.effects ?? []), ...(clip.effects ?? [])].filter((effect) => effect.clip_id === clip.clip_id && effect.enabled !== false)) { if (!effectRegistry.has(effect.kind)) { block("EFFECT_UNSUPPORTED"); continue; } try { validateRegisteredEffect(effect.kind, effect.parameters); } catch (error) { const code = error instanceof Error ? error.message.split(":", 1)[0] : "EFFECT_PARAMETER_INVALID"; block(code); continue; } const nodeId = `${base}-effect-${effect.effect_id}`; nodes.push({ node_id: nodeId, kind: "effect", capability: "timeline.effect", parameters: { effect_id: effect.effect_id, effect_kind: effect.kind, enabled: true, ...effect.parameters } }); edges.push({ from: previous, to: nodeId }); previous = nodeId; }
    compositeInputs.push(previous);
  }
  for (const track of activeTracks) for (const caption of track.captions ?? []) { const nodeId = `caption-${caption.caption_id}`; nodes.push({ node_id: nodeId, kind: "caption", capability: "timeline.caption", parameters: { caption_id: caption.caption_id, text: caption.text, start_pts: pts(timelinePts(caption.timeline_start)), duration: pts(timelinePts(caption.timeline_duration)), timescale: pts(timelineTimescale), ...(caption.language ? { language: caption.language } : {}), ...(caption.words ? { words_json: canonicalSerialize(caption.words.map((word) => ({ ...word, timeline_start: timelinePts(word.timeline_start), timeline_duration: timelinePts(word.timeline_duration) }))) } : {}), ...(caption.style?.font_file ? { font_file: String(caption.style.font_file) } : {}) } }); }
  const compositeId = "composite"; nodes.push({ node_id: compositeId, kind: "composite", capability: "timeline.composite", parameters: { input_count: compositeInputs.length, timeline_timescale: pts(timelineTimescale), timeline_duration: pts(timelineDuration), track_states_json: canonicalSerialize(timeline.tracks.map((track, order) => ({ track_id: track.track_id, kind: track.kind, order, z_index: track.z_index ?? 0, enabled: track.enabled !== false, locked: track.locked === true, muted: track.muted === true, solo: track.solo === true, opacity: track.opacity ?? 1, blend_mode: track.blend_mode ?? "normal", gaps: (track.gaps ?? []).map((gap) => ({ ...gap, timeline_start: timelinePts(gap.timeline_start), timeline_duration: timelinePts(gap.timeline_duration) })) }))) } }); for (const input of compositeInputs) edges.push({ from: input, to: compositeId });
  let finalNode = compositeId;
  for (const track of activeTracks) for (const transition of track.transitions ?? []) { const nodeId = `transition-${transition.transition_id}`; nodes.push({ node_id: nodeId, kind: "transition", capability: "timeline.transition", parameters: { transition_id: transition.transition_id, transition_kind: transition.kind, from_clip_id: transition.from_clip_id, to_clip_id: transition.to_clip_id, start_pts: pts(timelinePts(transition.timeline_start)), duration: pts(timelinePts(transition.timeline_duration)), timescale: pts(timelineTimescale), ...(transition.parameters ?? {}) } }); edges.push({ from: finalNode, to: nodeId }); finalNode = nodeId; }
  for (const track of activeTracks) for (const caption of track.captions ?? []) { const nodeId = `caption-${caption.caption_id}`; const existing = nodes.find((node) => node.node_id === nodeId); if (existing) { edges.push({ from: finalNode, to: nodeId }); finalNode = nodeId; } }
  const sinkId = "sink"; nodes.push({ node_id: sinkId, kind: "sink", capability: "sink.mp4", parameters: { target } }); edges.push({ from: finalNode, to: sinkId });
  return { schema_version: 1, graph_id: `${target}-timeline-v${timeline.version}`, timeline_version: timeline.version, target, nodes, edges, source_refs: [...sourceRefs.values()], profile, ...(range ? { range } : {}) };
}

export function renderGraphPayload(graph: RenderGraph): string { return canonicalSerialize(graph); }
export function validateGraph(graph: RenderGraph, capabilities: ReadonlyMap<string, RenderCapability>, target: RenderTarget): readonly RenderIssue[] { const issues: RenderIssue[] = []; const ids = new Set<string>(); const edges = new Map<string, string[]>(); for (const node of graph.nodes) { if (ids.has(node.node_id)) issues.push({ code: "DUPLICATE_NODE", node_id: node.node_id, message: "node id must be unique" }); ids.add(node.node_id); const capability = capabilities.get(node.capability); if (!capability || !capability[target]) issues.push({ code: "UNSUPPORTED_CAPABILITY", node_id: node.node_id, message: `capability unavailable for ${target}: ${node.capability}` }); if (node.kind === "source" && !node.parameters?.source_ref) issues.push({ code: "MISSING_SOURCE_REF", node_id: node.node_id, message: "source node needs explicit source_ref" }); } if (!graph.nodes.some((node) => node.kind === "source")) issues.push({ code: "NO_SOURCE", message: "graph needs a source" }); if (!graph.nodes.some((node) => node.kind === "sink")) issues.push({ code: "NO_SINK", message: "graph needs a sink" }); for (const edge of graph.edges) { if (!ids.has(edge.from)) issues.push({ code: "MISSING_NODE", node_id: edge.from, message: "edge source missing" }); if (!ids.has(edge.to)) issues.push({ code: "MISSING_NODE", node_id: edge.to, message: "edge target missing" }); edges.set(edge.from, [...(edges.get(edge.from) ?? []), edge.to]); } const visit = new Set<string>(); const active = new Set<string>(); const walk = (id: string) => { if (active.has(id)) { issues.push({ code: "CYCLE", node_id: id, message: "render graph contains a cycle" }); return; } if (visit.has(id)) return; active.add(id); for (const next of edges.get(id) ?? []) walk(next); active.delete(id); visit.add(id); }; for (const id of ids) walk(id); if (target === "master") for (const node of graph.nodes.filter((node) => node.kind === "source")) if (node.parameters?.source_kind !== "original") issues.push({ code: "MASTER_ORIGINAL_REQUIRED", node_id: node.node_id, message: "master graph source must be original" }); return issues; }
export function basicGraph(graph_id: string, sourceCapability = "source.original", sinkCapability = "sink.mp4"): RenderGraph { return { schema_version: 1, graph_id, nodes: [{ node_id: "source", kind: "source", capability: sourceCapability, parameters: { source_ref: "explicit-source", source_kind: sourceCapability === "source.proxy" ? "proxy" : "original" } }, { node_id: "sink", kind: "sink", capability: sinkCapability }], edges: [{ from: "source", to: "sink" }] }; }
