export type RenderNode = Readonly<{ node_id: string; kind: "source" | "effect" | "composite" | "sink"; capability: string; parameters?: Readonly<Record<string, string | number | boolean>> }>;
export type RenderEdge = Readonly<{ from: string; to: string }>;
export type RenderGraph = Readonly<{ schema_version: 1; graph_id: string; nodes: readonly RenderNode[]; edges: readonly RenderEdge[] }>;
export type RenderCapability = Readonly<{ name: string; preview: boolean; master: boolean }>;
export type RenderIssue = Readonly<{ code: "DUPLICATE_NODE" | "MISSING_NODE" | "CYCLE" | "UNSUPPORTED_CAPABILITY" | "NO_SOURCE" | "NO_SINK"; node_id?: string; message: string }>;

export function validateGraph(graph: RenderGraph, capabilities: ReadonlyMap<string, RenderCapability>, target: "preview" | "master"): readonly RenderIssue[] { const issues: RenderIssue[] = []; const ids = new Set<string>(); for (const node of graph.nodes) { if (ids.has(node.node_id)) issues.push({ code: "DUPLICATE_NODE", node_id: node.node_id, message: "node id must be unique" }); ids.add(node.node_id); const capability = capabilities.get(node.capability); if (!capability || !capability[target]) issues.push({ code: "UNSUPPORTED_CAPABILITY", node_id: node.node_id, message: `capability unavailable for ${target}: ${node.capability}` }); } if (!graph.nodes.some((node) => node.kind === "source")) issues.push({ code: "NO_SOURCE", message: "graph needs a source" }); if (!graph.nodes.some((node) => node.kind === "sink")) issues.push({ code: "NO_SINK", message: "graph needs a sink" }); for (const edge of graph.edges) { if (!ids.has(edge.from)) issues.push({ code: "MISSING_NODE", node_id: edge.from, message: "edge source missing" }); if (!ids.has(edge.to)) issues.push({ code: "MISSING_NODE", node_id: edge.to, message: "edge target missing" }); } return issues; }

export function basicGraph(graph_id: string, sourceCapability = "source.original", sinkCapability = "sink.mp4"): RenderGraph { return { schema_version: 1, graph_id, nodes: [{ node_id: "source", kind: "source", capability: sourceCapability }, { node_id: "sink", kind: "sink", capability: sinkCapability }], edges: [{ from: "source", to: "sink" }] }; }
