import { alignedPreviewSeconds } from "./player-panel.js";

/** Owns only decoded comparison media and its disposable visual transition. */
export function comparisonPanel() {
  const node=document.createElement("section");node.className="comparison-panel";node.setAttribute("aria-label","版本比较");node.hidden=true;node.inert=true;
  const motion=window.matchMedia("(prefers-reduced-motion: reduce)");
  let generation=0,entries=[],animation=null,disposed=false,returnFocus=null;const waits=new Set();
  const stopAnimation=()=>{if(animation){const prior=animation;animation=null;prior.onfinish=null;prior.oncancel=null;prior.cancel();}};
  const restoreFocus=()=>{if(node.contains(document.activeElement)&&returnFocus?.isConnected&&!returnFocus.disabled)returnFocus.focus({preventScroll:true});};
  const reset=()=>{restoreFocus();returnFocus=null;generation++;for(const cancel of [...waits])cancel();stopAnimation();for(const {video,url}of entries){video.pause();video.removeAttribute("src");video.load();URL.revokeObjectURL(url);}entries=[];node.replaceChildren();node.hidden=true;node.inert=true;node.style.opacity="";node.style.transform="";node.dataset.phase="closed";};
  const animate=(from,to,done)=>{stopAnimation();if(motion.matches){done();return;}const active=node.animate([from,to],{duration:180,easing:"cubic-bezier(.22,1,.36,1)",fill:"both"});animation=active;active.onfinish=()=>{if(animation!==active)return;animation=null;active.onfinish=null;active.oncancel=null;active.cancel();done();};};
  const close=(immediate=false)=>{restoreFocus();generation++;for(const cancel of [...waits])cancel();if(immediate||node.hidden||node.dataset.phase==="preparing"){reset();return;}const style=getComputedStyle(node),from={opacity:style.opacity,transform:style.transform};node.inert=true;for(const {video}of entries)video.pause();node.dataset.phase="closing";animate(from,{opacity:0,transform:"translateY(8px)"},reset);};
  const ready=video=>new Promise((resolve,reject)=>{let timer;const finish=(error,value)=>{clearTimeout(timer);video.removeEventListener("loadeddata",loaded);video.removeEventListener("error",failed);waits.delete(cancel);error?reject(error):resolve(value);};const loaded=()=>finish(null,true),failed=()=>finish(new Error(`比较画面解码失败（${video.error?.code??"unknown"}）`)),cancel=()=>finish(null,false);waits.add(cancel);video.addEventListener("loadeddata",loaded,{once:true});video.addEventListener("error",failed,{once:true});timer=setTimeout(()=>finish(new Error("比较画面未能及时解码，请查看本地记录。")),12000);if(video.readyState>=2)loaded();});
  async function open(items,isCurrent,opener=null) {
    reset();if(disposed||!isCurrent())return false;const ticket=generation;returnFocus=opener;node.dataset.phase="preparing";
    const heading=document.createElement("h2");heading.textContent="版本比较";const note=document.createElement("p");note.className="muted";note.textContent="两个版本独立播放，重排与删段不会按百分比假同步。";const dismiss=document.createElement("button");dismiss.textContent="结束比较";dismiss.addEventListener("click",()=>close());node.append(heading,note,dismiss);
    const videos=document.createElement("div");videos.className="comparison-videos";const decoding=[];
    for(const item of items){const column=document.createElement("section"),label=document.createElement("h3"),video=document.createElement("video");label.textContent=`作品 v${item.draft.timeline_version}`;video.controls=true;video.preload="auto";video.setAttribute("aria-label",label.textContent);const bytes=item.data.bytes instanceof Uint8Array?item.data.bytes:new Uint8Array(item.data.bytes),url=URL.createObjectURL(new Blob([bytes],{type:item.data.mime_type}));entries.push({video,url});decoding.push(ready(video));video.src=url;column.append(label,video);videos.append(column);}node.append(videos);
    const alignment=document.createElement("p"),controls=document.createElement("div");alignment.className="muted";controls.className="button-row";const players=entries.map(item=>item.video);
    for(const [from,to,label]of [[0,1,"右侧定位到左侧当前内容"],[1,0,"左侧定位到右侧当前内容"]]){const control=document.createElement("button");control.textContent=label;control.addEventListener("click",()=>{try{const seconds=alignedPreviewSeconds(items[from].timeline,items[to].timeline,players[from].currentTime);if(seconds===null){alignment.textContent="该版本没有唯一对应片段，保留原播放位置。";return;}players[to].currentTime=seconds;alignment.textContent="已按同一源片的实际范围定位；播放状态保持独立。";}catch(error){alignment.textContent=`片段对齐失败：${error.message}`;}});controls.append(control);}node.append(controls,alignment);
    try{const decoded=await Promise.all(decoding);if(ticket!==generation)return false;if(!decoded.every(Boolean)||!isCurrent()){reset();return false;}node.hidden=false;node.inert=false;node.dataset.phase="opening";animate({opacity:0,transform:"translateY(8px)"},{opacity:1,transform:"translateY(0)"},()=>{node.dataset.phase="open";});return true;}catch(error){if(ticket!==generation)return false;reset();throw error;}
  }
  const onMotionChange=()=>{if(motion.matches&&animation)animation.finish();};motion.addEventListener("change",onMotionChange);
  return {node,open,close,destroy(){disposed=true;motion.removeEventListener("change",onMotionChange);reset();}};
}
