/** Disposable presentation state; the Host remains the export/version authority. */
export function exportDialog(submit) {
  const node=document.createElement("section");node.className="export-overlay";node.hidden=true;node.inert=true;
  const panel=document.createElement("div");panel.className="export-dialog";panel.setAttribute("role","dialog");panel.setAttribute("aria-modal","true");panel.setAttribute("aria-label","导出作品");
  const heading=document.createElement("div");heading.className="panel-heading";const title=document.createElement("h2");title.textContent="导出作品";const dismiss=document.createElement("button");dismiss.textContent="关闭导出";dismiss.className="ghost";heading.append(title,dismiss);
  const summary=document.createElement("div"),note=document.createElement("p"),status=document.createElement("p"),send=document.createElement("button");summary.className="export-preview";note.className="muted";note.textContent=globalThis.window?.projectApi?.transport === "browser" ? "下载所选版本的实际成片。文件会保存到浏览器设置的下载目录；关闭此面板不会取消已经开始的导出。" : "保存所选版本的实际成片。关闭此面板只收起界面，不取消已开始的保存；原生保存窗口仍可取消。";status.className="export-status";status.setAttribute("aria-live","polite");send.textContent=globalThis.window?.projectApi?.transport === "browser" ? "下载成片" : "选择位置并导出";send.className="primary";send.type="button";panel.append(heading,summary,note,status,send);node.append(panel);
  const motion=window.matchMedia("(prefers-reduced-motion: reduce)");let animation=null,selection=null,project="",opener=null,projectEpoch=0;const results=new Map(),pending=new Set();
  const key=value=>JSON.stringify([value.project_id,value.request_id,value.draft_id,value.render_id]);
  const stop=()=>{if(animation){const prior=animation;animation=null;prior.onfinish=null;prior.cancel();}};
  const settled=()=>{stop();node.hidden=true;node.inert=true;node.dataset.phase="closed";};
  const animate=(from,to,done)=>{stop();if(motion.matches){done();return;}const active=panel.animate([from,to],{duration:180,easing:"cubic-bezier(.22,1,.36,1)",fill:"both"});animation=active;active.onfinish=()=>{if(animation!==active)return;animation=null;active.onfinish=null;active.cancel();done();};};
  const close=(immediate=false)=>{if(node.contains(document.activeElement)&&opener?.isConnected&&!opener.disabled)opener.focus({preventScroll:true});node.inert=true;if(immediate||node.hidden){settled();return;}const style=getComputedStyle(panel);node.dataset.phase="closing";animate({opacity:style.opacity,transform:style.transform},{opacity:0,transform:"translateY(8px)"},settled);};
  const refresh=()=>{if(!selection)return;const id=key(selection),busy=pending.has(id),result=results.get(id);send.disabled=busy||!selection.render_id;status.textContent=busy?"正在保存所选成片…":result?(result.ok?"导出操作已完成。":`导出未完成：${result.error?.message??"请查看本地制作记录。"}`):"选择本地位置后，由项目工作台核对成片身份与质量。";};
  const open=(value,trigger=document.activeElement)=>{if(!value?.render_id)return false;const wasHidden=node.hidden,style=wasHidden?{opacity:0,transform:"translateY(8px)"}:getComputedStyle(panel);selection={...value};project=value.project_id;opener=trigger;summary.replaceChildren();if(value.cover){const image=document.createElement("img");image.src=value.cover;image.alt=`作品 v${value.timeline_version} 的实际预览帧`;summary.append(image);}const text=document.createElement("div"),name=document.createElement("h3"),details=document.createElement("p");name.textContent=`作品 v${value.timeline_version}`;details.textContent=`预览检查：${value.preview_qc} · 成片检查：${value.master_qc}`;text.append(name,details);summary.append(text);node.hidden=false;node.inert=false;node.dataset.phase="opening";refresh();dismiss.focus({preventScroll:true});animate({opacity:style.opacity,transform:style.transform},{opacity:1,transform:"translateY(0)"},()=>{node.dataset.phase="open";});return true;};
  send.addEventListener("click",async()=>{if(!selection||send.disabled)return;const captured={...selection},id=key(captured),scopeEpoch=projectEpoch;pending.add(id);results.delete(id);refresh();try{const result=await submit(captured);if(projectEpoch===scopeEpoch&&project===captured.project_id)results.set(id,result??{ok:false,error:{message:"导出未返回有效结果，请查看本地记录。"}});}catch(error){if(projectEpoch===scopeEpoch&&project===captured.project_id)results.set(id,{ok:false,error:{message:error.message}});}finally{if(projectEpoch===scopeEpoch){pending.delete(id);if(project===captured.project_id)refresh();}}});
  dismiss.addEventListener("click",()=>close());node.addEventListener("click",event=>{if(event.target===node)close();});node.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();event.stopPropagation();close();}else if(event.key==="Tab"){const controls=[dismiss,...(!send.disabled?[send]:[])],index=controls.indexOf(document.activeElement);if(event.shiftKey&&index<=0){event.preventDefault();controls.at(-1).focus();}else if(!event.shiftKey&&index===controls.length-1){event.preventDefault();controls[0].focus();}}});
  const motionChanged=()=>{if(motion.matches&&animation)animation.finish();};motion.addEventListener("change",motionChanged);
  return {node,open,close,setProject(value){if(project!==value){projectEpoch++;project=value;selection=null;results.clear();pending.clear();close(true);}},destroy(){projectEpoch++;project="";selection=null;results.clear();pending.clear();close(true);motion.removeEventListener("change",motionChanged);}};
}
