packages:
  - apps/*
  - packages/core/*
  - packages/platform/*
  - packages/features/*
  - packages/adapters/*

onlyBuiltDependencies:
  - electron
  - esbuild

allowBuilds:
  electron: true
  esbuild: true

overrides:
  fast-uri: 3.1.5
