import assert from "node:assert/strict";
import type { AssetId } from "../../packages/core/media-identity/src/public.js";
import type { ApprovedStoryPlanV2 } from "../../contracts/generated/typescript/editorial/approved-story-plan.v2.js";
import { validateAssemblyCutV2, type AssemblyCutV2 } from "../../packages/features/assembly-cut/src/public.js";

const digest = (value: string) => value.repeat(64);
const evidenceRef = { object_id: "evidence-1", object_version: 1, digest: digest("e") };
const asset = `asset:sha256:${digest("a")}` as AssetId;
const plan: ApprovedStoryPlanV2 = { schema_version: 2, plan_id: "plan-1", object_version: 1, status: "approved", proposal_ref: { object_id: "proposal-1", object_version: 1, digest: digest("1") }, direction_ref: { object_id: "direction-1", object_version: 2, digest: digest("2") }, contract_ref: { object_id: "contract-1", object_version: 2, digest: digest("3") }, material_pack_ref: { object_id: "pack-1", object_version: 1, digest: digest("4") }, duration_feasibility_ref: { object_id: "duration-1", object_version: 1, digest: digest("5") }, thesis: "truth", audience_promise: "show truth", beats: [{ beat_id: "beat-1", role: "hook", purpose: "open", target_duration: { schema_version: 1, value: 1, timescale: 1 }, evidence_refs: [evidenceRef], coverage_requirement_ids: ["req-1"], entry_state: "before", exit_state: "after", desired_emotion: "curiosity" }], duration_budget: { schema_version: 1, value: 1, timescale: 1 }, emotional_curve: [{ phase: "hook", position: 0, intensity: 1 }], decision_ref: { object_id: "decision-1", object_version: 1, digest: digest("6") }, approval: { actor_id: "user", actor_kind: "user", approved_at: "2026-08-28T00:00:00Z", review_digest: digest("7") }, created_at: "2026-08-28T00:00:00Z", provenance: { producer: "project-host", source_version: "story-approval-v2", policy_version: "story-policy-v1", input_refs: [digest("6")] } };
const planDigest = digest("8");
const cut: AssemblyCutV2 = { schema_version: 2, assembly_id: "assembly-1", object_version: 1, approved_story_ref: { object_id: plan.plan_id, object_version: 1, digest: planDigest }, clips: [{ clip_id: "clip-1", beat_id: "beat-1", evidence_ref: evidenceRef, asset_id: asset, source: { start: { schema_version: 1, value: 0, timescale: 30 }, end: { schema_version: 1, value: 30, timescale: 30 } } }], status: "candidate", created_at: "2026-08-28T00:01:00Z", provenance: { producer: "project-host", source_version: "assembly-cut-v2", input_refs: [planDigest, evidenceRef.digest] } };
const evidence = [{ evidence_id: evidenceRef.object_id, evidence_version: 1, object_hash: evidenceRef.digest, asset_id: asset, start: { schema_version: 1 as const, value: 0, timescale: 30 }, end: { schema_version: 1 as const, value: 30, timescale: 30 }, review_status: "approved" as const }];

assert.equal(validateAssemblyCutV2({ cut, plan, plan_digest: planDigest, evidence }).status, "validated");
for (const invalid of [{ ...cut, object_version: 1.5 }, { ...cut, clips: [{ ...cut.clips[0]!, clip_id: "" }] }, { ...cut, created_at: "not-a-date" }]) assert.throws(() => validateAssemblyCutV2({ cut: invalid as AssemblyCutV2, plan, plan_digest: planDigest, evidence }), /ASSEMBLY_/);
assert.throws(() => validateAssemblyCutV2({ cut: { ...cut, approved_story_ref: { ...cut.approved_story_ref, digest: digest("9") } }, plan, plan_digest: planDigest, evidence }), /STORY_REBOUND/);
assert.throws(() => validateAssemblyCutV2({ cut: { ...cut, clips: [{ ...cut.clips[0]!, source: { start: { schema_version: 1, value: 0, timescale: 30 }, end: { schema_version: 1, value: 31, timescale: 30 } } }] }, plan, plan_digest: planDigest, evidence }), /SOURCE_RANGE_REBOUND/);
