import assert from "node:assert/strict";
import { compileApprovedEditorialIntent, compileFeedbackRevision, resolveCommandEditIntent, FEEDBACK_REVISION_COMPILER_ID, SEMANTIC_INTENT_COMPILER_ID, SEMANTIC_INTENT_COMPILER_VERSION } from "../../packages/core/edit-ir/src/public.js";
import type { EditorialEditIntentV1 } from "../../contracts/generated/typescript/editorial/editorial-edit-intent.v1.js";
import type { ApprovedStoryPlanV2 } from "../../contracts/generated/typescript/editorial/approved-story-plan.v2.js";
import { simulateCommands, type Timeline } from "../../packages/core/timeline-core/src/public.js";
import type { AssetId } from "../../packages/core/media-identity/src/public.js";
import { canonicalSerialize } from "../../packages/core/render-graph/src/public.js";
import { editorialObjectDigest } from "../../packages/core/editorial-core/src/public.js";
import { diagnoseFeedbackRevision, createFeedbackRevisionIntent } from "../../packages/features/feedback/src/public.js";
import { createHash } from "node:crypto";

const digest = (value: string) => value.repeat(64);
const evidenceRef = { object_id: "asr:first", object_version: 1, digest: digest("e") };
const plan: ApprovedStoryPlanV2 = { schema_version: 2, plan_id: "plan", object_version: 1, status: "approved", proposal_ref: { object_id: "proposal", object_version: 1, digest: digest("1") }, direction_ref: { object_id: "direction", object_version: 2, digest: digest("2") }, contract_ref: { object_id: "contract", object_version: 2, digest: digest("3") }, material_pack_ref: { object_id: "pack", object_version: 1, digest: digest("4") }, duration_feasibility_ref: { object_id: "duration", object_version: 1, digest: digest("5") }, thesis: "Use approved evidence", audience_promise: "Show the real moment", beats: [{ beat_id: "hook", role: "hook", purpose: "open", target_duration: { schema_version: 1, value: 1, timescale: 1 }, evidence_refs: [evidenceRef], coverage_requirement_ids: ["req"], entry_state: "before", exit_state: "after", desired_emotion: "curiosity" }], duration_budget: { schema_version: 1, value: 1, timescale: 1 }, emotional_curve: [{ phase: "hook", position: 0, intensity: 0.8 }], decision_ref: { object_id: "decision", object_version: 1, digest: digest("6") }, approval: { actor_id: "user", actor_kind: "user", approved_at: "2026-08-24T01:00:00Z", review_digest: digest("7") }, created_at: "2026-08-24T01:00:00Z", provenance: { producer: "project-host", source_version: "story", policy_version: "story", input_refs: [digest("6")] } };
const planDigest = digest("8"), asset = `asset:sha256:${digest("a")}` as AssetId;
const intent: EditorialEditIntentV1 = { schema_version: 1, intent_id: "intent", object_version: 1, status: "candidate", base_timeline_version: 0, approved_story_ref: { object_id: plan.plan_id, object_version: 1, digest: planDigest }, decision_refs: [plan.decision_ref], evidence_refs: [evidenceRef], contract_ref: plan.contract_ref, capability_snapshot_ref: { object_id: "capabilities", object_version: 1, digest: digest("9") }, operations: [{ operation_id: "select-hook", kind: "select_evidence", target_refs: ["beat:hook", "evidence:asr:first"], parameter_values: { priority: 1 }, expected_effect: "place approved hook", required_capabilities: ["semantic-evidence-selection"], unsupported_policy: "block" }], preconditions: ["timeline remains current"], protected_refs: [], reason: "compile exact approved evidence", alternatives: [], risks: [], confidence: { score: 1, basis: ["approved evidence"] }, actor: { actor_id: "project-host", actor_kind: "policy" }, input_fingerprint: digest("b"), created_at: "2026-08-24T01:01:00Z", provenance: { producer: "project-host", source_version: "intent", policy_version: "story", input_refs: [planDigest] } };
const timeline: Timeline = { version: 0, tracks: [{ track_id: "v1", kind: "video", clips: [] }] };
const evidence = [{ evidence_id: evidenceRef.object_id, evidence_version: 1, object_hash: evidenceRef.digest, asset_id: asset, start_pts: 0, end_pts: 48000, timescale: 48000, review_status: "approved" as const }];
const input = { intent, intent_digest: digest("c"), plan, plan_digest: planDigest, evidence, timeline };

const first = compileApprovedEditorialIntent(input), second = compileApprovedEditorialIntent(input);
assert.deepEqual(first, second, "same exact authorities must compile deterministically");
assert.equal(first.effect.compiler_id, SEMANTIC_INTENT_COMPILER_ID); assert.equal(first.effect.compiler_version, SEMANTIC_INTENT_COMPILER_VERSION);
assert.equal(first.command_intent.commands.length, 1); assert.equal(first.command_intent.commands[0]?.type, "add_clip");
assert.equal(first.effect.clips[0]?.timeline_duration, "48000"); assert.equal(first.effect.clips[0]?.source_timescale, "48000");
assert.equal(resolveCommandEditIntent(first.command_intent, timeline).schema_version, 2);
const uncoveredPlan: ApprovedStoryPlanV2 = { ...plan, beats: [...plan.beats, { ...plan.beats[0]!, beat_id: "ending", role: "ending", purpose: "close", entry_state: "after", exit_state: "resolved" }], duration_budget: { schema_version: 1, value: 2, timescale: 1 } };
assert.throws(() => compileApprovedEditorialIntent({ ...input, plan: uncoveredPlan }), /SEMANTIC_STORY_BEAT_UNCOVERED:ending/, "every approved Story Beat must have an explicit evidence-selection operation");
const duplicateBeatPlan: ApprovedStoryPlanV2 = { ...plan, beats: [...plan.beats, { ...plan.beats[0]!, purpose: "duplicate id must not share coverage" }], duration_budget: { schema_version: 1, value: 2, timescale: 1 } };
assert.throws(() => compileApprovedEditorialIntent({ ...input, plan: duplicateBeatPlan }), /SEMANTIC_STORY_BEAT_DUPLICATE:hook/, "duplicate approved Beat IDs must not share one duration selection");
assert.throws(() => compileApprovedEditorialIntent({ ...input, plan: { ...plan, duration_budget: { schema_version: 1, value: 2, timescale: 1 } } }), /SEMANTIC_STORY_DURATION_BUDGET_MISMATCH/, "approved Story duration must equal the exact sum of its Beats");
const durationMismatchPlan: ApprovedStoryPlanV2 = { ...plan, beats: plan.beats.map((item) => ({ ...item, target_duration: { schema_version: 1, value: 2, timescale: 1 } })), duration_budget: { schema_version: 1, value: 2, timescale: 1 } };
assert.throws(() => compileApprovedEditorialIntent({ ...input, plan: durationMismatchPlan }), /SEMANTIC_STORY_DURATION_MISMATCH:hook/, "unit-speed selected Evidence must exactly equal the approved Beat duration");
assert.throws(() => compileApprovedEditorialIntent({ ...input, evidence: [{ ...evidence[0]!, end_pts: 96000 }] }), /SEMANTIC_STORY_DURATION_MISMATCH:hook/, "Evidence longer than the approved Beat must fail instead of being truncated");
const secondEvidenceRef = { object_id: "asr:second", object_version: 1, digest: digest("d") }, multiEvidencePlanDigest = digest("f");
const multiEvidencePlan: ApprovedStoryPlanV2 = { ...plan, beats: plan.beats.map((item) => ({ ...item, evidence_refs: [evidenceRef, secondEvidenceRef] })) };
const multiEvidenceIntent: EditorialEditIntentV1 = { ...intent, approved_story_ref: { ...intent.approved_story_ref, digest: multiEvidencePlanDigest }, evidence_refs: [evidenceRef, secondEvidenceRef], operations: [{ ...intent.operations[0]!, operation_id: "select-hook-first", target_refs: ["beat:hook", "evidence:asr:first"] }, { ...intent.operations[0]!, operation_id: "select-hook-second", target_refs: ["beat:hook", "evidence:asr:second"] }] };
assert.throws(() => compileApprovedEditorialIntent({ ...input, intent: { ...multiEvidenceIntent, operations: multiEvidenceIntent.operations.map((operation) => ({ ...operation, operation_id: "select-hook-duplicate" })) }, plan: multiEvidencePlan, plan_digest: multiEvidencePlanDigest, evidence: [{ ...evidence[0]!, end_pts: 24000 }, { evidence_id: secondEvidenceRef.object_id, evidence_version: 1, object_hash: secondEvidenceRef.digest, asset_id: asset, start_pts: 24000, end_pts: 48000, timescale: 48000, review_status: "approved" as const }] }), /SEMANTIC_OPERATION_DUPLICATE/, "duplicate operation IDs must fail before clip commands are created");
const adjacentCompilation = compileApprovedEditorialIntent({ ...input, intent: multiEvidenceIntent, plan: multiEvidencePlan, plan_digest: multiEvidencePlanDigest, evidence: [{ ...evidence[0]!, end_pts: 24000 }, { evidence_id: secondEvidenceRef.object_id, evidence_version: 1, object_hash: secondEvidenceRef.digest, asset_id: asset, start_pts: 24000, end_pts: 48000, timescale: 48000, review_status: "approved" as const }] });
assert.equal(adjacentCompilation.command_intent.commands.length, 2, "adjacent non-overlapping ranges may exactly compose one approved Beat");
const repeatedRangePlan: ApprovedStoryPlanV2 = { ...multiEvidencePlan, beats: multiEvidencePlan.beats.map((item) => ({ ...item, target_duration: { schema_version: 1, value: 2, timescale: 1 } })), duration_budget: { schema_version: 1, value: 2, timescale: 1 } }, repeatedRangePlanDigest = digest("0"), repeatedRangeIntent: EditorialEditIntentV1 = { ...multiEvidenceIntent, approved_story_ref: { ...multiEvidenceIntent.approved_story_ref, digest: repeatedRangePlanDigest } };
assert.throws(() => compileApprovedEditorialIntent({ ...input, intent: repeatedRangeIntent, plan: repeatedRangePlan, plan_digest: repeatedRangePlanDigest, evidence: [evidence[0]!, { evidence_id: secondEvidenceRef.object_id, evidence_version: 1, object_hash: secondEvidenceRef.digest, asset_id: asset, start_pts: 0, end_pts: 48000, timescale: 48000, review_status: "approved" as const }] }), /SEMANTIC_EVIDENCE_SOURCE_OVERLAP/, "distinct Evidence IDs must not authorize repeating the same source range as an implicit loop");

assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, version: 1 } }), /SEMANTIC_TIMELINE_STALE/);
assert.throws(() => compileApprovedEditorialIntent({ ...input, evidence: [{ ...evidence[0]!, object_hash: digest("d") }] }), /SEMANTIC_EVIDENCE_REBOUND/);
assert.throws(() => compileApprovedEditorialIntent({ ...input, intent: { ...intent, operations: [{ ...intent.operations[0]!, kind: "set_pacing", required_capabilities: ["semantic-pacing"] }] } }), /SEMANTIC_OPERATION_UNSUPPORTED/);
assert.throws(() => compileApprovedEditorialIntent({ ...input, intent: { ...intent, operations: [{ ...intent.operations[0]!, range: { start: { schema_version: 1, value: 0, timescale: 1 }, end: { schema_version: 1, value: 1, timescale: 1 } } }] } }), /SEMANTIC_OPERATION_RANGE_UNSUPPORTED:select-hook/, "even a range equal to the approved Evidence must fail until select_evidence range semantics are explicitly defined");
for (const preserveAudio of [true, false]) assert.throws(() => compileApprovedEditorialIntent({ ...input, intent: { ...intent, operations: [{ ...intent.operations[0]!, parameter_values: { priority: 1, preserve_audio: preserveAudio } }] } }), /SEMANTIC_OPERATION_PARAMETER_UNSUPPORTED:preserve_audio:select-hook/, "the evidence-selection compiler cannot promise audio semantics that are absent from its approved Evidence input");
assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, tracks: [...timeline.tracks, { track_id: "v2", kind: "video", clips: [] }] } }), /SEMANTIC_VIDEO_TRACK_AMBIGUOUS/);
const existingClip = { clip_id: "existing-source", source: { asset_id: asset, start_pts: 0n, end_pts: 48000n, timescale: 48000n }, timeline_start: 0n, timeline_duration: 48000n, media_kind: "video" as const };
assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, tracks: [{ ...timeline.tracks[0]!, clips: [existingClip] }] } }), /SEMANTIC_DESTINATION_TIMELINE_NOT_EMPTY:v1/, "Story execution must not append to or silently replace an occupied target track");
const nonNeutralOutputStates: readonly [string, Record<string, unknown>][] = [
  ["muted", { muted: true }], ["solo", { solo: true }], ["opacity", { opacity: 0 }], ["blend_mode", { blend_mode: "multiply" }],
  ["transitions", { transitions: [{}] }], ["effects", { effects: [{}] }], ["keyframes", { keyframes: [{}] }], ["automation_curves", { automation_curves: [{}] }], ["audio_routing", { audio_routing: [{}] }], ["locks", { locks: [{}] }],
];
for (const [field, properties] of nonNeutralOutputStates) assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, tracks: [{ ...timeline.tracks[0]!, ...properties } as any] } }), new RegExp(`SEMANTIC_DESTINATION_TRACK_NOT_NEUTRAL:v1:${field}`), `an empty first-cut output track with ${field} must fail before commands are created`);
assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, tracks: [timeline.tracks[0]!, { track_id: "empty-audio-solo", kind: "audio", clips: [], solo: true }] } }), /SEMANTIC_DESTINATION_TRACK_NOT_NEUTRAL:empty-audio-solo:solo/, "an enabled empty solo audio track would globally suppress the video output");
assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, master_loudness: { schema_version: 1, enabled: true, target_lufs: -14, true_peak_db: -1, tolerance_lufs: 1 } } }), /SEMANTIC_DESTINATION_TIMELINE_NOT_NEUTRAL:master_loudness/, "enabled global loudness processing would change the selected Evidence audio");
assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, dialogue_music_ducking: { schema_version: 1, enabled: true, threshold_db: -30, ratio: 8, attack_ms: 20, release_ms: 350, max_reduction_db: 12 } } }), /SEMANTIC_DESTINATION_TIMELINE_NOT_NEUTRAL:dialogue_music_ducking/, "enabled global ducking would change the selected Evidence audio");
const explicitNeutralTimeline: Timeline = { ...timeline, master_loudness: { schema_version: 1, enabled: false, target_lufs: -14, true_peak_db: -1, tolerance_lufs: 1 }, dialogue_music_ducking: { schema_version: 1, enabled: false, threshold_db: -30, ratio: 8, attack_ms: 20, release_ms: 350, max_reduction_db: 12 }, tracks: [{ ...timeline.tracks[0]!, locked: false, muted: false, solo: false, opacity: 1, blend_mode: "normal", transitions: [], effects: [], keyframes: [], automation_curves: [], audio_routing: [], locks: [] }] };
assert.equal(compileApprovedEditorialIntent({ ...input, timeline: explicitNeutralTimeline }).command_intent.commands.length, 1, "explicit neutral output state remains executable");
const stagedTimeline: Timeline = { ...timeline, tracks: [{ track_id: "source-stage", kind: "video", enabled: false, muted: true, solo: true, opacity: 0, blend_mode: "multiply", clips: [existingClip] }, timeline.tracks[0]!] };
const stagedCompilation = compileApprovedEditorialIntent({ ...input, timeline: stagedTimeline }), stagedFirstCut = simulateCommands(stagedTimeline, stagedCompilation.command_intent.commands), stagedActiveClips = stagedFirstCut.tracks.filter((item) => item.enabled !== false).flatMap((item) => item.clips);
assert.equal(stagedCompilation.effect.clips[0]?.timeline_start, "0", "a disabled source stage plus one empty active output track is an authorized non-destructive first-cut shape"); assert.equal(stagedFirstCut.tracks[0]?.clips[0]?.clip_id, existingClip.clip_id); assert.equal(stagedActiveClips.reduce((maximum, item) => item.timeline_start + item.timeline_duration > maximum ? item.timeline_start + item.timeline_duration : maximum, 0n), 48000n, "the final render-active Timeline extent must exactly equal the approved Story");
const overlongAudioTimeline: Timeline = { ...timeline, tracks: [...timeline.tracks, { track_id: "a1", kind: "audio", clips: [{ ...existingClip, clip_id: "overlong-audio", media_kind: "audio", timeline_duration: 96000n }] }] };
assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: overlongAudioTimeline }), /SEMANTIC_DESTINATION_TIMELINE_NOT_EMPTY:a1/, "pre-existing render-active content must require a separately authorized composition operation");
const protectedCompilation = compileApprovedEditorialIntent({ ...input, intent: { ...intent, protected_refs: [asset] } });
assert.throws(() => resolveCommandEditIntent(protectedCompilation.command_intent, timeline), /EDIT_PROTECTED_REFERENCE/);
assert.throws(() => compileApprovedEditorialIntent({ ...input, timeline: { ...timeline, sequence: { sequence_id: "main", timebase: { value: 2n, timescale: 3n }, tracks: [] } } }), /SEMANTIC_TIMEBASE_NOT_EXACT/);

const firstCut = simulateCommands(timeline, first.command_intent.commands), clip = firstCut.tracks[0]!.clips[0]!;
function feedbackCase(caseId: string, caseTimeline: Timeline, targetClip: Timeline["tracks"][number]["clips"][number], trimTicks: bigint) {
  const timelineDigest = createHash("sha256").update(canonicalSerialize(caseTimeline)).digest("hex");
  const diagnosis = diagnoseFeedbackRevision({ diagnosis_id: `diagnosis-${caseId}`, feedback_text: "收短这个开场镜头", base_execution_ref: { object_id: "execution-first", object_version: 1, digest: digest("f") }, base_timeline_ref: { version: caseTimeline.version, digest: timelineDigest }, target: { track_id: "v1", clip_id: targetClip.clip_id, original_source: { asset_id: targetClip.source.asset_id, start: { schema_version: 1, value: Number(targetClip.source.start_pts), timescale: Number(targetClip.source.timescale) }, end: { schema_version: 1, value: Number(targetClip.source.end_pts), timescale: Number(targetClip.source.timescale) } }, proposed_source: { asset_id: targetClip.source.asset_id, start: { schema_version: 1, value: Number(targetClip.source.start_pts), timescale: Number(targetClip.source.timescale) }, end: { schema_version: 1, value: Number(targetClip.source.end_pts - trimTicks), timescale: Number(targetClip.source.timescale) } } }, authority_refs: { approved_story_ref: intent.approved_story_ref, decision_refs: intent.decision_refs, evidence_refs: intent.evidence_refs, contract_ref: intent.contract_ref, capability_snapshot_ref: intent.capability_snapshot_ref }, reason: "one strict local trim", alternatives: ["retain first cut"], confidence: { score: 1, basis: ["exact clip and range"] }, created_at: "2026-08-24T04:00:00Z" });
  const feedbackIntent = createFeedbackRevisionIntent(diagnosis, intent, { intent_id: `intent-${caseId}`, created_at: diagnosis.created_at });
  return { diagnosis, feedbackIntent, feedbackInput: { intent: feedbackIntent, intent_digest: editorialObjectDigest(feedbackIntent), plan, plan_digest: planDigest, evidence, timeline: caseTimeline, timeline_digest: timelineDigest, diagnosis, diagnosis_digest: editorialObjectDigest(diagnosis), base_execution_digest: diagnosis.base_execution_ref.digest } };
}
const { diagnosis, feedbackIntent, feedbackInput } = feedbackCase("trim", firstCut, clip, 12000n);
const feedbackCompilation = compileFeedbackRevision(feedbackInput);
assert.equal(feedbackCompilation.effect.compiler_id, FEEDBACK_REVISION_COMPILER_ID); assert.equal(feedbackCompilation.command_intent.commands.length, 1); assert.equal(feedbackCompilation.command_intent.commands[0]?.type, "trim_source"); assert.deepEqual(feedbackCompilation.effect.affected_scope, [`clip:${clip.clip_id}`]);
assert.throws(() => compileFeedbackRevision({ ...feedbackInput, timeline_digest: digest("0") }), /FEEDBACK_REVISION_TIMELINE_STALE/);
assert.throws(() => compileFeedbackRevision({ ...feedbackInput, diagnosis: { ...diagnosis, target: { ...diagnosis.target, clip_id: "missing" } } }), /FEEDBACK_REVISION_TARGET_AMBIGUOUS|FEEDBACK_REVISION_OPERATION_UNSUPPORTED/);
assert.throws(() => compileFeedbackRevision({ ...feedbackInput, intent: { ...feedbackIntent, protected_refs: [`clip:${clip.clip_id}`] } }), /FEEDBACK_REVISION_TARGET_PROTECTED/);
assert.throws(() => compileFeedbackRevision({ ...feedbackInput, intent: { ...feedbackIntent, operations: [{ ...feedbackIntent.operations[0]!, kind: "set_pacing", required_capabilities: ["semantic-pacing"] }] } }), /FEEDBACK_REVISION_OPERATION_UNSUPPORTED/);

const equivalentTimeline: Timeline = { ...firstCut, sequence: { sequence_id: "main", timebase: { value: 2n, timescale: 96000n }, tracks: [] } };
const equivalentCompilation = compileFeedbackRevision(feedbackCase("equivalent-timebase", equivalentTimeline, equivalentTimeline.tracks[0]!.clips[0]!, 12000n).feedbackInput);
assert.equal(equivalentCompilation.command_intent.commands[0]?.type, "trim_source", "an exactly equivalent RationalTime tick must remain supported");

const explicitMismatchTimeline: Timeline = { ...firstCut, sequence: { sequence_id: "main", timebase: { value: 1n, timescale: 30n }, tracks: [] } };
assert.throws(() => compileFeedbackRevision(feedbackCase("explicit-mixed-timebase", explicitMismatchTimeline, explicitMismatchTimeline.tracks[0]!.clips[0]!, 12000n).feedbackInput), /FEEDBACK_TRIM_TIMEBASE_UNSUPPORTED/, "an explicit non-equivalent Timeline tick must fail closed");

const speedTimeline: Timeline = { ...firstCut, tracks: [{ ...firstCut.tracks[0]!, clips: [{ ...clip, speed: { numerator: 1n, denominator: 2n } }] }] };
assert.throws(() => compileFeedbackRevision(feedbackCase("speed", speedTimeline, speedTimeline.tracks[0]!.clips[0]!, 12000n).feedbackInput), /FEEDBACK_TRIM_RETIME_UNSUPPORTED/, "a non-unit-speed clip needs a retime-aware trim command");
const mappedTimeline: Timeline = { ...firstCut, tracks: [{ ...firstCut.tracks[0]!, clips: [{ ...clip, time_map: { map_id: "identity-map", pitch_policy: "preserve", segments: [{ segment_id: "identity", timeline_start: 0n, timeline_end: 48000n, source_start: 0n, source_end: 48000n, mode: "speed", speed_numerator: 1n, speed_denominator: 1n }] } }] }] };
assert.throws(() => compileFeedbackRevision(feedbackCase("time-map", mappedTimeline, mappedTimeline.tracks[0]!.clips[0]!, 12000n).feedbackInput), /FEEDBACK_TRIM_RETIME_UNSUPPORTED/, "a TimeMap needs a map-aware trim command even when its current segment is identity-shaped");
const mismatchedDurationTimeline: Timeline = { ...firstCut, tracks: [{ ...firstCut.tracks[0]!, clips: [{ ...clip, timeline_duration: 24000n }] }] };
assert.throws(() => compileFeedbackRevision(feedbackCase("duration-mismatch", mismatchedDurationTimeline, mismatchedDurationTimeline.tracks[0]!.clips[0]!, 12000n).feedbackInput), /FEEDBACK_TRIM_RETIME_UNSUPPORTED/, "a source-to-timeline duration mismatch must not be rewritten as raw source ticks");

const targetCommand = first.command_intent.commands[0]!;
if (targetCommand.type !== "add_clip") throw new Error("semantic first cut must add the target clip");
const anchorAsset = `asset:sha256:${digest("0")}` as AssetId;
const implicitMixedTimeline = simulateCommands(timeline, [
  { type: "add_clip", track_id: "v1", clip: { clip_id: "implicit-30fps-anchor", source: { asset_id: anchorAsset, start_pts: 0n, end_pts: 30n, timescale: 30n }, timeline_start: 0n, timeline_duration: 30n, media_kind: "video" } },
  { ...targetCommand, clip: { ...targetCommand.clip, timeline_start: 30n, timeline_duration: 30n } },
]);
const mixedTarget = implicitMixedTimeline.tracks[0]!.clips.find((candidate) => candidate.clip_id === targetCommand.clip.clip_id)!;
assert.throws(() => compileFeedbackRevision(feedbackCase("implicit-mixed-timebase", implicitMixedTimeline, mixedTarget, 24000n).feedbackInput), /FEEDBACK_TRIM_TIMEBASE_UNSUPPORTED/, "an implicit first-clip tick must reject a mixed-timescale trim before command creation");

console.log("Semantic Intent and feedback revision compiler determinism and fail-closed property checks passed");
