import { strict as assert } from "node:assert";
import { basicGraph, buildTimelineRenderGraph, canonicalSerialize, RenderCapability, resolveExecutionPlan, semanticGraphPayload, validateGraph, validateRegisteredEffect } from "../../packages/core/render-graph/src/public.js";
import { sourceRange } from "../../packages/core/media-identity/src/public.js";
const capabilities = new Map<string, RenderCapability>([["source.original", { name: "source.original", preview: true, master: true }], ["sink.mp4", { name: "sink.mp4", preview: true, master: true }]]); const graph = basicGraph("graph-1"); assert.equal(validateGraph(graph, capabilities, "preview").length, 0); assert.equal(validateGraph(graph, capabilities, "master").length, 0); assert.equal(validateGraph({ ...graph, nodes: graph.nodes.slice(0, 1) }, capabilities, "master").some((issue) => issue.code === "NO_SINK"), true);
assert.doesNotThrow(() => validateRegisteredEffect("blur"));
assert.throws(() => validateRegisteredEffect("unregistered"), /EFFECT_UNSUPPORTED/);
const previewPlan = resolveExecutionPlan({ ...graph, timeline_version: 4, target: "preview" }, "preview");
const masterPlan = resolveExecutionPlan({ ...graph, timeline_version: 4, target: "master" }, "master");
assert.equal(previewPlan.semantic_graph_payload, masterPlan.semantic_graph_payload);
assert.equal(semanticGraphPayload({ ...graph, timeline_version: 4, target: "preview" }), semanticGraphPayload({ ...graph, timeline_version: 4, target: "master" }));
assert.notEqual(previewPlan.cache_key_payload, masterPlan.cache_key_payload, "target-specific execution caches must not collide");
const proxyMasterPlan = resolveExecutionPlan(basicGraph("proxy-master", "source.proxy"), "master");
assert.equal(proxyMasterPlan.decisions.some((decision) => decision.outcome === "fallback" && decision.detail === "source.original"), true);
assert.equal(proxyMasterPlan.diagnostics.some((diagnostic) => diagnostic.code === "MASTER_ORIGINAL_REQUIRED"), true);
const blockedGraph = { ...graph, nodes: [...graph.nodes.slice(0, 1), { node_id: "unsupported", kind: "effect" as const, capability: "effect.unavailable" }, graph.nodes[1]], edges: [{ from: "source", to: "unsupported" }, { from: "unsupported", to: "sink" }] };
const blockedPlan = resolveExecutionPlan(blockedGraph, "preview");
assert.equal(blockedPlan.decisions.some((decision) => decision.node_id === "unsupported" && decision.outcome === "block"), true);
assert.equal(blockedPlan.diagnostics.some((diagnostic) => diagnostic.code === "UNSUPPORTED_CAPABILITY" && diagnostic.node_id === "unsupported"), true);
const orderedA = { ...graph, timeline_version: 4, profile: { name: "ordered", width: 1920, height: 1080 }, nodes: [{ ...graph.nodes[0], parameters: { asset_ref: "asset", semantic_source_start_pts: "0n", semantic_source_end_pts: "30n", nested: "stable" } }, graph.nodes[1]] };
const orderedB = { ...orderedA, profile: { height: 1080, width: 1920, name: "ordered" }, nodes: [{ ...orderedA.nodes[0], parameters: { nested: "stable", semantic_source_end_pts: "30n", semantic_source_start_pts: "0n", asset_ref: "asset" } }, orderedA.nodes[1]] };
assert.equal(semanticGraphPayload(orderedA), semanticGraphPayload(orderedB), "semantic payload must ignore object insertion order recursively");
assert.equal(resolveExecutionPlan(orderedA, "preview").cache_key, resolveExecutionPlan(orderedB, "preview").cache_key, "cache key must ignore profile and parameter insertion order");
assert.notEqual(resolveExecutionPlan({ ...orderedA, range: { start_pts: 0n, end_pts: 10n, timescale: 30n } }, "preview").cache_key, resolveExecutionPlan({ ...orderedA, range: { start_pts: 0n, end_pts: 20n, timescale: 30n } }, "preview").cache_key, "render range must invalidate execution cache");
assert.notEqual(semanticGraphPayload(orderedA), semanticGraphPayload({ ...orderedA, nodes: [{ ...orderedA.nodes[0], parameters: { ...orderedA.nodes[0].parameters, semantic_source_end_pts: "60n" } }, orderedA.nodes[1]] }), "source trim semantics must invalidate semantic graph");
assert.throws(() => canonicalSerialize({ value: Number.NaN }), /numbers must be finite/);
assert.throws(() => canonicalSerialize({ value: Number.POSITIVE_INFINITY }), /numbers must be finite/);
assert.throws(() => canonicalSerialize({ value: undefined }), /undefined/);
assert.notEqual(canonicalSerialize({ value: 1n }), canonicalSerialize({ value: "1n" }), "BigInt encoding must not collide with strings");
const assetA = `asset:sha256:${"a".repeat(64)}` as any; const assetB = `asset:sha256:${"b".repeat(64)}` as any; const assetC = `asset:sha256:${"c".repeat(64)}` as any;
const clip = (clip_id: string, asset_id: any) => ({ clip_id, source: sourceRange(asset_id, 0n, 30n, 30n), timeline_start: 0n, timeline_duration: 30n });
const sources = new Map([[assetA, { asset_ref: assetA, original_ref: "a.mp4", source_timescale: 30n }], [assetB, { asset_ref: assetB, original_ref: "b.mp4", source_timescale: 30n }], [assetC, { asset_ref: assetC, original_ref: "c.mp4", source_timescale: 30n }]]);
const stateTimeline = { version: 1, tracks: [{ track_id: "base", kind: "video" as const, clips: [clip("clip-base", assetA)], muted: true }, { track_id: "disabled", kind: "video" as const, clips: [clip("clip-disabled", assetB)], enabled: false }, { track_id: "music", kind: "audio" as const, clips: [clip("clip-music", assetC)], muted: true }] };
const stateGraph = buildTimelineRenderGraph(stateTimeline, sources, "master");
assert.deepEqual(stateGraph.nodes.filter((node) => node.kind === "source").map((node) => node.parameters?.clip_id), ["clip-base"], "disabled and muted audio tracks must not execute");
assert.equal(stateGraph.nodes.find((node) => node.kind === "source")?.parameters?.audio_enabled, false, "muted video retains pictures but suppresses embedded audio");
const soloTimeline = { ...stateTimeline, tracks: [{ ...stateTimeline.tracks[0], muted: false }, { ...stateTimeline.tracks[1], enabled: true, solo: true }, { ...stateTimeline.tracks[2], muted: false }] };
assert.deepEqual(buildTimelineRenderGraph(soloTimeline, sources, "master").nodes.filter((node) => node.kind === "source").map((node) => node.parameters?.clip_id), ["clip-disabled"], "solo is a global track-selection authority");
const blockerFor = (changes: Record<string, unknown>) => resolveExecutionPlan(buildTimelineRenderGraph({ version: 1, tracks: [{ track_id: "v1", kind: "video" as const, clips: [{ ...clip("blocked", assetA), ...changes }] }] }, sources, "master"), "master").diagnostics.map((diagnostic) => diagnostic.code);
assert.ok(blockerFor({ automation_curves: [{ curve_id: "curve", target_id: "blocked", property_path: "transform.opacity", value_kind: "number", keyframes: [{ keyframe_id: "key", time: 0n, value: 1 }] }] }).includes("AUTOMATION_RENDER_UNSUPPORTED"));
assert.ok(blockerFor({ mask: { mask_id: "mask", shape: "rectangle", mode: "mosaic", x: 0.1, y: 0.1, width: 0.2, height: 0.2, lost_frame_policy: "block", tracking_samples: [{ time: 0n, x: 0.1, y: 0.1, width: 0.2, height: 0.2, confidence: 1, corrected: true }] } }).includes("TRACKED_MASK_RENDER_UNSUPPORTED"));
assert.ok(blockerFor({ mask: { mask_id: "ellipse", shape: "ellipse", mode: "blur", x: 0.1, y: 0.1, width: 0.2, height: 0.2, lost_frame_policy: "block" } }).includes("ELLIPSE_MASK_RENDER_UNSUPPORTED"), "ellipse geometry must block instead of rendering its rectangular bounds");
assert.ok(blockerFor({ transform: { anchor_x: 0.5, anchor_y: 0.5 } }).includes("TRANSFORM_ANCHOR_RENDER_UNSUPPORTED"));
assert.ok(blockerFor({ effects: [{ effect_id: "unknown-effect", clip_id: "blocked", kind: "unregistered", parameters: {}, enabled: true }] }).includes("EFFECT_UNSUPPORTED"), "unregistered effects must become persisted resolver blockers");
const layoutTracks = Array.from({ length: 40 }, (_, index) => ({ track_id: `layout-${index}`, kind: "video" as const, z_index: 39 - index, clips: [clip(`layout-clip-${index}`, assetA)] }));
const layoutGraph = buildTimelineRenderGraph({ version: 1, tracks: layoutTracks }, sources, "master");
assert.deepEqual(layoutGraph.nodes.filter((node) => node.kind === "source").map((node) => node.parameters?.track_z_index), Array.from({ length: 40 }, (_, index) => index), "generated track layouts must compile in deterministic z order");
const sequenceTimebaseGraph = buildTimelineRenderGraph({ version: 1, sequence: { sequence_id: "root", timebase: { value: 1n, timescale: 1000n }, tracks: [] }, tracks: [{ track_id: "millisecond", kind: "video", clips: [{ ...clip("millisecond-clip", assetA), timeline_start: 1000n, timeline_duration: 1000n }] }] }, sources, "master");
const sequenceTimebaseSource = sequenceTimebaseGraph.nodes.find((node) => node.kind === "source")!;
assert.equal(sequenceTimebaseSource.parameters?.timeline_timescale, "1000n", "sequence timebase must override source media timebase");
assert.equal(sequenceTimebaseSource.parameters?.timeline_start, "1000n");
assert.equal(sequenceTimebaseSource.parameters?.timeline_duration, "1000n");
const fractionalTickGraph = buildTimelineRenderGraph({ version: 1, sequence: { sequence_id: "fractional", timebase: { value: 1001n, timescale: 30000n }, tracks: [] }, tracks: [{ track_id: "fractional-track", kind: "video", clips: [{ ...clip("fractional-clip", assetA), timeline_start: 1n, timeline_duration: 2n }] }] }, sources, "master");
const fractionalSource = fractionalTickGraph.nodes.find((node) => node.kind === "source")!;
assert.equal(fractionalSource.parameters?.timeline_start, "1001n", "non-unit RationalTime ticks must be scaled exactly");
assert.equal(fractionalSource.parameters?.timeline_duration, "2002n");
assert.equal(fractionalSource.parameters?.timeline_timescale, "30000n");
assert.throws(() => buildTimelineRenderGraph({ version: 1, sequence: { sequence_id: "invalid-timebase", timebase: { value: 0n, timescale: 1000n }, tracks: [] }, tracks: [{ track_id: "invalid", kind: "video", clips: [clip("invalid-clip", assetA)] }] }, sources, "master"), /sequence timebase value and timescale must be positive/);
