import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { assertCreationPlanV1 } from "../../packages/platform/contract-runtime/src/public.js";
import { compileCreationPlan, resolveCommandEditIntent, type CommandEditIntent, type CreationCompileContext } from "../../packages/core/edit-ir/src/public.js";
import { createCommitPlan, simulateCommands, type Timeline } from "../../packages/core/timeline-core/src/public.js";

const plan = JSON.parse(readFileSync("contracts/examples/valid/editorial/creation-plan.v1.json", "utf8"));
assertCreationPlanV1(plan);
const time = (value: number, timescale = 30) => ({ schema_version: 1 as const, value, timescale });
const asset = plan.shots[0].source.asset_id as any;
plan.shots.push({ ...structuredClone(plan.shots[0]), shot_id: "reaction", source: { ...plan.shots[0].source, start: time(90), end: time(180) }, purpose: "Preserve the source reaction." });
plan.captions = [{ caption_id: "caption", shot_id: "shot-1", offset: time(0), duration: time(30), text: "actual words", kind: "verbatim", evidence_ids: ["quote-1"], audio_anchor: { kind: "embedded", id: "shot-1" } }];
plan.audio = [{ audio_id: "sound", shot_id: "reaction", source: { ...plan.shots[0].source, start: time(60), end: time(150) }, offset: time(-30), role: "dialogue", gain_db: -3, fade_in: time(3), fade_out: time(3), purpose: "J-cut with actual source audio." }];
const context: CreationCompileContext = { request_id: plan.request_id, revision: 1, input_digest: plan.input_digest, authorized_asset_ids: [asset], protected_refs: [], principle_ids: [], spans: [{ span_id: "evidence-1", asset_id: asset, start_pts: 0n, end_pts: 240n, timescale: 30n, has_video: true, has_audio: true, observations: [{ evidence_id: "visual-1", kind: "visual", start_pts: 0n, end_pts: 240n, timescale: 30n, text: "Fixture visual", uncertain: false }, { evidence_id: "audio-1", kind: "audio", start_pts: 0n, end_pts: 240n, timescale: 30n, text: "Fixture audio", uncertain: false }, { evidence_id: "quote-1", kind: "transcript", start_pts: 0n, end_pts: 30n, timescale: 30n, text: "actual words", uncertain: false }] }] };
const base: Timeline = { version: 0, tracks: [], sequence: { sequence_id: "main", timebase: { value: 1n, timescale: 30n }, tracks: [] } };
const commands = compileCreationPlan(plan, base, context);
const first = simulateCommands(base, commands);
const video = first.tracks.find(track => track.track_id === "video-main")!;
assert.deepEqual(video.clips.map(clip => clip.timeline_duration), [60n, 90n]);
assert.equal(video.captions![0].text, "actual words");
assert.equal(first.tracks.find(track => track.track_id === "audio-dialogue")!.clips[0].timeline_start, 30n);
assert.equal(first.tracks.find(track => track.track_id === "audio-dialogue")!.audio_routing![0].bus, "dialogue");
const revised = structuredClone(plan); revised.base_timeline_version = 1; revised.revision = 2;
revised.shots[0].source.end = time(45); revised.preserve_refs = ["reaction"];
revised.captions[0].text = "actual words in this source"; revised.captions[0].kind = "editorial"; revised.captions[0].audio_anchor = null;
const nextContext = { ...context, revision: 2, protected_refs: ["reaction"] };
const second = simulateCommands(first, compileCreationPlan(revised, first, nextContext));
const protectionIntent: CommandEditIntent = { intent_id: "fixture-protection", base_version: first.version, actor: { actor_id: "user", producer: "model" }, targets: [], commands: compileCreationPlan(revised, first, nextContext), semantic_refs: [], preconditions: [], protected_refs: ["clip:reaction"], provenance: { source_id: "fixture" }, reason: "verify hard protection", expected_effects: ["move"] };
assert.throws(() => resolveCommandEditIntent(protectionIntent, first), /EDIT_PROTECTED_REFERENCE:clip:reaction/);
assert.doesNotThrow(() => resolveCommandEditIntent({ ...protectionIntent, base_version: base.version, commands }, base), "a protected output can first be created; later changes remain denied");
const nextVideo = second.tracks.find(track => track.track_id === "video-main")!;
assert.equal(nextVideo.clips[1].timeline_start, 45n);
assert.deepEqual(nextVideo.clips[1].source, video.clips[1].source, "tightening opening keeps actual reaction content");
assert.equal(second.tracks.find(track => track.track_id === "audio-dialogue")!.clips[0].timeline_start, 15n, "linked audio follows the changed shot placement");
const forbidden = structuredClone(revised); forbidden.shots[1].source.end = time(179);
assert.throws(() => compileCreationPlan(forbidden, first, nextContext), /CREATION_PROTECTED_CONTENT_CHANGED:reaction/);
const fabricated = structuredClone(plan); fabricated.captions[0].text = "a fabricated quotation";
assert.throws(() => compileCreationPlan(fabricated, base, context), /CREATION_CAPTION_QUOTE_UNSUPPORTED:caption/);
const cropped = structuredClone(plan); cropped.shots[0].source.start = time(30);
assert.throws(() => compileCreationPlan(cropped, base, context), /CREATION_CAPTION_QUOTE_UNSUPPORTED:caption/, "a quote removed from audible source cannot remain verbatim");
assert.throws(() => compileCreationPlan(plan, base, { ...context, spans: context.spans.map(span => ({ ...span, observations: span.observations.filter(item => item.kind !== "visual") })) }), /CREATION_SOURCE_UNOBSERVED:.*:video/);
assert.throws(() => compileCreationPlan(plan, base, { ...context, spans: context.spans.map(span => ({ ...span, observations: span.observations.filter(item => item.kind === "visual") })) }), /CREATION_SOURCE_UNOBSERVED:.*:audio/);
const otherAsset = `asset:sha256:${"b".repeat(64)}` as any;
const crossContext: CreationCompileContext = { ...context, authorized_asset_ids: [asset, otherAsset], spans: [...context.spans, { ...context.spans[0]!, span_id: "other-sound", asset_id: otherAsset, has_video: false, observations: [{ evidence_id: "other-audio", kind: "audio", start_pts: 0n, end_pts: 240n, timescale: 30n, text: "Different source sound", uncertain: false }, { evidence_id: "other-quote", kind: "transcript", start_pts: 60n, end_pts: 90n, timescale: 30n, text: "Other source spoken words", uncertain: false }] }] };
const crossPlan = structuredClone(plan); crossPlan.audio[0].source.asset_id = otherAsset; crossPlan.audio[0].source.span_id = "other-sound";
crossPlan.captions = [{ caption_id: "j-caption", shot_id: "reaction", offset: time(-30), duration: time(30), text: "Other source spoken words", kind: "verbatim", evidence_ids: ["other-quote"], audio_anchor: { kind: "audio", id: "sound" } }];
const crossTimeline = simulateCommands(base, compileCreationPlan(crossPlan, base, crossContext));
assert.equal(crossTimeline.tracks.find(track => track.kind === "video")!.captions![0].timeline_start, 30n);
const crossRevision = structuredClone(crossPlan); crossRevision.base_timeline_version = 1; crossRevision.shots[0].source.end = time(45); crossRevision.preserve_refs = ["j-caption", "sound"];
const crossAfter = simulateCommands(crossTimeline, compileCreationPlan(crossRevision, crossTimeline, { ...crossContext, protected_refs: crossRevision.preserve_refs }));
assert.equal(crossAfter.tracks.find(track => track.kind === "video")!.captions![0].timeline_start, 15n, "preserved J-cut caption follows its actual independent audio anchor");
const wrongAnchor = structuredClone(crossPlan); wrongAnchor.captions[0].audio_anchor = { kind: "embedded", id: "reaction" };
assert.throws(() => compileCreationPlan(wrongAnchor, base, crossContext), /CREATION_CAPTION_QUOTE_UNSUPPORTED:j-caption/);
const wrongTiming = structuredClone(crossPlan); wrongTiming.captions[0].offset = time(-29);
assert.throws(() => compileCreationPlan(wrongTiming, base, crossContext), /CREATION_CAPTION_QUOTE_UNSUPPORTED:j-caption/);
const invalid = structuredClone(plan); invalid.shots[0].source.span_id = "unknown";
assert.throws(() => compileCreationPlan(invalid, base, context), /CREATION_SOURCE_DENIED:unknown/);
const inexact = structuredClone(plan); inexact.shots[0].source.end = time(1, 29);
assert.throws(() => compileCreationPlan(inexact, base, context), /CREATION_SOURCE_PTS_INEXACT/);
assert.throws(() => compileCreationPlan(plan, { ...base, sequence: undefined }, context), /CREATION_TIMEBASE_REQUIRED/);
assertCreationPlanV1(revised);
const samplePlan = structuredClone(plan);
samplePlan.audio[0].source = { asset_id: asset, span_id: "sample-audio", start: time(1, 48000), end: time(48001, 48000) };
samplePlan.audio[0].fade_in = time(1, 48000); samplePlan.audio[0].fade_out = time(0, 48000);
const sampleContext = { ...context, spans: [...context.spans, { ...context.spans[0]!, span_id: "sample-audio", start_pts: 0n, end_pts: 96000n, timescale: 48000n }] };
const sampleTimeline = simulateCommands(base, compileCreationPlan(samplePlan, base, sampleContext));
assert.equal(sampleTimeline.tracks.find(track => track.kind === "audio")!.clips[0].timeline_duration, 30n);
const reorderBase = structuredClone(first) as any;
reorderBase.tracks[0].captions.push({ ...reorderBase.tracks[0].captions[0], caption_id: "overlay", text: "second overlay" });
const reorder = createCommitPlan(reorderBase, [{ type: "set_track_properties", track_id: "video-main", properties: { captions: [...reorderBase.tracks[0].captions].reverse() } }]);
assert.deepEqual(reorder.plan.affected_ranges, [{ track_id: "video-main", start: 0n, end: 30n }], "caption paint-order changes must remain protected by range locks");
for (const grade of [{ lut_path: "C:/private/look.cube" }, { brightness: 0.1 }, { gamma: 1.1 }]) {
  const graded = structuredClone(first) as any;
  graded.tracks[0].clips[0].grade = { grade_id: "existing-look", ...grade };
  assert.throws(() => compileCreationPlan(revised, graded, nextContext), /CREATION_EXISTING_SEMANTICS_UNREPRESENTED:shot-1/, "unrelated requested edits must not discard an unrepresented existing look");
}
console.log("Stage3 declarative multi-shot/caption/audio compilation, linked timing, protected content and exact-source failures passed (fixtures only)");
