import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { beginCreation, startCreationRun, reserveCreationCall, settleCreationCall, reviseCreation, assertCreationCommit, CreationError, type CreationModelCall, type CreationModelSettlement, type CreationState } from "../../packages/platform/project-host/src/stage3-request.js";
import { validateCreationTransition } from "../../packages/platform/contract-runtime/src/public.js";
const now = "2026-09-20T01:00:00Z";
const fixture = JSON.parse(readFileSync("contracts/examples/valid/editorial/creation-session.v1.json", "utf8")) as CreationState;
const authorization = { ...fixture.authorization };
const started = startCreationRun(beginCreation(authorization, 0, now), "run-1", 0, "a".repeat(64), null, now), ticket = started.active_run!;
const call: CreationModelCall = { call_id: "call-1", run_id: ticket.run_id, revision: 1, attempt: 1, provider: authorization.provider, model: authorization.model, input_digest: ticket.input_digest, wire_digest: "b".repeat(64),  profile: null, input_bytes: 100,    dispatch_committed_at: now, settlement: null };
const code = (expected: string) => (error: unknown) => error instanceof CreationError && error.code === expected;
let state = reserveCreationCall(started, ticket, call, 0, now);
validateCreationTransition(started, state, "metadata");
assert.equal(state.model_calls[0].settlement, null);
const second = reserveCreationCall(state, ticket, { ...call, call_id: "call-2", attempt: 2 }, 0, now);
validateCreationTransition(state, second, "metadata"); assert.equal(second.model_calls.length, 2);
assert.throws(() => reserveCreationCall(state, ticket, call, 0, now), code("REQUEST_CALL_ALREADY_RESERVED"));
const unknown: CreationModelSettlement = { status: "failed", code: "MODEL_PROVIDER_FAILED", reason_code: "MODEL_PROVIDER_FAILED", usage: null, cost: null, output_digest: null, completed_at: now };
const failed = settleCreationCall(state, call.call_id, unknown);
assert.equal(failed.model_calls[0].settlement!.usage, null); assert.equal(failed.model_calls[0].settlement!.cost, null);
assert.deepEqual(settleCreationCall(failed, call.call_id, unknown), failed);
assert.throws(() => settleCreationCall(failed, call.call_id, { ...unknown, code: "OTHER" }), code("REQUEST_SETTLEMENT_CONFLICT"));
const revised = reviseCreation(state, 1, { raw_text: "new user requirement", base_timeline_version: 0, viewed_timeline_version: null, preserve_refs: [], created_at: now });
const settled = settleCreationCall(revised, call.call_id, { ...unknown, status: "cancelled", code: "MODEL_CANCELLED", reason_code: "REQUEST_REVISION_STALE", usage: { input: 10, output: 5, total: 15 } });
validateCreationTransition(revised, settled, "metadata");
assert.deepEqual(settled.revisions, revised.revisions); assert.equal(settled.status, "received"); assert.equal(settled.active_run, null);
assert.deepEqual(settled.model_calls[0].settlement!.usage, { input: 10, output: 5, total: 15 }); assert.equal(settled.model_calls[0].settlement!.cost, null);
const breached = settleCreationCall(state, call.call_id, { ...unknown, usage: { input: 90, output: 21, total: 111 } });
validateCreationTransition(state, breached, "metadata");
assert.equal(breached.model_calls[0].settlement!.usage!.input, 90);
assertCreationCommit(breached, ticket, 0, null, now);
assert.throws(() => validateCreationTransition(state, { ...state, sequence: state.sequence + 1, model_calls: [] }, "metadata"), code("REQUEST_LEDGER_MUTATION_INVALID"));
assert.throws(() => validateCreationTransition(state, { ...state, sequence: state.sequence + 1, model_calls: [{ ...call, input_bytes: 1 }] }, "metadata"), code("REQUEST_CALL_IMMUTABLE"));
console.log("Stage3 immutable dispatch records, unknown charges, late settlements and actual usage passed (fixtures only)");
