import assert from "node:assert/strict";
import { feedbackTargetKey, prepareStage2ContractDraft, prepareStage2FeedbackRequest, prepareStage2MaterialGeneration, stage2IntentControlState } from "../../apps/desktop/src/renderer/features/stage2-workspace.js";

const contractWorkspace = { workspace_digest: "0".repeat(64), contract: null };
const contractFields = { creatorGoal: "  Evidence-bound trip recap  ", audience: "friends，family,friends", platforms: "youtube, local", targetDurationSeconds: "60", requirements: "Use approved footage\nPreserve chronology", desiredTraits: "warm,clear", forbiddenMisrepresentation: "invented event", privacyPolicyId: "privacy-current", privacyPolicyVersion: "3", privacyPolicyDigest: "A".repeat(64), rightsPolicyId: "rights-current", rightsPolicyVersion: "5", rightsPolicyDigest: "b".repeat(64), protectedRefs: "clip:user-lock", allowedTransformations: "trim,reorder", forbiddenOutcomes: "fabrication" };
const contractRequest = prepareStage2ContractDraft(contractWorkspace, contractFields);
assert.equal(contractRequest.workspace_digest, contractWorkspace.workspace_digest); assert.equal(contractRequest.creator_goal, "Evidence-bound trip recap"); assert.deepEqual(contractRequest.audience, ["friends", "family"]); assert.deepEqual(contractRequest.requirements, ["Use approved footage", "Preserve chronology"]); assert.deepEqual(contractRequest.privacy_policy_ref, { object_id: "privacy-current", object_version: 3, digest: "a".repeat(64) }); assert.equal("project_id" in contractRequest, false); assert.equal("status" in contractRequest, false); assert.equal("approval" in contractRequest, false);
assert.throws(() => prepareStage2ContractDraft(contractWorkspace, { ...contractFields, rightsPolicyDigest: "test-placeholder" }), /权利策略必须填写精确/);
assert.throws(() => prepareStage2ContractDraft({ ...contractWorkspace, contract: { object_id: "existing" } }, contractFields), /已存在 Creative Contract/);

const feedbackCandidate = { object_id: "intent-feedback", status: "candidate", feedback_diagnosis_ref: { object_id: "diagnosis", object_version: 1, digest: "a".repeat(64) } };
assert.deepEqual(stage2IntentControlState(feedbackCandidate, undefined, undefined, false), { stale: false, rejected: false, canApprove: true, canExecute: false, canReviewFeedback: true });
assert.deepEqual(stage2IntentControlState(feedbackCandidate, { decision_id: "approval" }, undefined, false), { stale: false, rejected: false, canApprove: false, canExecute: true, canReviewFeedback: true });
assert.deepEqual(stage2IntentControlState({ ...feedbackCandidate, status: "rejected" }, undefined, undefined, false), { stale: false, rejected: true, canApprove: false, canExecute: false, canReviewFeedback: false }, "Host-terminal rejection must remain closed after its rejection decision expires from the current approval view");
assert.deepEqual(stage2IntentControlState({ ...feedbackCandidate, status: "stale" }, undefined, undefined, false), { stale: true, rejected: false, canApprove: false, canExecute: false, canReviewFeedback: false });
const firstTarget = { track_id: "video-main", clip_id: "clip-a" }, secondTarget = { track_id: "video-main", clip_id: "clip-b" };
assert.notEqual(feedbackTargetKey(firstTarget), feedbackTargetKey(secondTarget), "feedback target identity must distinguish clips on the same track");
assert.equal(feedbackTargetKey(firstTarget), JSON.stringify(["video-main", "clip-a"]), "feedback target identity must bind the exact track and clip");
const source = (asset_id, start, end) => ({ asset_id, start: { schema_version: 1, value: start, timescale: 10 }, end: { schema_version: 1, value: end, timescale: 10 } });
const feedbackWorkspace = { review: { current_execution_id: "execution-current" }, executions: [{ execution_id: "execution-current" }], timeline: { editable_targets: [{ ...firstTarget, asset_id: "asset-a", source: source("asset-a", 0, 100) }, { ...secondTarget, asset_id: "asset-b", source: source("asset-b", 10, 210) }] } };
const secondRequest = prepareStage2FeedbackRequest(feedbackWorkspace, "缩短我选择的第二个镜头", "1", feedbackTargetKey(feedbackWorkspace.timeline.editable_targets[1]), "second-target");
assert.deepEqual(secondRequest.target, { track_id: "video-main", clip_id: "clip-b", proposed_source: { asset_id: "asset-b", start: { schema_version: 1, value: 10, timescale: 10 }, end: { schema_version: 1, value: 200, timescale: 10 } } }, "multi-clip feedback must bind the explicitly selected second clip");
let preparedCommands = 0;
const prepareThenCountCommand = (targetKey) => { const request = prepareStage2FeedbackRequest(feedbackWorkspace, "明确局部反馈", "1", targetKey, "fail-closed"); preparedCommands += 1; return request; };
assert.throws(() => prepareThenCountCommand(""), /请选择当前 Timeline 中要修改的具体镜头/);
assert.throws(() => prepareThenCountCommand(JSON.stringify(["video-main", "clip-stale"])), /请选择当前 Timeline 中要修改的具体镜头/);
assert.equal(preparedCommands, 0, "empty or stale target identity must fail before a Host command can be prepared");
const materialWorkspace = { contract: { status: "approved" }, timeline: feedbackWorkspace.timeline };
const materialRequest = prepareStage2MaterialGeneration(materialWorkspace, feedbackTargetKey(feedbackWorkspace.timeline.editable_targets[1]), "事实一\n事实二\n事实一");
assert.deepEqual(materialRequest, { stage: "material", target: { track_id: "video-main", clip_id: "clip-b" }, evidence_statements: ["事实一", "事实二"] });
assert.equal("workspace_digest" in materialRequest, false, "Renderer helper must not cache or replace the live workspace identity appended by the command action");
assert.throws(() => prepareStage2MaterialGeneration(materialWorkspace, JSON.stringify(["video-main", "locked-clip"]), "事实"), /请选择当前 Timeline 中可编辑的具体镜头/);
console.log("Stage 2 Renderer terminal intent control checks passed");
