import assert from "node:assert/strict";
// The current Renderer replaced the historical Stage2 entry; keep this required
// command exercising the current exact-time, explicit-target and consent boundary.
import { authorizationAssets, exactTicks, explicitList, prepareCreationAuthorization, manualCommands } from "../../apps/desktop/src/renderer/features/creation-workspace.js";
const base = { value: 1n, timescale: 24n };
assert.throws(() => exactTicks("0.1", base), /精确落在当前帧边界/);
assert.equal(exactTicks("0.125", base), 3n);
assert.equal(exactTicks("1001/30000", { value: 1001n, timescale: 30000n }), 1n);
assert.equal(exactTicks("7/1001", { value: 1n, timescale: 1001n }), 7n);
assert.equal(exactTicks("9007199254740993", { value: 1n, timescale: 1n }), 9007199254740993n);
for (const input of ["-1", "1/0", "NaN", "1e3", ""]) assert.throws(() => exactTicks(input, base));
for (const invalid of [null, { value: 0n, timescale: 24n }, { value: 1n, timescale: 0n }, { value: 1, timescale: 24 }]) assert.throws(() => exactTicks("1", invalid), /精确时间基/);
assert.deepEqual(explicitList("a，b\nc"), ["a", "b", "c"]); assert.throws(() => explicitList("a,a"), /重复/);
const media = [{ asset_id: "a", location_type: "original" }, { asset_id: "a", location_type: "proxy" }, { asset_id: "a", location_type: "original" }, { asset_id: "b", location_type: "proxy" }, { asset_id: "c", location_type: "original" }];
assert.deepEqual(authorizationAssets(media).map(item => item.asset_id), ["a", "c"], "one asset is authorized once, and a proxy alone cannot supply an Original");
const values = { original_text: "  保留原话 1n\n两段画面  ", provider: " qwen ", model: " fixture ", asset_ids: ["a"], allowed_data: ["request"], protected_refs: "clip-b", expires_at: "2027-01-01T00:00:00Z" };
const prepared = prepareCreationAuthorization(values, "request-a");
assert.equal(prepared.original_text, values.original_text); assert.deepEqual(prepared.protected_refs, ["clip-b"]); assert.equal("budget" in prepared, false);
assert.deepEqual(prepared.allowed_data, ["request"]); assert.equal(prepared.provider, "qwen");
for (const forbidden of ["actor_id", "project_id", "approval", "credential"]) assert.equal(forbidden in prepared, false);
prepared.asset_ids.push("another"); assert.deepEqual(values.asset_ids, ["a"]);
assert.throws(() => prepareCreationAuthorization({ ...values, asset_ids: [] }, "request-b"));
assert.throws(() => prepareCreationAuthorization({ ...values, expires_at: "" }, "request-b"));
const timeline = { version: 3, sequence: { timebase: base }, tracks: [{ track_id: "video", kind: "video", clips: [{ clip_id: "a" }, { clip_id: "b" }] }, { track_id: "audio", kind: "audio", clips: [{ clip_id: "a" }] }] };
const edit = { target: JSON.stringify(["video", "b"]), raw_text: "只修改第二个镜头，保留第一个", placement_text: "0.125", gain_db: "-6", caption_text: "1n", caption_start: "0", caption_duration: "0.5" };
const commands = manualCommands(timeline, edit, "actual-edit");
assert.deepEqual(commands, [{ type: "move_clip", track_id: "video", clip_id: "b", timeline_start: 3n }, { type: "set_gain", track_id: "video", clip_id: "b", gain_db: -6 }, { type: "add_caption", track_id: "video", caption: { caption_id: "caption:actual-edit", text: "1n", timeline_start: 0n, timeline_duration: 12n } }]);
let sent = 0;
for (const target of ["", JSON.stringify(["video", "missing"]), JSON.stringify(["missing", "b"])]) assert.throws(() => { manualCommands(timeline, { ...edit, target }, "bad"); sent++; }, /具体镜头|请选择/);
assert.equal(sent, 0, "empty or stale targets cannot prepare a Host command");
assert.throws(() => manualCommands(timeline, { ...edit, placement_text: "0.1" }, "bad"), /帧边界/);
assert.throws(() => manualCommands(timeline, { ...edit, target: JSON.stringify(["audio", "a"]) }, "bad"), /字幕必须放在视频轨/);
for (const gain of [" ", "Infinity", "NaN"]) assert.throws(() => manualCommands(timeline, { ...edit, gain_db: gain }, "bad"), /音量/);
assert.throws(() => manualCommands(timeline, { ...edit, caption_duration: "0" }, "bad"), /时长必须为正/);
assert.throws(() => manualCommands(timeline, { ...edit, raw_text: " " }, "bad"));
assert.throws(() => manualCommands(timeline, { ...edit, placement_text: "", gain_db: "", caption_text: "" }, "bad"), /至少一项实际修改/);
console.log("Current Renderer exact-time, bounded consent, unique assets, raw text and explicit multi-clip target checks passed");
