import { strict as assert } from "node:assert";
import { validateRendererUrl } from "../../apps/desktop/src/main/validate-sender.js";
import { registerCreationHandlers,creationTimelineProjection } from "../../apps/desktop/src/main/ipc/creation.handlers.js";
import { creationErrorResult } from "../../apps/desktop/src/main/ipc/creation-errors.js";
import { CreationError } from "../../packages/platform/contract-runtime/src/public.js";
import { ModelGatewayError } from "../../packages/platform/model-gateway/src/public.js";

assert.doesNotThrow(()=>validateRendererUrl("app://renderer/index.html"));
for(const url of ["file:///index.html","app://evil/index.html","app://renderer.evil/index.html","https://renderer/index.html"])assert.throws(()=>validateRendererUrl(url),/untrusted/);
const commands=new Map<string,any>(),queries=new Map<string,any>(),credential={},accepted:any[]=[];
registerCreationHandlers(queries,commands,{creationCredential:credential,host:{cancelCreationRequest(channel:object,request_id:string,revoke:boolean){assert.equal(channel,credential);accepted.push({request_id,revoke});return {authorization:{request_id},sequence:2};}}} as any,async()=>{throw new Error("unexpected dialog");},async()=>{throw new Error("unexpected save dialog");});
for(const removed of ["project.timeline.command","project.timeline.undo","project.timeline.redo","project.stage2.action","project.stage2.generate"])assert.equal(commands.has(removed),false,removed);
const cancel=commands.get("project.creation.cancel");assert.ok(cancel);
assert.deepEqual(cancel({payload:{request_id:"owned",revoke:false}}),{request_id:"owned",sequence:2});
for(const payload of [{request_id:"owned",revoke:"false"},{request_id:"",revoke:false},{request_id:"owned",revoke:false,credential:{}}])assert.throws(()=>cancel({payload}),/操作|布尔值|指定/);
assert.equal(accepted.length,1,"invalid explicit command envelopes must not enter Host");
const raw={version:1,sequence:{sequence_id:"main",timebase:{value:1n,timescale:30n},tracks:[]},tracks:[{track_id:"video",kind:"video",clips:[{clip_id:"clip",source:{asset_id:"asset",start_pts:0n,end_pts:1n,timescale:30n},timeline_start:0n,timeline_duration:1n,grade:{lut_path:"PRIVATE_PATH"},semantic_sidecar:{metadata:{private:"PRIVATE_CONTEXT"}}}],captions:[{caption_id:"caption",text:"1n",timeline_start:0n,timeline_duration:1n,style:{private:"PRIVATE_STYLE"}}]}]};
const projected=JSON.stringify(creationTimelineProjection(raw),(_,v)=>typeof v==="bigint"?String(v):v);assert.equal(projected.includes("PRIVATE"),false);assert.ok(projected.includes('"text":"1n"'));
const error=creationErrorResult("COMMAND_FAILED",new CreationError("REQUEST_BASE_STALE","PRIVATE_PATH PRIVATE_CONTEXT"));assert.equal(error.error.code,"REQUEST_BASE_STALE");assert.equal(JSON.stringify(error).includes("PRIVATE"),false);
assert.equal(creationErrorResult("QUERY_FAILED",new Error("private credential in message")).error.code,"QUERY_FAILED");
const providerCause = new Error("PRIVATE_ENDPOINT PRIVATE_TOKEN PRIVATE_INPUT");
const providerFailure = creationErrorResult("COMMAND_FAILED", new ModelGatewayError("MODEL_PROVIDER_FAILED", "PRIVATE_OUTPUT", { cause: providerCause }));
assert.equal(providerFailure.error.code, "MODEL_PROVIDER_FAILED");
assert.match(providerFailure.error.message, /模型服务未能完成这次请求/);
assert.match(providerFailure.error.message, /已保存的作品版本仍保留/);
assert.match(providerFailure.error.message, /本地记录/);
assert.doesNotMatch(providerFailure.error.message, /MODEL_PROVIDER_FAILED|未提交|PRIVATE/);
assert.deepEqual(Object.keys(providerFailure.error).sort(), ["code", "message"], "IPC projects safe copy only, never cause or stack");
const invalidTiming = creationErrorResult("COMMAND_FAILED", new ModelGatewayError("MODEL_OUTPUT_INVALID", "private planner output", { cause: new CreationError("CREATION_DURATION_TARGET_UNMET", "private source path") }));
assert.equal(invalidTiming.error.code, "MODEL_OUTPUT_INVALID"); assert.ok(invalidTiming.error.message.includes("总时长不符合当前要求")); assert.equal(invalidTiming.error.message.includes("private"), false);
const exportCommands = new Map<string, any>(); let masterReads = 0, staleExport = false;
const exportContext = { creationCredential: credential, host: { readCreationDraftMaster(channel: object) { assert.equal(channel, credential); masterReads++; return { timeline_version: 4, output_hash: "a".repeat(64), bytes: Buffer.from("verified fixture") }; } }, sessions: { assertCurrent() { if (staleExport) throw new Error("export project changed while dialog was open"); } } } as any;
registerCreationHandlers(new Map(), exportCommands, exportContext, async () => { throw new Error("unexpected confirmation"); }, async (_context, _event, _operation, options) => { assert.equal(options.defaultPath, "AVE-v4.mp4"); return { canceled: true }; });
const exportRequest = { payload: { request_id: "owned", draft_id: "draft", render_id: "render" } };
await assert.rejects(exportCommands.get("project.creation.export")(exportRequest, {}, {}), (error: any) => {
  const result=creationErrorResult("COMMAND_FAILED",error);
  assert.equal(result.error.code,"DESKTOP_EXPORT_CANCELLED");
  assert.match(result.error.message,/已取消导出，未保存新的成片文件/);
  assert.doesNotMatch(result.error.message,/核对当前状态与授权|导出操作已完成/);
  return true;
});
staleExport = true;
await assert.rejects(exportCommands.get("project.creation.export")(exportRequest, {}, {}), /export project changed while dialog was open/);
assert.equal(masterReads, 2, "cancelled or stale native selection never reaches second authority read or file write");
console.log("IPC sender, current route isolation, trusted channel forwarding and safe projections passed");
