import { strict as assert } from "node:assert";
import { validateRendererUrl } from "../../apps/desktop/src/main/validate-sender.js";
import { registerCreationHandlers,creationTimelineProjection } from "../../apps/desktop/src/main/ipc/creation.handlers.js";
import { creationErrorResult } from "../../apps/desktop/src/main/ipc/creation-errors.js";
import { CreationError } from "../../packages/platform/contract-runtime/src/public.js";

assert.doesNotThrow(()=>validateRendererUrl("app://renderer/index.html"));
for(const url of ["file:///index.html","app://evil/index.html","app://renderer.evil/index.html","https://renderer/index.html"])assert.throws(()=>validateRendererUrl(url),/untrusted/);
const commands=new Map<string,any>(),queries=new Map<string,any>(),credential={},accepted:any[]=[];
registerCreationHandlers(queries,commands,{creationCredential:credential,host:{cancelCreationRequest(channel:object,request_id:string,revoke:boolean){assert.equal(channel,credential);accepted.push({request_id,revoke});return {authorization:{request_id},sequence:2};}}} as any,async()=>{throw new Error("unexpected dialog");});
for(const removed of ["project.timeline.command","project.timeline.undo","project.timeline.redo","project.stage2.action","project.stage2.generate"])assert.equal(commands.has(removed),false,removed);
const cancel=commands.get("project.creation.cancel");assert.ok(cancel);
assert.deepEqual(cancel({payload:{request_id:"owned",revoke:false}}),{request_id:"owned",sequence:2});
for(const payload of [{request_id:"owned",revoke:"false"},{request_id:"",revoke:false},{request_id:"owned",revoke:false,credential:{}}])assert.throws(()=>cancel({payload}),/操作|布尔值|指定/);
assert.equal(accepted.length,1,"invalid explicit command envelopes must not enter Host");
const raw={version:1,sequence:{sequence_id:"main",timebase:{value:1n,timescale:30n},tracks:[]},tracks:[{track_id:"video",kind:"video",clips:[{clip_id:"clip",source:{asset_id:"asset",start_pts:0n,end_pts:1n,timescale:30n},timeline_start:0n,timeline_duration:1n,grade:{lut_path:"PRIVATE_PATH"},semantic_sidecar:{metadata:{private:"PRIVATE_CONTEXT"}}}],captions:[{caption_id:"caption",text:"1n",timeline_start:0n,timeline_duration:1n,style:{private:"PRIVATE_STYLE"}}]}]};
const projected=JSON.stringify(creationTimelineProjection(raw),(_,v)=>typeof v==="bigint"?String(v):v);assert.equal(projected.includes("PRIVATE"),false);assert.ok(projected.includes('"text":"1n"'));
const error=creationErrorResult("COMMAND_FAILED",new CreationError("REQUEST_BASE_STALE","PRIVATE_PATH PRIVATE_CONTEXT"));assert.equal(error.error.code,"REQUEST_BASE_STALE");assert.equal(JSON.stringify(error).includes("PRIVATE"),false);
assert.equal(creationErrorResult("QUERY_FAILED",new Error("private credential in message")).error.code,"QUERY_FAILED");
console.log("IPC sender, current route isolation, trusted channel forwarding and safe projections passed");
