export const featureId = "delivery" as const;
import type { DeliveryManifest, ExportCapability, ExportProfile, ExportRegistration, RightsLedgerEntry } from "../../../core/editorial-core/src/public.js";
export type DeliveryCommand = Readonly<{ type: string; payload: unknown }>;
export type DeliveryQuery = Readonly<{ type: string; parameters?: Readonly<Record<string, unknown>> }>;
export type DeliveryFeatureDescriptor = Readonly<{ feature_id: typeof featureId; label: "delivery"; owner: "project-host"; layers: readonly ["commands", "queries", "use-cases", "policies", "validators", "prompts", "ports"] }>;
export const descriptor: DeliveryFeatureDescriptor = Object.freeze({ feature_id: featureId, label: "delivery", owner: "project-host", layers: ["commands", "queries", "use-cases", "policies", "validators", "prompts", "ports"] as const });
export const exportCapabilities: Readonly<Record<string, ExportCapability>> = { social_1080p: { schema_version: 1, capability_id: "social-1080p", container: "mp4", video_codec: "h264", audio_codec: "aac", min_width: 1280, max_width: 1920, min_height: 720, max_height: 1080, min_fps: 23.976, max_fps: 60, audio_sample_rates: [44100, 48000] }, archive_4k: { schema_version: 1, capability_id: "archive-4k", container: "mp4", video_codec: "h264", audio_codec: "aac", min_width: 3840, max_width: 3840, min_height: 2160, max_height: 2160, min_fps: 23.976, max_fps: 60, audio_sample_rates: [48000] }, vertical_short: { schema_version: 1, capability_id: "vertical-short", container: "mp4", video_codec: "h264", audio_codec: "aac", min_width: 1080, max_width: 1080, min_height: 1920, max_height: 1920, min_fps: 24, max_fps: 60, audio_sample_rates: [44100, 48000] } };
export function validateDelivery(manifest: DeliveryManifest): DeliveryManifest { const gates = manifest.gates; if (gates.qc !== "passed" || gates.privacy === "blocked" || gates.rights !== "passed" || gates.original_link !== "verified") throw new Error("delivery gates are not satisfied"); return { ...manifest, status: "ready" }; }
export function approveRights(entry: RightsLedgerEntry): RightsLedgerEntry { if (entry.status !== "pending") throw new Error("rights entry is not pending"); if (!entry.license_id.trim()) throw new Error("license is required"); return { ...entry, status: "approved" }; }
export function validateExportRegistration(registration: ExportRegistration, delivery: DeliveryManifest, qcReportId: string): void { if (registration.delivery_id !== delivery.delivery_id) throw new Error("export delivery mismatch"); if (delivery.status !== "ready") throw new Error("delivery is not ready"); if (registration.qc_report_id !== qcReportId) throw new Error("export QC report mismatch"); if (!/^[0-9a-f]{64}$/.test(registration.sha256)) throw new Error("export hash is invalid"); }
export function validateExportProfile(profile: ExportProfile, capability: ExportCapability): void { if (profile.container !== capability.container || profile.video_codec !== capability.video_codec || profile.audio_codec !== capability.audio_codec) throw new Error("export format is unsupported"); if (profile.width < capability.min_width || profile.width > capability.max_width || profile.height < capability.min_height || profile.height > capability.max_height) throw new Error("export dimensions are unsupported"); if (profile.fps < capability.min_fps || profile.fps > capability.max_fps) throw new Error("export frame rate is unsupported"); if (!capability.audio_sample_rates.includes(profile.audio_sample_rate)) throw new Error("export audio sample rate is unsupported"); }
