export const featureId = "assembly-cut" as const;
import type { ApprovedStoryPlan, AssemblyCut, AssemblyEditOperation } from "../../../core/editorial-core/src/public.js";
export type AssemblyCutCommand = Readonly<{ type: string; payload: unknown }>;
export type AssemblyCutQuery = Readonly<{ type: string; parameters?: Readonly<Record<string, unknown>> }>;
export type AssemblyCutFeatureDescriptor = Readonly<{ feature_id: typeof featureId; label: "assembly cut"; owner: "project-host"; layers: readonly ["commands", "queries", "use-cases", "policies", "validators", "prompts", "ports"] }>;
export const descriptor: AssemblyCutFeatureDescriptor = Object.freeze({ feature_id: featureId, label: "assembly cut", owner: "project-host", layers: ["commands", "queries", "use-cases", "policies", "validators", "prompts", "ports"] as const });
function validateEvidenceReferences(evidenceIds: readonly string[], knownEvidence: ReadonlySet<string>): void { if (evidenceIds.length === 0 || evidenceIds.some((id) => !knownEvidence.has(id))) throw new Error("all evidence references must be known"); }
export function validateAssemblyCut(cut: AssemblyCut, plan: ApprovedStoryPlan, approvedEvidence: ReadonlySet<string>): AssemblyCut { if (cut.approved_plan_id !== plan.plan_id) throw new Error("assembly plan mismatch"); const beatIds = new Set(plan.beats.map((beat) => beat.beat_id)); if (cut.clips.some((clip) => !beatIds.has(clip.beat_id))) throw new Error("assembly clip references unknown beat"); for (const clip of cut.clips) { validateEvidenceReferences(clip.evidence_ids, approvedEvidence); if (clip.end_pts <= clip.start_pts) throw new Error("assembly clip range must be positive"); } return { ...cut, status: "validated" }; }
export function compileAssemblyToEditIR(cut: AssemblyCut): readonly AssemblyEditOperation[] { if (cut.status !== "validated") throw new Error("only validated assembly cuts can compile"); return cut.clips.map((clip) => { if (clip.end_pts <= clip.start_pts) throw new Error("assembly clip range must be positive"); return { operation: "add", clip_id: clip.clip_id, asset_id: clip.asset_id, start_pts: clip.start_pts, end_pts: clip.end_pts, evidence_ids: clip.evidence_ids, beat_id: clip.beat_id }; }); }
