import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chmod, mkdtemp, readFile, rm, stat, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { ProjectHostSession } from "../../packages/platform/project-host/src/public.js";
import { builtInCreativeSkillDefinitions, creativeSkillDefinitionDigest } from "../../packages/core/editorial-core/src/public.js";
import { registerAssetLocation, registerCreativeSkillDefinition, registerMaterialEvidencePack, registerMediaAsset } from "../../packages/platform/project-storage/src/public.js";
import type { AssetId } from "../../packages/core/media-identity/src/public.js";
import { createStage2HumanReview } from "./stage2-human-review-helper.js";

const digest = (character: string) => character.repeat(64);
const root = await mkdtemp(resolve(tmpdir(), "ave-creative-skill-host-"));
const humanReview = createStage2HumanReview("user-1", "2026-08-24T00:00:30.000Z");
let host: ProjectHostSession | undefined;
let reopened: ProjectHostSession | undefined;
try {
  const activeHost = new ProjectHostSession(humanReview.options);
  host = activeHost;
  await activeHost.create(root);
  const session = (activeHost as any).session;
  const projectId = session.manifest.project_id as string;
  const draft = activeHost.createCreativeContractDraft({ project_id: projectId, contract_id: "contract-skill", creator_goal: "Create a truthful reaction-led trip recap", audience: ["friends"], platforms: ["youtube"], target_duration: { schema_version: 1, value: 60, timescale: 1 }, requirements: [{ requirement_id: "req-evidence", kind: "hard", statement: "Use approved evidence", priority: 100 }], voice_and_identity: { desired_traits: ["warm"], forbidden_misrepresentation: ["invented emotion"] }, privacy_policy_ref: { object_id: "privacy", object_version: 1, digest: digest("a") }, rights_policy_ref: { object_id: "rights", object_version: 1, digest: digest("b") }, approval_policy: { mode: "explicit_user", actor_kind: "user" }, protected_refs: [], allowed_transformations: ["trim"], forbidden_outcomes: ["fabricated fact"], created_at: "2026-08-24T00:00:00.000Z", provenance: { producer: "user", source_id: "contract-form", source_version: "current", policy_version: "knowledge-v1", input_refs: [], unresolved_assumptions: [] } });
  const review = activeHost.registerCreativeContractDraft({ ...draft, status: "review" }) as any;
  const approved = activeHost.approveCreativeContract(await humanReview.approveContract(activeHost, "approval-skill-contract", draft.contract_id, 1, review.object_hash)) as any;
  const contractRef = { object_id: draft.contract_id, object_version: 2, digest: approved.object_hash };

  const mediaPath = resolve(root, "originals", "skill-evidence.bin");
  const mediaBytes = Buffer.from("approved reaction evidence fixture");
  await writeFile(mediaPath, mediaBytes);
  const normalizedTime = new Date(Math.floor(Date.now() / 1000) * 1000);
  await utimes(mediaPath, normalizedTime, normalizedTime);
  const mediaDigest = createHash("sha256").update(mediaBytes).digest("hex");
  const mediaStat = await stat(mediaPath);
  const asset = `asset:sha256:${mediaDigest}` as AssetId;
  registerMediaAsset(session, projectId, { asset_id: asset, algorithm: "sha256", digest: mediaDigest, byte_length: mediaBytes.byteLength, stream_facts: { duration_pts: 48000, timescale: 48000 } });
  registerAssetLocation(session, projectId, { asset_location_id: "original-skill", asset_id: asset, location_type: "original", location_ref: mediaPath, verified_at: "2026-08-24T00:02:00.000Z", metadata: { verification_status: "verified", fingerprint: { algorithm: "sha256", digest: mediaDigest, byte_length: mediaBytes.byteLength }, file_stat: { size: mediaStat.size, mtime_ms: mediaStat.mtimeMs } } });
  await activeHost.recordMaterialPermission(await humanReview.materialPermission(activeHost, "approval-skill-material", { contract_ref: contractRef, asset_id: asset, asset_location_id: "original-skill", location_ref: mediaPath, verified_at: "2026-08-24T00:02:00.000Z", permission_state: "authorized", policy_ref: draft.rights_policy_ref }));
  const immutableLocation = session.db.prepare(
    "SELECT location_ref, metadata_json FROM asset_locations WHERE project_id = ? AND asset_id = ? AND location_type = 'immutable_original'",
  ).get(projectId, asset) as { location_ref: string; metadata_json: string } | undefined;
  assert.ok(immutableLocation, "material permission must create a project-owned immutable Original");
  const immutableMetadata = JSON.parse(immutableLocation.metadata_json) as { file_stat: { mtime_ms: number } };
  const immutableMediaPath = immutableLocation.location_ref;
  const immutableBytes = await readFile(immutableMediaPath);
  const immutableFileTime = new Date(immutableMetadata.file_stat.mtime_ms);
  const approvedEvidence = { evidence_id: "asr:reaction", analysis_type: "asr", asset_id: asset, start_pts: 0, end_pts: 48000, timescale: 48000, evidence_version: 1, review_status: "candidate", text: "I could not believe we finally arrived" }; activeHost.registerEvidence(approvedEvidence); await humanReview.approveEvidence(activeHost, "approval-evidence-skill", approvedEvidence);
  const pack = await activeHost.assembleMaterialEvidencePack({ pack_id: "pack-skill", contract_ref: contractRef, evidence_ids: ["asr:reaction"], coverage_matrix: { schema_version: 1, matrix_id: "coverage-skill", rows: [{ requirement_id: "req-evidence", evidence_ids: ["asr:reaction"], status: "covered" }] }, expected_media_verified_at: { [asset]: "2026-08-24T00:02:00.000Z" }, policy_version: "knowledge-v1", created_at: "2026-08-24T00:03:00.000Z" }) as any;
  await assert.rejects(() => activeHost.assembleMaterialEvidencePack({ pack_id: "pack-leap-expiry", contract_ref: contractRef, evidence_ids: ["asr:reaction"], coverage_matrix: { schema_version: 1, matrix_id: "coverage-leap-expiry", rows: [{ requirement_id: "req-evidence", evidence_ids: ["asr:reaction"], status: "covered" }] }, expected_media_verified_at: { [asset]: "2026-08-24T00:02:00.000Z" }, policy_version: "knowledge-v1", created_at: "2026-08-24T00:03:00.000Z", expires_at: "2016-12-31T23:59:60Z" }), /expiry is stale or invalid/);
  const legacyLeapPackValue = { ...pack.value, pack_id: "pack-legacy-leap", input_fingerprint: digest("7"), expires_at: "2016-12-31T23:59:60Z" };
  registerMaterialEvidencePack(session, projectId, legacyLeapPackValue);
  const legacyLeapView = await activeHost.readMaterialEvidencePack(legacyLeapPackValue.pack_id, 1) as any;
  assert.equal(legacyLeapView.lifecycle_status, "stale");
  assert.ok(legacyLeapView.stale_reasons.includes("pack_expiry_invalid"));

  const definition = builtInCreativeSkillDefinitions[0]!;
  const pinned = activeHost.pinBuiltInCreativeSkillDefinition(definition.skill_id, definition.skill_version) as any;
  assert.equal(pinned.definition_digest, definition.definition_digest);
  assert.equal((activeHost.pinBuiltInCreativeSkillDefinition(definition.skill_id, definition.skill_version) as any).object_hash, pinned.object_hash, "identical Definition pin must be idempotent");
  assert.throws(() => activeHost.pinBuiltInCreativeSkillDefinition("unknown-skill", 1), /unknown or untrusted/);
  const definitionRef = { object_id: definition.skill_id, object_version: definition.skill_version, digest: definition.definition_digest };
  const materialPackRef = { object_id: "pack-skill", object_version: 1, digest: pack.object_hash };
  const evaluationInput = { evaluation_id: "evaluation-skill", definition_ref: definitionRef, contract_ref: contractRef, material_pack_ref: materialPackRef, context_tags: ["personal-story", "reaction-evidenced"], parameter_values: { intensity: "moderate" }, evaluated_at: "2026-08-24T00:04:00.000Z" } as const;
  const timelineBefore = session.db.prepare("SELECT COUNT(*) AS count FROM timeline_versions").get().count;
  const evaluation = await activeHost.evaluateCreativeSkillKnowledge(evaluationInput) as any;
  assert.equal(evaluation.value.result, "applicable");
  assert.equal(evaluation.value.score, 1);
  assert.equal(JSON.stringify(evaluation.value).includes("command"), false);
  const retry = await activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "ignored-retry-id", evaluated_at: "2026-08-24T00:05:00.000Z" }) as any;
  assert.equal(retry.object_hash, evaluation.object_hash, "same exact context must reuse the immutable Evaluation");
  const conflicting = await activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "evaluation-conflict", context_tags: ["personal-story", "reaction-evidenced", "strict-chronology"] }) as any;
  assert.equal(conflicting.value.result, "conflicting");
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "bad-parameter", parameter_values: { unknown: true } }), /unknown parameter/);
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "malicious", commands: [{ type: "add_clip" }] } as any), /unknown input field|execution field is forbidden/);
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "forged-evaluator", evaluator_version: "certified-v999" } as any), /unknown input field/);
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "forged-policy", policy_version: "forged-policy" } as any), /unknown input field/);
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "forged-version", object_version: 999 } as any), /unknown input field/);
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "rebound-definition", definition_ref: { ...definitionRef, digest: digest("9") } }), /trusted catalog|unavailable or rebound/);
  const forgedPackValue = { ...pack.value, pack_id: "pack-forged-edge", input_fingerprint: digest("8"), contract_ref: { ...pack.value.contract_ref, object_id: "forged-contract", object_version: 999 } };
  const forgedPack = registerMaterialEvidencePack(session, projectId, forgedPackValue) as any;
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "forged-pack-edge", material_pack_ref: { object_id: forgedPackValue.pack_id, object_version: 1, digest: forgedPack.object_hash } }), /stale or rebound/);
  const inertExternalBase = { ...definition, skill_id: "external-shell-prose", reasoning_rules: [{ ...definition.reasoning_rules[0]!, recommendation: "/bin/sh -c id" }] };
  const inertExternal = { ...inertExternalBase, definition_digest: creativeSkillDefinitionDigest(inertExternalBase) };
  registerCreativeSkillDefinition(session, projectId, inertExternal);
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "external-catalog-denied", definition_ref: { object_id: inertExternal.skill_id, object_version: inertExternal.skill_version, digest: inertExternal.definition_digest } }), /trusted catalog/);
  assert.equal(session.db.prepare("SELECT COUNT(*) AS count FROM timeline_versions").get().count, timelineBefore);
  assert.equal(session.db.prepare("SELECT COUNT(*) AS count FROM object_refs WHERE object_type IN ('preset_application','preset_application_blocker')").get().count, 0);

  await chmod(immutableMediaPath, 0o666);
  await writeFile(immutableMediaPath, Buffer.alloc(immutableBytes.byteLength, 0x78));
  await utimes(immutableMediaPath, immutableFileTime, immutableFileTime);
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "stale-media", context_tags: ["personal-story"] }), /insufficient.*stale/);
  const stale = await activeHost.readSkillEvaluation("evaluation-skill", 1) as any;
  assert.equal(stale.lifecycle_status, "stale");
  assert.ok(stale.stale_reasons.includes("material_pack_changed"));
  const withdrawal = activeHost.withdrawCreativeSkillDefinition(definition.skill_id, definition.skill_version, "retired", "superseded by a reviewed catalog version") as any;
  assert.equal(withdrawal.availability, "retired");
  await assert.rejects(() => activeHost.evaluateCreativeSkillKnowledge({ ...evaluationInput, evaluation_id: "after-retirement" }), /retired or revoked/);
  assert.throws(() => activeHost.pinBuiltInCreativeSkillDefinition(definition.skill_id, definition.skill_version), /retired or revoked/);
  const withdrawnView = await activeHost.readSkillEvaluation("evaluation-skill", 1) as any;
  assert.ok(withdrawnView.stale_reasons.includes("definition_withdrawn"));
  await activeHost.close();
  host = undefined;

  reopened = new ProjectHostSession();
  await reopened.open(root);
  assert.equal((reopened.readCreativeSkillDefinition(definition.skill_id, 1) as any).digest, definition.definition_digest);
  const reopenedEvaluation = await reopened.readSkillEvaluation("evaluation-skill", 1) as any;
  assert.equal(reopenedEvaluation.digest, evaluation.object_hash);
  assert.equal(reopenedEvaluation.lifecycle_status, "stale");
  assert.ok((await reopened.listSkillEvaluations()).every((row: any) => row.lifecycle_status === "stale"));
  await reopened.close();
  reopened = undefined;
} finally {
  await reopened?.close().catch(() => undefined);
  await host?.close().catch(() => undefined);
  if (typeof global.gc === "function") global.gc();
  await new Promise((resolve) => setTimeout(resolve, 50));
  await rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });
}
console.log("creative skill Project Host pin, evaluation, staleness, reopen and zero-execution checks passed");
