import { strict as assert } from "node:assert";
import { execFile } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { promisify } from "node:util";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
const run = promisify(execFile); const root = await mkdtemp(resolve(tmpdir(), "ai-vlog-cli-")); const cli = resolve("apps/dev-cli/src/main.ts"); const media = resolve("tests/fixtures/generated/p0-vfr.mp4");
try {
  const created = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "create-project", root])).stdout); assert.equal(created.ok, true);
  const imported = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "import-media", root, media])).stdout); assert.equal(imported.ok, true); assert.match(imported.asset_id, /^asset:sha256:[0-9a-f]{64}$/);
  const timeline = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "create-timeline", root, "v1"])).stdout); assert.equal(timeline.ok, true); assert.equal(timeline.status.timeline, "v0");
  const command = { type: "add_clip", track_id: "v1", clip: { clip_id: "clip-cli", source: { asset_id: imported.asset_id, start_pts: "0n", end_pts: "10n", timescale: "30n" }, timeline_start: "0n", timeline_duration: "10n" } };
  const applied = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "apply-command", root, "0", JSON.stringify(command)])).stdout); assert.equal(applied.ok, true); assert.equal(applied.status.timeline, "v1");
  const conflict = await run(process.execPath, ["--import", "tsx", cli, "apply-command", root, "0", JSON.stringify(command)]).catch((error) => error); assert.notEqual(conflict.code, undefined); assert.match(String(conflict.stdout), /TIMELINE_COMMAND_FAILED/);
  const render = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "render-preview", root, media], { maxBuffer: 1024 * 1024 })).stdout); assert.equal(render.ok, true); assert.equal(render.status.qc, "passed");
  const qc = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "run-qc", resolve(root, "renders/master.mp4")])).stdout); assert.equal(qc.ok, true); assert.equal(qc.report.status, "passed");
  const verified = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "verify-project", root])).stdout); assert.equal(verified.ok, true); assert.equal(verified.integrity, "ok");
  const migrated = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "migrate-project", root])).stdout); assert.equal(migrated.ok, true); assert.equal(migrated.integrity, "ok"); assert.equal(migrated.schema_version, 27);
  const analysisRecords = [{ segment_id: "seg-cli", asset_id: imported.asset_id, start_pts: 0, end_pts: 12, text: "cli evidence" }];
  const analyzed = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "analyze", root, "asr", JSON.stringify(analysisRecords)])).stdout); assert.equal(analyzed.ok, true); assert.equal(analyzed.evidence_count, 1);
  const evidence = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "inspect-evidence", root, "asr:seg-cli"])).stdout); assert.equal(evidence.ok, true); assert.equal(evidence.evidence.object_id, "asr:seg-cli"); assert.equal("content" in evidence.evidence || "text" in evidence.evidence || "value" in evidence.evidence, false, "CLI must preserve the bounded Evidence query projection");
  const proposal = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "propose-story", root, JSON.stringify(["asr:seg-cli"])] )).stdout); assert.equal(proposal.ok, true); assert.equal(proposal.proposal.beats.length, 1);
  const plan = { schema_version: 1, plan_id: "plan-cli", proposal_id: proposal.proposal.proposal_id, approved_by: "cli-user", approved_at: "2026-07-30T00:00:00.000Z", beats: proposal.proposal.beats };
  const approved = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "approve-story", root, JSON.stringify(plan)])).stdout); assert.equal(approved.ok, true); assert.equal(approved.plan.plan_id, "plan-cli");
  const cut = { schema_version: 1, assembly_id: "assembly-cli", approved_plan_id: "plan-cli", clips: [{ clip_id: "clip-assembly", beat_id: proposal.proposal.beats[0].beat_id, evidence_ids: ["asr:seg-cli"], asset_id: imported.asset_id, start_pts: "0n", end_pts: "10n" }], status: "candidate" };
  const registered = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "register-assembly", root, JSON.stringify(cut)])).stdout); assert.equal(registered.ok, true); assert.equal(registered.cut.status, "validated");
  const compiled = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "compile-assembly", root, "assembly-cli", "v1", "1"])).stdout); assert.equal(compiled.ok, true); assert.equal(compiled.status.timeline, "v2");
  const patch = { schema_version: 1, patch_id: "patch-cli", base_version: 2, operations: [{ operation: "replace", clip_id: "clip-assembly", source_start_pts: "1n", source_end_pts: "9n" }] };
  const rough = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "apply-rough-cut", root, "v1", JSON.stringify(patch)])).stdout); assert.equal(rough.ok, true); assert.equal(rough.status.timeline, "v3");
  const roughConflict = await run(process.execPath, ["--import", "tsx", cli, "apply-rough-cut", root, "v1", JSON.stringify(patch)]).catch((error) => error); assert.match(String(roughConflict.stdout), /ROUGH_CUT_FAILED/);
  const issue = { schema_version: 1, issue_id: "issue-cli", category: "pacing", statement: "节奏需要收紧", target_clip_ids: ["clip-assembly"], status: "open" };
  const diagnosis = { schema_version: 1, diagnosis_id: "diagnosis-cli", feedback_text: "节奏需要调整", issue_ids: ["issue-cli"], status: "candidate" };
  const diagnosed = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "review-diagnosis", root, JSON.stringify(diagnosis), JSON.stringify([issue])])).stdout); assert.equal(diagnosed.ok, true);
  const compare = { schema_version: 1, compare_id: "compare-cli", left_version: 2, right_version: 3, selection: "right", reason: "节奏更好" };
  const compared = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "compare-review", root, JSON.stringify(compare)])).stdout); assert.equal(compared.ok, true);
  const reaction = { schema_version: 1, reaction_id: "reaction-cli", compare_id: "compare-cli", timeline_pts: "5n", reaction: "positive", source: "user" };
  const reacted = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "reaction-review", root, JSON.stringify(reaction)])).stdout); assert.equal(reacted.ok, true);
  const privacy = { schema_version: 1, entry_id: "privacy-cli", asset_id: imported.asset_id, classification: "public", action: "none", status: "pending" };
  const rights = { schema_version: 1, entry_id: "rights-cli", asset_id: imported.asset_id, license_id: "fixture-license", status: "pending" };
  assert.equal(JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "approve-privacy", root, JSON.stringify(privacy)])).stdout).ok, true);
  assert.equal(JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "approve-rights", root, JSON.stringify(rights)])).stdout).ok, true);
  const delivery = { schema_version: 1, delivery_id: "delivery-cli", timeline_version: 3, master_render_id: "master", gates: { qc: "passed", privacy: "not_required", rights: "passed", original_link: "verified" }, status: "blocked" };
  const delivered = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "create-delivery", root, JSON.stringify(delivery)])).stdout); assert.equal(delivered.ok, true); assert.equal(delivered.delivery.value.status, "ready");
  const profile = { container: "mp4", video_codec: "h264", audio_codec: "aac", width: 1920, height: 1080, fps: 30, audio_sample_rate: 48000 };
  assert.equal(JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "validate-export", root, "social_1080p", JSON.stringify(profile)])).stdout).ok, true);
  const registeredExport = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "register-export", root, "delivery-cli", "qc-1", "export-cli", resolve(root, "renders/master.mp4")])).stdout); assert.equal(registeredExport.ok, true);
  const inspected = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "inspect-project", root])).stdout); assert.equal(inspected.ok, true); assert.equal(inspected.manifest.project_format_version, 1);
} finally { await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); }
console.log("dev cli media flow passed");
