import { strict as assert } from "node:assert";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { promisify } from "node:util";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
const run = promisify(execFile); const root = await mkdtemp(resolve(tmpdir(), "ai-vlog-cli-")); const cli = resolve("apps/dev-cli/src/main.ts"); const media = resolve("tests/fixtures/generated/p0-vfr.mp4");
try {
  const created = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "create-project", root])).stdout); assert.equal(created.ok, true);
  const imported = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "import-media", root, media])).stdout); assert.equal(imported.ok, true); assert.match(imported.asset_id, /^asset:sha256:[0-9a-f]{64}$/);
  const timeline = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "create-timeline", root, "v1"])).stdout); assert.equal(timeline.ok, true); assert.equal(timeline.status.timeline, "v0");
  const command = { type: "add_clip", track_id: "v1", clip: { clip_id: "clip-cli", source: { asset_id: imported.asset_id, start_pts: "0n", end_pts: "10n", timescale: "30n" }, timeline_start: "0n", timeline_duration: "10n" } };
  const applied = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "apply-command", root, "0", JSON.stringify(command)])).stdout); assert.equal(applied.ok, true); assert.equal(applied.status.timeline, "v1");
  const conflict = await run(process.execPath, ["--import", "tsx", cli, "apply-command", root, "0", JSON.stringify(command)]).catch((error) => error); assert.notEqual(conflict.code, undefined); assert.match(String(conflict.stdout), /TIMELINE_COMMAND_FAILED/);
  const render = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "render-preview", root, media], { maxBuffer: 1024 * 1024 })).stdout); assert.equal(render.ok, true); assert.equal(render.status.qc, "passed");
  const qc = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "run-qc", resolve(root, "renders/master.mp4")])).stdout); assert.equal(qc.ok, true); assert.equal(qc.report.status, "passed");
  const verified = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "verify-project", root])).stdout); assert.equal(verified.ok, true); assert.equal(verified.integrity, "ok");
  const analysisRecords = [{ segment_id: "seg-cli", asset_id: imported.asset_id, start_pts: 0, end_pts: 12, text: "cli evidence" }];
  const analyzed = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "analyze", root, "asr", JSON.stringify(analysisRecords)])).stdout); assert.equal(analyzed.ok, true); assert.equal(analyzed.evidence_count, 1);
  const evidence = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "inspect-evidence", root, "asr:seg-cli"])).stdout); assert.equal(evidence.ok, true); assert.equal(evidence.evidence.object_id, "asr:seg-cli"); assert.equal("content" in evidence.evidence || "text" in evidence.evidence || "value" in evidence.evidence, false, "CLI must preserve the bounded Evidence query projection");
  for (const removed of ["migrate-project", "propose-story", "approve-story", "register-assembly", "compile-assembly", "review-diagnosis"]) { const rejected = await run(process.execPath, ["--import", "tsx", cli, removed, root]).catch((error) => error); assert.match(String(rejected.stdout), /UNKNOWN_COMMAND/, `${removed} must not remain a compatibility route`); }
  const source = await readFile(cli, "utf8"); assert.match(source, /register-assembly-v2/); assert.match(source, /execute-assembly-v2/);
  const patch = { schema_version: 1, patch_id: "patch-cli", base_version: 1, operations: [{ operation: "replace", clip_id: "clip-cli", source_start_pts: "1n", source_end_pts: "9n" }] };
  const rough = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "apply-rough-cut", root, "v1", JSON.stringify(patch)])).stdout); assert.equal(rough.ok, true); assert.equal(rough.status.timeline, "v2");
  const roughConflict = await run(process.execPath, ["--import", "tsx", cli, "apply-rough-cut", root, "v1", JSON.stringify(patch)]).catch((error) => error); assert.match(String(roughConflict.stdout), /ROUGH_CUT_FAILED/);
  const compare = { schema_version: 1, compare_id: "compare-cli", left_version: 1, right_version: 2, selection: "right", reason: "节奏更好" };
  const compared = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "compare-review", root, JSON.stringify(compare)])).stdout); assert.equal(compared.ok, true);
  const reaction = { schema_version: 1, reaction_id: "reaction-cli", compare_id: "compare-cli", timeline_pts: "5n", reaction: "positive", source: "user" };
  const reacted = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "reaction-review", root, JSON.stringify(reaction)])).stdout); assert.equal(reacted.ok, true);
  const privacy = { schema_version: 1, entry_id: "privacy-cli", asset_id: imported.asset_id, classification: "public", action: "none", status: "pending" };
  const rights = { schema_version: 1, entry_id: "rights-cli", asset_id: imported.asset_id, license_id: "fixture-license", status: "pending" };
  assert.equal(JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "approve-privacy", root, JSON.stringify(privacy)])).stdout).ok, true);
  assert.equal(JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "approve-rights", root, JSON.stringify(rights)])).stdout).ok, true);
  const delivery = { schema_version: 1, delivery_id: "delivery-cli", timeline_version: 2, master_render_id: "master", gates: { qc: "passed", privacy: "not_required", rights: "passed", original_link: "verified" }, status: "blocked" };
  const delivered = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "create-delivery", root, JSON.stringify(delivery)])).stdout); assert.equal(delivered.ok, true); assert.equal(delivered.delivery.value.status, "ready");
  const profile = { container: "mp4", video_codec: "h264", audio_codec: "aac", width: 1920, height: 1080, fps: 30, audio_sample_rate: 48000 };
  assert.equal(JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "validate-export", root, "social_1080p", JSON.stringify(profile)])).stdout).ok, true);
  const registeredExport = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "register-export", root, "delivery-cli", "qc-1", "export-cli", resolve(root, "renders/master.mp4")])).stdout); assert.equal(registeredExport.ok, true);
  const inspected = JSON.parse((await run(process.execPath, ["--import", "tsx", cli, "inspect-project", root])).stdout); assert.equal(inspected.ok, true); assert.equal(inspected.manifest.project_format_version, 2);
} finally { await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); }
console.log("dev cli media flow passed");
