import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { access, copyFile, mkdir, mkdtemp, readFile, rm, stat, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { promisify } from "node:util";
import { ProjectHostSession } from "../../packages/platform/project-host/src/public.js";
import { builtInCreativeSkillDefinitions, builtInDurationBlueprints, type StoryBeatCandidate } from "../../packages/core/editorial-core/src/public.js";
import { listFeedbackDiagnosisEdges, listStage2PermissionDecisions, openProject, putObjectAndRegister, readFeedbackDiagnosis, readIntelligenceEditExecution, registerAssetLocation, registerMediaAsset } from "../../packages/platform/project-storage/src/public.js";
import type { AssetId } from "../../packages/core/media-identity/src/public.js";
import { permissionRefKey, type Stage2PermissionTypedRef } from "../../packages/features/permission-enforcement/src/public.js";
import { createStage2HumanReview } from "./stage2-human-review-helper.js";

const fixed = (character: string) => character.repeat(64);
const run = promisify(execFile), realMode = process.env.AVE_PIPELINE_REAL_MODE === "1";
const configuredRoot = process.env.AVE_INTELLIGENCE_PIPELINE_REVIEW_ROOT;
if (realMode && !configuredRoot) throw new Error("INTELLIGENCE_PIPELINE_REVIEW_ROOT_REQUIRED");
if (realMode) { let exists = true; try { await access(configuredRoot!); } catch { exists = false; } assert.equal(exists, false, "intelligence pipeline review root must be fresh"); }
const root = realMode ? configuredRoot! : await mkdtemp(resolve(tmpdir(), "ave-intelligence-pipeline-host-"));
const human = createStage2HumanReview("pipeline-reviewer", "2026-08-24T03:00:00Z");
let host: ProjectHostSession | undefined, reopened: ProjectHostSession | undefined;

try {
  host = new ProjectHostSession(human.options); await host.create(root); host.initializeTimeline([{ track_id: "v1", kind: "video", clips: [] }]);
  const session = (host as any).session, projectId = session.manifest.project_id as string;
  const draft = host.upgradeCreativeContractV1({ schema_version: 1, contract_id: "contract-pipeline", status: "review", requirements: [{ requirement_id: "req-goal", kind: "hard", statement: "Show the goal" }, { requirement_id: "req-ending", kind: "hard", statement: "Show the ending" }] }, { project_id: projectId, creator_goal: "Build an evidence-led first cut", audience: ["friends"], platforms: ["youtube"], target_duration: { schema_version: 1, value: 60, timescale: 1 }, voice_and_identity: { desired_traits: ["warm"], forbidden_misrepresentation: ["invented event"] }, privacy_policy_ref: { object_id: "privacy", object_version: 1, digest: fixed("a") }, rights_policy_ref: { object_id: "rights", object_version: 1, digest: fixed("b") }, approval_policy: { mode: "explicit_user", actor_kind: "user" }, protected_refs: ["clip:user-lock"], allowed_transformations: ["trim", "reorder"], forbidden_outcomes: ["fabrication"], created_at: "2026-08-24T02:50:00Z", provenance: { producer: "adapter", source_id: "pipeline-test", source_version: "1", policy_version: "knowledge-v1", input_refs: [], unresolved_assumptions: [] } });
  const review = host.registerCreativeContractDraft({ ...draft, status: "review" }) as any;
  const approvedContract = host.approveCreativeContract(await human.approveContract(host, "approval-pipeline-contract", draft.contract_id, 1, review.object_hash)) as any;
  const contractRef = { object_id: draft.contract_id, object_version: 2, digest: approvedContract.object_hash };
  let mediaPath = resolve(root, "originals", "pipeline-evidence.bin"), bytes = Buffer.from("approved pipeline evidence with deterministic source identity"), sourceTimescale = 48000, sourceDuration = 60 * 48000;
  if (realMode) { const manifestPath = process.env.AVE_REAL_MEDIA_MANIFEST; if (!manifestPath) throw new Error("INTELLIGENCE_PIPELINE_REAL_MEDIA_MANIFEST_REQUIRED"); const manifest = JSON.parse((await readFile(manifestPath)).toString("utf8")) as any; if (manifest.schema_version !== 1 || !manifest.originals?.[0]?.path) throw new Error("INTELLIGENCE_PIPELINE_REAL_MEDIA_MANIFEST_INVALID"); mediaPath = manifest.originals[0].path; bytes = await readFile(mediaPath); const probe = JSON.parse(String((await run("ffprobe", ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=time_base,duration_ts", "-of", "json", mediaPath])).stdout)); const video = probe.streams?.[0], match = video?.time_base?.match(/^1\/(\d+)$/); if (!match || !video.duration_ts) throw new Error("INTELLIGENCE_PIPELINE_REAL_VIDEO_TIMING_REQUIRED"); sourceTimescale = Number(match[1]); sourceDuration = Number(video.duration_ts); if (!Number.isSafeInteger(sourceTimescale) || !Number.isSafeInteger(sourceDuration) || sourceDuration < sourceTimescale * 60) throw new Error("INTELLIGENCE_PIPELINE_REAL_VIDEO_TOO_SHORT"); }
  else { await writeFile(mediaPath, bytes); const normalizedTime = new Date(Math.floor(Date.now() / 1000) * 1000); await utimes(mediaPath, normalizedTime, normalizedTime); }
  const mediaStat = await stat(mediaPath), mediaDigest = createHash("sha256").update(bytes).digest("hex"), asset = `asset:sha256:${mediaDigest}` as AssetId;
  registerMediaAsset(session, projectId, { asset_id: asset, algorithm: "sha256", digest: mediaDigest, byte_length: bytes.length, stream_facts: { duration_pts: sourceDuration, timescale: sourceTimescale } });
  registerAssetLocation(session, projectId, { asset_location_id: "pipeline-original", asset_id: asset, location_type: "original", location_ref: mediaPath, verified_at: "2026-08-24T02:51:00Z", metadata: { verification_status: "verified", fingerprint: { algorithm: "sha256", digest: mediaDigest, byte_length: bytes.length }, file_stat: { size: mediaStat.size, mtime_ms: mediaStat.mtimeMs }, ...(!realMode ? { probe: { streams: [{ codec_type: "video", width: 360, height: 640 }] } } : {}) } });
  await host.recordMaterialPermission(await human.materialPermission(host, "approval-pipeline-material", { contract_ref: contractRef, asset_id: asset, asset_location_id: "pipeline-original", location_ref: mediaPath, verified_at: "2026-08-24T02:51:00Z", permission_state: "authorized", policy_ref: draft.rights_policy_ref }));
  const plannedBeatSeconds = [8, 8, 8, 9, 9, 9, 9] as const, evidenceIds = plannedBeatSeconds.map((_, index) => `asr:pipeline:${index}`);
  let evidenceStartPts = 0;
  for (const [index, evidenceId] of evidenceIds.entries()) { const startPts = evidenceStartPts, endPts = startPts + plannedBeatSeconds[index]! * sourceTimescale; evidenceStartPts = endPts; const evidence = { evidence_id: evidenceId, analysis_type: "asr", asset_id: asset, start_pts: startPts, end_pts: endPts, timescale: sourceTimescale, evidence_version: 1, review_status: "candidate", text: `approved pipeline evidence ${index}` }; host.registerEvidence(evidence); await human.approveEvidence(host, `approval-pipeline-evidence-${index}`, evidence); }
  const overlappingEvidenceIds = ["asr:pipeline:overlap-a", "asr:pipeline:overlap-b"];
  for (const [index, evidenceId] of overlappingEvidenceIds.entries()) { const evidence = { evidence_id: evidenceId, analysis_type: "asr", asset_id: asset, start_pts: 0, end_pts: 4 * sourceTimescale, timescale: sourceTimescale, evidence_version: 1, review_status: "candidate", text: `approved overlapping pipeline evidence ${index}` }; host.registerEvidence(evidence); await human.approveEvidence(host, `approval-pipeline-overlap-evidence-${index}`, evidence); }
  const pack = await host.assembleMaterialEvidencePack({ pack_id: "pack-pipeline", contract_ref: contractRef, evidence_ids: [...evidenceIds, ...overlappingEvidenceIds], coverage_matrix: { schema_version: 1, matrix_id: "coverage-pipeline", rows: [{ requirement_id: "req-goal", evidence_ids: [...evidenceIds.slice(0, 4), ...overlappingEvidenceIds], status: "covered" }, { requirement_id: "req-ending", evidence_ids: evidenceIds.slice(4), status: "covered" }] }, expected_media_verified_at: { [asset]: "2026-08-24T02:51:00Z" }, policy_version: "knowledge-v1", timeline_version: 0, created_at: "2026-08-24T02:52:00Z" }) as any;
  const packRef = { object_id: pack.value.pack_id, object_version: 1, digest: pack.object_hash };
  const definition = builtInCreativeSkillDefinitions.find((candidate) => candidate.status === "published")!; host.pinBuiltInCreativeSkillDefinition(definition.skill_id, definition.skill_version);
  const evaluation = await host.evaluateCreativeSkillKnowledge({ evaluation_id: "evaluation-pipeline", definition_ref: { object_id: definition.skill_id, object_version: definition.skill_version, digest: definition.definition_digest }, contract_ref: contractRef, material_pack_ref: packRef, context_tags: ["personal-story", "reaction-evidenced"], parameter_values: { intensity: "moderate" }, evaluated_at: "2026-08-24T02:53:00Z" }) as any;
  const evaluationRef = { object_id: evaluation.value.evaluation_id, object_version: 1, digest: evaluation.object_hash };
  const blueprint = builtInDurationBlueprints.find((candidate) => candidate.duration_class === "60s")!; host.pinBuiltInDurationBlueprint(blueprint.blueprint_id, 1);
  const feasibility = await host.evaluateDurationBlueprint({ feasibility_id: "duration-pipeline", blueprint_ref: { object_id: blueprint.blueprint_id, object_version: 1, digest: blueprint.definition_digest }, contract_ref: contractRef, material_pack_ref: packRef, evaluated_at: "2026-08-24T02:54:00Z" }) as any;
  const durationRef = { object_id: feasibility.value.feasibility_id, object_version: 1, digest: feasibility.object_hash };
  const directionCandidate = await host.createStoryDirection({ direction_id: "direction-pipeline", title: "Goal and arrival", thesis: "The detour creates the memory", contract_ref: contractRef, material_pack_ref: packRef, skill_evaluation_refs: [evaluationRef], duration_feasibility_ref: durationRef, expected_benefits: ["ending answers opening"], risks: [], alternatives: [], confidence: { score: 0.9, basis: ["approved evidence"] }, created_at: "2026-08-24T02:55:00Z" }) as any;
  const directionAlternative = await host.createStoryDirection({ direction_id: "direction-pipeline-alt", title: "Chronological route", thesis: "The trip unfolds in order", contract_ref: contractRef, material_pack_ref: packRef, skill_evaluation_refs: [evaluationRef], duration_feasibility_ref: durationRef, expected_benefits: ["simple chronology"], risks: ["weaker turn"], alternatives: [], confidence: { score: 0.7, basis: ["approved evidence"] }, created_at: "2026-08-24T02:55:00Z" }) as any;
  const directionSubject: Stage2PermissionTypedRef = { object_type: "direction_card", object_id: directionCandidate.value.direction_id, object_version: 1, digest: directionCandidate.object_hash };
  const directionContexts: Stage2PermissionTypedRef[] = [{ object_type: "creative_contract", ...contractRef }, { object_type: "material_evidence_pack", ...packRef }, { object_type: "duration_feasibility", ...durationRef }];
  const directionEffect = { direction_ids: [directionCandidate.value.direction_id, directionAlternative.value.direction_id].sort(), candidate_refs: [{ object_id: directionCandidate.value.direction_id, object_version: 1, digest: directionCandidate.object_hash }, { object_id: directionAlternative.value.direction_id, object_version: 1, digest: directionAlternative.object_hash }].sort((left, right) => left.object_id.localeCompare(right.object_id)), selected_direction_id: directionCandidate.value.direction_id, decision_id: "decision-direction-pipeline", reason: "select exact direction", review_digest: directionCandidate.object_hash };
  await human.issue(host, "approval-pipeline-direction", "direction_card.select", directionSubject, directionContexts, ["alternatives", "reason", "review_digest", "selected_ref"], [permissionRefKey(directionSubject)], directionEffect, "select exact direction");
  const selectedDirection = await host.selectStoryDirection([directionAlternative.value.direction_id, directionCandidate.value.direction_id], { decision_id: "decision-direction-pipeline", selected_direction_id: directionCandidate.value.direction_id, approval_id: "approval-pipeline-direction", reason: "select exact direction", review_digest: directionCandidate.object_hash }) as any;
  const directionRef = { object_id: selectedDirection.direction.value.direction_id, object_version: 2, digest: selectedDirection.direction.object_hash }, evidenceRef = (index: number) => ({ object_id: pack.value.evidence_refs[index].evidence_id, object_version: pack.value.evidence_refs[index].evidence_version, digest: pack.value.evidence_refs[index].content_digest });
  const beat = (id: string, role: string, seconds: number, index: number, requirement: string, entry: string, exit: string, confidence = 0.9): StoryBeatCandidate => ({ beat_id: id, role, purpose: `${role} purpose`, target_duration: { schema_version: 1, value: seconds, timescale: 1 }, evidence_refs: [evidenceRef(index)], alternative_evidence_refs: [], coverage_requirement_ids: [requirement], entry_state: entry, exit_state: exit, desired_emotion: role === "ending" ? "satisfaction" : "curiosity", continuity_constraints: ["preserve state"], confidence: { score: confidence, basis: ["approved evidence"] }, reason: "evidence supports beat", risks: [], unresolved_assumptions: [] });
  assert.equal(feasibility.value.planned_beat_count, plannedBeatSeconds.length); assert.equal(plannedBeatSeconds.reduce((sum, seconds) => sum + seconds, 0), feasibility.value.target_duration.value);
  const storyBeats = (suffix = "", confidence = 0.9) => plannedBeatSeconds.map((seconds, index) => { const ending = index === plannedBeatSeconds.length - 1, goal = index < 4; return beat(`${ending ? "ending" : index === 0 ? "hook" : `development-${index}`}${suffix}`, ending ? "ending" : index === 0 ? "hook" : "development", seconds, index, goal ? "req-goal" : "req-ending", index === 0 ? "unknown" : `state-${index}`, ending ? "resolved" : `state-${index + 1}`, confidence); });
  const proposal = await host.proposeStoryV2({ proposal_id: "proposal-pipeline", direction_ref: directionRef, contract_ref: contractRef, material_pack_ref: packRef, skill_evaluation_refs: [evaluationRef], duration_feasibility_ref: durationRef, thesis: selectedDirection.direction.value.thesis, audience_promise: "see goal and resolution", beats: storyBeats(), risks: [], alternatives: [], created_at: "2026-08-24T02:56:00Z" }) as any;
  const proposalAlternative = await host.proposeStoryV2({ proposal_id: "proposal-pipeline-alt", direction_ref: directionRef, contract_ref: contractRef, material_pack_ref: packRef, skill_evaluation_refs: [evaluationRef], duration_feasibility_ref: durationRef, thesis: "chronological alternative", audience_promise: "follow the route", beats: storyBeats("-alt", 0.8), risks: ["weaker turn"], alternatives: [], created_at: "2026-08-24T02:56:00Z" }) as any;
  const storySubject: Stage2PermissionTypedRef = { object_type: "story_proposal_v2", object_id: proposal.value.proposal_id, object_version: 1, digest: proposal.object_hash };
  const storyContexts: Stage2PermissionTypedRef[] = [{ object_type: "creative_contract", ...contractRef }, { object_type: "direction_card", ...directionRef }, { object_type: "material_evidence_pack", ...packRef }, { object_type: "duration_feasibility", ...durationRef }];
  const storyEffect = { proposal_ids: [proposal.value.proposal_id, proposalAlternative.value.proposal_id].sort(), candidate_refs: [{ object_id: proposal.value.proposal_id, object_version: 1, digest: proposal.object_hash }, { object_id: proposalAlternative.value.proposal_id, object_version: 1, digest: proposalAlternative.object_hash }].sort((left, right) => left.object_id.localeCompare(right.object_id)), selected_proposal_id: proposal.value.proposal_id, decision_id: "decision-story-pipeline", plan_id: "plan-pipeline", reason: "approve exact story", review_digest: proposal.object_hash };
  await human.issue(host, "approval-pipeline-story", "story_plan.approve", storySubject, storyContexts, ["alternatives", "reason", "review_digest", "selected_ref"], [permissionRefKey(storySubject)], storyEffect, "approve exact story");
  const approvedStory = await host.approveStoryCandidates([proposalAlternative.value.proposal_id, proposal.value.proposal_id], { decision_id: "decision-story-pipeline", plan_id: "plan-pipeline", selected_proposal_id: proposal.value.proposal_id, approval_id: "approval-pipeline-story", reason: "approve exact story", review_digest: proposal.object_hash }) as any;
  const exactEvidenceRef = (evidenceId: string) => { const reference = pack.value.evidence_refs.find((candidate: any) => candidate.evidence_id === evidenceId); assert.ok(reference); return { object_id: reference.evidence_id, object_version: reference.evidence_version, digest: reference.content_digest }; }, overlapRefs = overlappingEvidenceIds.map(exactEvidenceRef), overlappingStoryBeats = (suffix: string, confidence: number) => storyBeats(suffix, confidence).map((item, index) => index === 0 ? { ...item, evidence_refs: overlapRefs } : item);
  const overlapProposal = await host.proposeStoryV2({ proposal_id: "proposal-pipeline-overlap", direction_ref: directionRef, contract_ref: contractRef, material_pack_ref: packRef, skill_evaluation_refs: [evaluationRef], duration_feasibility_ref: durationRef, thesis: selectedDirection.direction.value.thesis, audience_promise: "prove duplicate source ranges cannot become an implicit loop", beats: overlappingStoryBeats("-overlap", 0.86), risks: [], alternatives: [], created_at: "2026-08-24T02:56:10Z" }) as any;
  const overlapProposalAlternative = await host.proposeStoryV2({ proposal_id: "proposal-pipeline-overlap-alt", direction_ref: directionRef, contract_ref: contractRef, material_pack_ref: packRef, skill_evaluation_refs: [evaluationRef], duration_feasibility_ref: durationRef, thesis: "overlap test alternative", audience_promise: "retain an exact comparison candidate", beats: overlappingStoryBeats("-overlap-alt", 0.75), risks: [], alternatives: [], created_at: "2026-08-24T02:56:10Z" }) as any;
  const overlapStorySubject: Stage2PermissionTypedRef = { object_type: "story_proposal_v2", object_id: overlapProposal.value.proposal_id, object_version: 1, digest: overlapProposal.object_hash }, overlapStoryEffect = { proposal_ids: [overlapProposal.value.proposal_id, overlapProposalAlternative.value.proposal_id].sort(), candidate_refs: [{ object_id: overlapProposal.value.proposal_id, object_version: 1, digest: overlapProposal.object_hash }, { object_id: overlapProposalAlternative.value.proposal_id, object_version: 1, digest: overlapProposalAlternative.object_hash }].sort((left, right) => left.object_id.localeCompare(right.object_id)), selected_proposal_id: overlapProposal.value.proposal_id, decision_id: "decision-story-pipeline-overlap", plan_id: "plan-pipeline-overlap", reason: "approve the exact overlap fixture for compiler rejection", review_digest: overlapProposal.object_hash };
  await human.issue(host, "approval-pipeline-story-overlap", "story_plan.approve", overlapStorySubject, storyContexts, ["alternatives", "reason", "review_digest", "selected_ref"], [permissionRefKey(overlapStorySubject)], overlapStoryEffect, overlapStoryEffect.reason);
  const approvedOverlapStory = await host.approveStoryCandidates([overlapProposalAlternative.value.proposal_id, overlapProposal.value.proposal_id], { decision_id: overlapStoryEffect.decision_id, plan_id: overlapStoryEffect.plan_id, selected_proposal_id: overlapStoryEffect.selected_proposal_id, approval_id: "approval-pipeline-story-overlap", reason: overlapStoryEffect.reason, review_digest: overlapProposal.object_hash }) as any;

  const approveIntent = async (intent: any, approvalId: string, reason: string) => {
    const subject: Stage2PermissionTypedRef = { object_type: "editorial_edit_intent", object_id: intent.value.intent_id, object_version: intent.value.object_version, digest: intent.object_hash };
    const contexts: Stage2PermissionTypedRef[] = [{ object_type: "creative_contract", ...intent.value.contract_ref }, { object_type: "approved_story_plan_v2", ...intent.value.approved_story_ref }, ...intent.value.decision_refs.map((reference: any) => ({ object_type: "decision_record" as const, ...reference })), { object_type: "capability_snapshot", ...intent.value.capability_snapshot_ref }];
    if (intent.value.feedback_diagnosis_ref) { const diagnosis = readFeedbackDiagnosis(session, projectId, intent.value.feedback_diagnosis_ref.object_id, intent.value.feedback_diagnosis_ref.object_version) as any; contexts.push({ object_type: "feedback_diagnosis", ...intent.value.feedback_diagnosis_ref }, { object_type: "intelligence_edit_execution", ...diagnosis.value.base_execution_ref }); }
    const scope = [...new Set<string>(intent.value.operations.flatMap((operation: any) => operation.target_refs))].sort();
    const effect = { intent_ref: subject, expected_effects: intent.value.operations.map((operation: any) => ({ operation_id: operation.operation_id, expected_effect: operation.expected_effect, target_refs: operation.target_refs })), reason, review_digest: intent.object_hash };
    await human.issue(host!, approvalId, "editorial_edit_intent.approve", subject, contexts, ["expected_effects", "reason", "review_digest"], scope, effect, reason);
    return host!.approveEditorialIntent({ intent_id: intent.value.intent_id, approval_id: approvalId, reason, review_digest: intent.object_hash }) as Promise<any>;
  };
  const snapshot = () => ({ timelines: session.db.prepare("SELECT COUNT(*) count FROM timeline_versions").get().count, commands: session.db.prepare("SELECT COUNT(*) count FROM timeline_commands").get().count, events: session.db.prepare("SELECT COUNT(*) count FROM project_events").get().count, refs: session.db.prepare("SELECT COUNT(*) count FROM object_refs").get().count, permissions: session.db.prepare("SELECT COUNT(*) count FROM permission_decisions").get().count, renderBundles: session.db.prepare("SELECT COUNT(*) count FROM render_bundles").get().count, renderResults: session.db.prepare("SELECT COUNT(*) count FROM render_results").get().count });
  const overlapOperations = (approvedOverlapStory.plan.value.beats as any[]).flatMap((item, beatIndex) => item.evidence_refs.map((reference: any, evidenceIndex: number) => ({ operation_id: `select-overlap-${beatIndex}-${evidenceIndex}`, kind: "select_evidence" as const, target_refs: [`beat:${item.beat_id}`, `evidence:${reference.object_id}`], parameter_values: { priority: beatIndex + evidenceIndex + 1 }, expected_effect: `select exact overlap fixture ${reference.object_id}`, required_capabilities: ["semantic-evidence-selection"], unsupported_policy: "block" as const })));
  const overlapIntent = await host.generateEditorialIntent({ plan_id: approvedOverlapStory.plan.value.plan_id, decision_ids: [approvedOverlapStory.decision.value.decision_id], capability_snapshot_id: "capabilities-pipeline-overlap", intent_id: "intent-pipeline-overlap", operations: overlapOperations, preconditions: ["timeline remains current"], reason: "prove overlapping source ranges fail before execution review", alternatives: [], risks: [], confidence: { score: 1, basis: ["controlled overlap fixture"] }, actor: { actor_id: "project-host", actor_kind: "policy" }, created_at: "2026-08-24T02:56:20Z" }) as any;
  const overlapIntentApproval = await approveIntent(overlapIntent, "approval-pipeline-intent-overlap", "retain overlap proposal only for compiler zero-write coverage"), beforeOverlapPrepare = snapshot();
  await assert.rejects(() => host!.prepareEditorialIntentExecution({ execution_id: "execution-pipeline-overlap", intent_id: overlapIntent.value.intent_id, proposal_approval_decision_id: overlapIntentApproval.value.decision_id }), /SEMANTIC_EVIDENCE_SOURCE_OVERLAP/); assert.deepEqual(snapshot(), beforeOverlapPrepare, "distinct Evidence IDs over the same source range must fail before execution, Timeline or Permission persistence");
  const approvedBeats = approvedStory.plan.value.beats as any[]; assert.deepEqual(approvedBeats.map((item) => item.target_duration.value), [...plannedBeatSeconds]); assert.deepEqual(approvedBeats.map((item) => item.evidence_refs[0].object_id), evidenceIds);
  const intentOperations = approvedBeats.map((item, index) => ({ operation_id: `select-${item.beat_id}`, kind: "select_evidence" as const, target_refs: [`beat:${item.beat_id}`, `evidence:${item.evidence_refs[0].object_id}`], parameter_values: { priority: index + 1 }, expected_effect: `place approved ${item.beat_id} evidence`, required_capabilities: ["semantic-evidence-selection"], unsupported_policy: "block" as const }));
  const unsupportedIntentCases = [
    { suffix: "range", operation: { ...intentOperations[0]!, range: { start: { schema_version: 1 as const, value: 0, timescale: 1 }, end: { schema_version: 1 as const, value: 1, timescale: 1 } } }, error: /SEMANTIC_OPERATION_RANGE_UNSUPPORTED/ },
    { suffix: "preserve-audio", operation: { ...intentOperations[0]!, parameter_values: { ...intentOperations[0]!.parameter_values, preserve_audio: false } }, error: /SEMANTIC_OPERATION_PARAMETER_UNSUPPORTED:preserve_audio/ },
  ] as const;
  for (const [index, unsupportedCase] of unsupportedIntentCases.entries()) {
    const unsupportedIntent = await host.generateEditorialIntent({ plan_id: approvedStory.plan.value.plan_id, decision_ids: [approvedStory.decision.value.decision_id], capability_snapshot_id: `capabilities-pipeline-${unsupportedCase.suffix}`, intent_id: `intent-pipeline-${unsupportedCase.suffix}`, operations: [unsupportedCase.operation, ...intentOperations.slice(1)], preconditions: ["timeline remains current"], reason: `prove ${unsupportedCase.suffix} fails closed after persistence`, alternatives: [], risks: [], confidence: { score: 1, basis: ["controlled unsupported semantic fixture"] }, actor: { actor_id: "project-host", actor_kind: "policy" }, created_at: `2026-08-24T02:56:${24 + index}Z` }) as any;
    const unsupportedApproval = await approveIntent(unsupportedIntent, `approval-pipeline-intent-${unsupportedCase.suffix}`, `retain ${unsupportedCase.suffix} proposal only for compiler zero-write coverage`), beforeUnsupportedPrepare = snapshot();
    await assert.rejects(() => host!.prepareEditorialIntentExecution({ execution_id: `execution-pipeline-${unsupportedCase.suffix}`, intent_id: unsupportedIntent.value.intent_id, proposal_approval_decision_id: unsupportedApproval.value.decision_id }), unsupportedCase.error);
    assert.deepEqual(snapshot(), beforeUnsupportedPrepare, `${unsupportedCase.suffix} must fail before execution, Timeline or Permission persistence`);
  }
  const partialIntent = await host.generateEditorialIntent({ plan_id: approvedStory.plan.value.plan_id, decision_ids: [approvedStory.decision.value.decision_id], capability_snapshot_id: "capabilities-pipeline-partial", intent_id: "intent-pipeline-partial", operations: intentOperations.slice(0, 1), preconditions: ["timeline remains current"], reason: "prove incomplete Story coverage fails before execution review", alternatives: [], risks: [], confidence: { score: 0.5, basis: ["deliberately incomplete fixture"] }, actor: { actor_id: "project-host", actor_kind: "policy" }, created_at: "2026-08-24T02:56:30Z" }) as any;
  const partialApproval = await approveIntent(partialIntent, "approval-pipeline-intent-partial", "approve incomplete proposal only for compiler zero-write coverage"), beforePartialPrepare = snapshot();
  await assert.rejects(() => host!.prepareEditorialIntentExecution({ execution_id: "execution-pipeline-partial", intent_id: partialIntent.value.intent_id, proposal_approval_decision_id: partialApproval.value.decision_id }), /SEMANTIC_STORY_BEAT_UNCOVERED/); assert.deepEqual(snapshot(), beforePartialPrepare, "incomplete approved Story coverage must fail before execution review persistence");
  const intent = await host.generateEditorialIntent({ plan_id: approvedStory.plan.value.plan_id, decision_ids: [approvedStory.decision.value.decision_id], capability_snapshot_id: "capabilities-pipeline", intent_id: "intent-pipeline", operations: intentOperations, preconditions: ["timeline remains current"], reason: "compile exact approved first cut", alternatives: [], risks: [], confidence: { score: 0.95, basis: ["approved evidence"] }, actor: { actor_id: "project-host", actor_kind: "policy" }, created_at: "2026-08-24T02:57:00Z" }) as any;
  const proposalApproval = await approveIntent(intent, "approval-pipeline-intent", "retain exact semantic proposal");
  const identity = { execution_id: "execution-pipeline", intent_id: intent.value.intent_id, proposal_approval_decision_id: proposalApproval.value.decision_id };
  const executionReview = await host.prepareEditorialIntentExecution(identity);
  assert.equal(executionReview.base_timeline_version, 0); assert.equal(executionReview.expected_final_timeline_version, 1); assert.match(executionReview.effect_digest, /^[0-9a-f]{64}$/);
  const beforeUnauthorized = snapshot(); await assert.rejects(() => host!.executeApprovedEditorialIntent({ ...identity, execution_approval_id: "missing-execution-approval", reason: "execute reviewed first cut" }), /APPROVAL_RECORD_UNAVAILABLE/); assert.deepEqual(snapshot(), beforeUnauthorized, "missing execution approval must write nothing");
  await human.issueDigest(host, "approval-pipeline-execution", "editorial_edit_intent.execute", executionReview.subject_ref, executionReview.context_refs, executionReview.requested_data_fields, executionReview.affected_scope, executionReview.effect_digest, "execute reviewed first cut");
  const conflictRefId = `${projectId}:edit-ir:execute:${intent.value.intent_id}`; await putObjectAndRegister(session, projectId, Buffer.from("forced edit IR object id conflict"), { object_ref_id: conflictRefId, object_type: "fault_fixture", relation_key: "fault" });
  const beforeFault = snapshot(); await assert.rejects(() => host!.executeApprovedEditorialIntent({ ...identity, execution_approval_id: "approval-pipeline-execution", reason: "execute reviewed first cut" }), /atomic artifact id conflict/); assert.deepEqual(snapshot(), beforeFault, "storage conflict must roll back execution permission and Timeline writes");
  session.db.prepare("DELETE FROM object_refs WHERE object_ref_id = ?").run(conflictRefId);
  const executed = await host.executeApprovedEditorialIntent({ ...identity, execution_approval_id: "approval-pipeline-execution", reason: "execute reviewed first cut" }) as any;
  assert.equal(executed.status, "committed"); assert.equal(executed.base_timeline_version, 0); assert.equal(executed.final_timeline_version, 1); assert.equal(executed.semantic_graph_hash, executionReview.semantic_graph_hash);
  const timeline = host.readTimelineSnapshot() as any; assert.equal(timeline.version, 1); assert.equal(timeline.tracks[0].clips.length, plannedBeatSeconds.length); assert.deepEqual(timeline.tracks[0].clips.map((clip: any) => clip.semantic_sidecar.evidence_refs[0]), evidenceIds); assert.deepEqual(timeline.tracks[0].clips.map((clip: any) => BigInt(clip.timeline_duration)), plannedBeatSeconds.map((seconds) => BigInt(seconds * sourceTimescale))); assert.equal(timeline.tracks[0].clips.reduce((sum: bigint, clip: any) => sum + BigInt(clip.timeline_duration), 0n), 60n * BigInt(sourceTimescale));
  assert.equal((readIntelligenceEditExecution(session, projectId, identity.execution_id) as any).value.commit_plan_hash, executed.commit_plan_hash);
  assert.ok((listStage2PermissionDecisions(session, projectId) as any[]).some((row) => row.value.action === "editorial_edit_intent.execute"));
  const beforeRetry = snapshot(), retry = await host.executeApprovedEditorialIntent({ ...identity, execution_approval_id: "approval-pipeline-execution", reason: "execute reviewed first cut" }) as any; assert.deepEqual(retry, executed); assert.deepEqual(snapshot(), beforeRetry, "identical retry must be read-only");
  await assert.rejects(() => host!.executeApprovedEditorialIntent({ ...identity, intent_id: "different-intent", execution_approval_id: "approval-pipeline-execution", reason: "execute reviewed first cut" }), /SEMANTIC_EXECUTION_ID_CONFLICT/); assert.deepEqual(snapshot(), beforeRetry, "conflicting retry must write nothing");

  const firstCutTimeline = host.readTimelineSnapshot() as any, firstCutClip = firstCutTimeline.tracks[0].clips[0], trimAmount = Math.max(1, realMode ? Number(firstCutClip.source.timescale) : Math.floor(Number(firstCutClip.source.timescale) / 4)), proposedSource = { asset_id: firstCutClip.source.asset_id, start: { schema_version: 1 as const, value: Number(firstCutClip.source.start_pts), timescale: Number(firstCutClip.source.timescale) }, end: { schema_version: 1 as const, value: Number(firstCutClip.source.end_pts) - trimAmount, timescale: Number(firstCutClip.source.timescale) } };
  const rejectedRevision = await host.createFeedbackRevision({ diagnosis_id: "diagnosis-pipeline-reject", intent_id: "intent-pipeline-reject", base_execution_id: identity.execution_id, feedback_text: "先不要采用这版收紧", target: { track_id: "v1", clip_id: firstCutClip.clip_id, proposed_source: proposedSource }, reason: "exercise exact rejection with zero Timeline mutation", alternatives: ["retain accepted first cut"], confidence: { score: 1, basis: ["exact current clip"] }, created_at: "2026-08-24T03:01:00Z" }) as any;
  const rejectedSubject: Stage2PermissionTypedRef = { object_type: "editorial_edit_intent", object_id: rejectedRevision.intent.value.intent_id, object_version: rejectedRevision.intent.value.object_version, digest: rejectedRevision.intent.object_hash }, rejectedDiagnosisRef: Stage2PermissionTypedRef = { object_type: "feedback_diagnosis", object_id: rejectedRevision.diagnosis.value.diagnosis_id, object_version: rejectedRevision.diagnosis.value.object_version, digest: rejectedRevision.diagnosis.object_hash }, rejectedContexts: Stage2PermissionTypedRef[] = [rejectedDiagnosisRef, { object_type: "intelligence_edit_execution", ...rejectedRevision.diagnosis.value.base_execution_ref }, { object_type: "creative_contract", ...rejectedRevision.intent.value.contract_ref }, { object_type: "approved_story_plan_v2", ...rejectedRevision.intent.value.approved_story_ref }], rejectReason = "reject exact local revision";
  await human.issue(host, "approval-pipeline-feedback-reject", "feedback_revision.reject", rejectedSubject, rejectedContexts, ["reason", "review_digest"], rejectedRevision.diagnosis.value.affected_scope, { intent_ref: rejectedSubject, diagnosis_ref: rejectedDiagnosisRef, reason: rejectReason, review_digest: rejectedRevision.intent.object_hash }, rejectReason);
  const beforeReject = snapshot(); await host.rejectFeedbackRevision({ intent_id: rejectedRevision.intent.value.intent_id, approval_id: "approval-pipeline-feedback-reject", reason: rejectReason, review_digest: rejectedRevision.intent.object_hash }); const afterReject = snapshot(); assert.equal((host.readTimelineSnapshot() as any).version, 1); assert.equal(afterReject.timelines, beforeReject.timelines); assert.equal(afterReject.commands, beforeReject.commands); assert.equal(afterReject.renderBundles, beforeReject.renderBundles); assert.equal(afterReject.renderResults, beforeReject.renderResults); assert.equal(afterReject.refs, beforeReject.refs + 1, "explicit rejection may register only its exact Permission Decision object ref"); assert.equal(afterReject.permissions, beforeReject.permissions + 1, "explicit rejection must retain one exact Permission Decision"); assert.equal(afterReject.events, beforeReject.events + 1, "explicit rejection must retain one exact audit event");

  const beforeUnknownTarget = snapshot(); await assert.rejects(() => host!.createFeedbackRevision({ diagnosis_id: "diagnosis-pipeline-missing", intent_id: "intent-pipeline-missing", base_execution_id: identity.execution_id, feedback_text: "收短不存在的镜头", target: { track_id: "v1", clip_id: "missing", proposed_source: proposedSource }, reason: "reject unknown feedback target", alternatives: [], confidence: { score: 0, basis: ["target is unavailable"] }, created_at: "2026-08-24T03:01:30Z" }), /FEEDBACK_TARGET_UNAVAILABLE/); assert.deepEqual(snapshot(), beforeUnknownTarget, "unknown feedback target must write nothing");
  const staleRevision = await host.createFeedbackRevision({ diagnosis_id: "diagnosis-pipeline-stale", intent_id: "intent-pipeline-stale", base_execution_id: identity.execution_id, feedback_text: "基于旧时间线收短镜头", target: { track_id: "v1", clip_id: firstCutClip.clip_id, proposed_source: proposedSource }, reason: "retain a candidate bound to the accepted first cut", alternatives: ["retain accepted first cut"], confidence: { score: 1, basis: ["exact accepted execution, clip and source range"] }, created_at: "2026-08-24T03:01:45Z" }) as any;
  const revision = await host.createFeedbackRevision({ diagnosis_id: "diagnosis-pipeline-trim", intent_id: "intent-pipeline-trim", base_execution_id: identity.execution_id, feedback_text: "把已接受的开场镜头尾部收短一点", target: { track_id: "v1", clip_id: firstCutClip.clip_id, proposed_source: proposedSource }, reason: "apply one exact inward trim", alternatives: ["retain accepted first cut"], confidence: { score: 1, basis: ["exact accepted execution, clip and source range"] }, created_at: "2026-08-24T03:02:00Z" }) as any;
  const feedbackEdgeKinds = (listFeedbackDiagnosisEdges(session, projectId, revision.diagnosis.value.diagnosis_id) as any[]).map((edge) => edge.edge_kind); assert.deepEqual(feedbackEdgeKinds.filter((kind) => kind !== "evidence"), ["approved_story", "base_execution", "capability_snapshot", "contract", "decision"]); assert.equal(feedbackEdgeKinds.filter((kind) => kind === "evidence").length, plannedBeatSeconds.length);
  const beforePreview = snapshot(), feedbackPreview = await host.previewFeedbackRevision(revision.intent.value.intent_id); assert.deepEqual(snapshot(), beforePreview, "feedback effect preview must not persist or mutate Timeline"); assert.equal(feedbackPreview.base_timeline_version, 1); assert.equal(feedbackPreview.expected_final_timeline_version, 2); assert.equal(feedbackPreview.effect.compiler_id, "feedback-revision-inward-trim"); assert.equal((await host.readFeedbackDiagnosis(revision.diagnosis.value.diagnosis_id) as any).lifecycle_status, "reviewed");
  const feedbackProposalApproval = await approveIntent(revision.intent, "approval-pipeline-feedback-intent", "approve exact feedback revision");
  const feedbackIdentity = { execution_id: "execution-pipeline-feedback", intent_id: revision.intent.value.intent_id, proposal_approval_decision_id: feedbackProposalApproval.value.decision_id }, feedbackExecutionReview = await host.prepareEditorialIntentExecution(feedbackIdentity);
  assert.equal(feedbackExecutionReview.base_timeline_version, 1); assert.equal(feedbackExecutionReview.expected_final_timeline_version, 2); assert.equal(feedbackExecutionReview.compiler_id, "feedback-revision-inward-trim");
  await human.issueDigest(host, "approval-pipeline-feedback-rebound", "editorial_edit_intent.execute", feedbackExecutionReview.subject_ref, feedbackExecutionReview.context_refs, feedbackExecutionReview.requested_data_fields, feedbackExecutionReview.affected_scope, fixed("9"), "attempt rebound feedback execution");
  const beforeFeedbackRebound = snapshot(); await assert.rejects(() => host!.executeApprovedEditorialIntent({ ...feedbackIdentity, execution_approval_id: "approval-pipeline-feedback-rebound", reason: "execute exact feedback revision" }), /APPROVAL_REBOUND/); assert.deepEqual(snapshot(), beforeFeedbackRebound, "feedback execution approval rebound must write nothing");
  await human.issueDigest(host, "approval-pipeline-feedback-execution", "editorial_edit_intent.execute", feedbackExecutionReview.subject_ref, feedbackExecutionReview.context_refs, feedbackExecutionReview.requested_data_fields, feedbackExecutionReview.affected_scope, feedbackExecutionReview.effect_digest, "execute exact feedback revision");
  const feedbackConflictRefId = `${projectId}:edit-ir:execute:${revision.intent.value.intent_id}`; await putObjectAndRegister(session, projectId, Buffer.from("forced feedback edit IR object id conflict"), { object_ref_id: feedbackConflictRefId, object_type: "fault_fixture", relation_key: "feedback-fault" });
  const beforeFeedbackFault = snapshot(); await assert.rejects(() => host!.executeApprovedEditorialIntent({ ...feedbackIdentity, execution_approval_id: "approval-pipeline-feedback-execution", reason: "execute exact feedback revision" }), /atomic artifact id conflict/); assert.deepEqual(snapshot(), beforeFeedbackFault, "feedback storage conflict must roll back permission, Timeline, command, event and render writes");
  session.db.prepare("DELETE FROM object_refs WHERE object_ref_id = ?").run(feedbackConflictRefId);
  const feedbackExecuted = await host.executeApprovedEditorialIntent({ ...feedbackIdentity, execution_approval_id: "approval-pipeline-feedback-execution", reason: "execute exact feedback revision" }) as any;
  const revisedTimeline = host.readTimelineSnapshot() as any; assert.equal(revisedTimeline.version, 2); assert.equal(revisedTimeline.tracks[0].clips.length, plannedBeatSeconds.length); assert.equal(Number(revisedTimeline.tracks[0].clips[0].source.end_pts), proposedSource.end.value); assert.equal(feedbackExecuted.base_execution_ref.object_id, identity.execution_id); assert.equal(feedbackExecuted.feedback_diagnosis_ref.object_id, revision.diagnosis.value.diagnosis_id);
  const beforeStalePreview = snapshot(); await assert.rejects(() => host!.previewFeedbackRevision(staleRevision.intent.value.intent_id), /FEEDBACK_REVISION_TIMELINE_STALE/); assert.deepEqual(snapshot(), beforeStalePreview, "stale feedback Timeline candidate must write nothing");
  const beforeStaleExecution = snapshot(); await assert.rejects(() => host!.createFeedbackRevision({ diagnosis_id: "diagnosis-pipeline-stale-execution", intent_id: "intent-pipeline-stale-execution", base_execution_id: identity.execution_id, feedback_text: "继续修改已被后续版本替代的执行", target: { track_id: "v1", clip_id: firstCutClip.clip_id, proposed_source: proposedSource }, reason: "reject stale base execution", alternatives: [], confidence: { score: 0, basis: ["base execution is stale"] }, created_at: "2026-08-24T03:03:00Z" }), /FEEDBACK_BASE_EXECUTION_NOT_CURRENT/); assert.deepEqual(snapshot(), beforeStaleExecution, "stale feedback execution must write nothing");
  const beforeFeedbackRetry = snapshot(), feedbackRetry = await host.executeApprovedEditorialIntent({ ...feedbackIdentity, execution_approval_id: "approval-pipeline-feedback-execution", reason: "execute exact feedback revision" }) as any; assert.deepEqual(feedbackRetry, feedbackExecuted); assert.deepEqual(snapshot(), beforeFeedbackRetry, "feedback execution retry must be read-only");

  if (realMode) {
    const outputDirectory = resolve(root, "review"); await mkdir(outputDirectory, { recursive: true });
    const immutableLocationRow = session.db.prepare("SELECT asset_location_id, location_ref, metadata_json FROM asset_locations WHERE project_id = ? AND asset_id = ? AND location_type = 'immutable_original'").get(projectId, asset) as any;
    assert.ok(immutableLocationRow, "execution-bound render must use the project-owned immutable Original");
    const executionRenderOptions = { sources: [{ asset_ref: asset, original_ref: immutableLocationRow.location_ref, original_object_ref: immutableLocationRow.asset_location_id, source_timescale: BigInt(sourceTimescale), original_timescale: BigInt(sourceTimescale) }], outputDirectory, profile: { name: "semantic-intent-preflight" }, qcRequirements: { planned_silence: true }, executionBinding: { execution_id: feedbackExecuted.execution_id, timeline_version: feedbackExecuted.final_timeline_version, semantic_graph_hash: feedbackExecuted.semantic_graph_hash, preview_plan_id: feedbackExecuted.preview_plan_id, master_plan_id: feedbackExecuted.master_plan_id, source_identity_digest: feedbackExecuted.source_identity_digest } } as const;
    const authorizedMetadata = JSON.parse(immutableLocationRow.metadata_json), renderPersistence = () => ({ bundles: session.db.prepare("SELECT COUNT(*) count FROM render_bundles").get().count, results: session.db.prepare("SELECT COUNT(*) count FROM render_results").get().count, refs: session.db.prepare("SELECT COUNT(*) count FROM object_refs").get().count });
    session.db.prepare("UPDATE asset_locations SET metadata_json = ? WHERE project_id = ? AND asset_location_id = ?").run(JSON.stringify({ ...authorizedMetadata, permission_state: "denied" }), projectId, immutableLocationRow.asset_location_id); const beforeUnauthorizedRender = renderPersistence(); await assert.rejects(() => host!.renderTimeline(executionRenderOptions), /SEMANTIC_RENDER_ORIGINAL_UNAUTHORIZED/); assert.deepEqual(renderPersistence(), beforeUnauthorizedRender, "revoked immutable Original must block before render persistence"); session.db.prepare("UPDATE asset_locations SET metadata_json = ? WHERE project_id = ? AND asset_location_id = ?").run(JSON.stringify(authorizedMetadata), projectId, immutableLocationRow.asset_location_id);
    const reboundCases = [
      ["execution_id", "execution-rebound", /SEMANTIC_RENDER_EXECUTION_REBOUND/],
      ["source_identity_digest", fixed("1"), /SEMANTIC_RENDER_SOURCE_IDENTITY_REBOUND/],
      ["semantic_graph_hash", fixed("2"), /SEMANTIC_RENDER_GRAPH_REBOUND/],
      ["preview_plan_id", "plan-preview-rebound", /SEMANTIC_RENDER_PLAN_REBOUND/],
      ["master_plan_id", "plan-master-rebound", /SEMANTIC_RENDER_PLAN_REBOUND/],
    ] as const;
    for (const [field, value, error] of reboundCases) { const beforeRebound = renderPersistence(), reboundOptions = { ...executionRenderOptions, executionBinding: { ...executionRenderOptions.executionBinding, [field]: value } }; await assert.rejects(() => host!.renderTimeline(reboundOptions), error); assert.deepEqual(renderPersistence(), beforeRebound, `${field} rebound must block before render persistence`); }
    const rendered = await host.renderTimeline(executionRenderOptions) as any;
    assert.equal(rendered.status.qc, "passed"); const preview = rendered.preview.outputs.find((item: any) => item.kind === "render"), master = rendered.master.outputs.find((item: any) => item.kind === "render"); if (!preview?.path || !master?.path) throw new Error("INTELLIGENCE_PIPELINE_REAL_OUTPUT_MISSING");
    assert.equal(preview.semantic_graph_hash, feedbackExecuted.semantic_graph_hash, "Preview must encode the exact feedback execution-bound semantic graph"); assert.equal(master.semantic_graph_hash, feedbackExecuted.semantic_graph_hash, "Master must encode the exact feedback execution-bound semantic graph");
    const previewPath = resolve(outputDirectory, "preview.mp4"), masterPath = resolve(outputDirectory, "master.mp4"); await copyFile(preview.path, previewPath); await copyFile(master.path, masterPath);
    const previewHash = createHash("sha256").update(await readFile(previewPath)).digest("hex"), masterHash = createHash("sha256").update(await readFile(masterPath)).digest("hex");
    const outputProbe = JSON.parse(String((await run("ffprobe", ["-v", "error", "-show_entries", "format=duration:stream=codec_type,width,height,r_frame_rate,nb_frames", "-of", "json", masterPath])).stdout));
    await writeFile(resolve(outputDirectory, "INTELLIGENCE-PIPELINE-REVIEW.json"), JSON.stringify({ schema_version: 1, status: "agent_visual_precheck_pending", execution_id: feedbackIdentity.execution_id, base_execution_id: identity.execution_id, feedback_diagnosis_id: revision.diagnosis.value.diagnosis_id, intent_id: revision.intent.value.intent_id, timeline_version: revisedTimeline.version, feedback_trim: { base_source_end_pts: Number(firstCutClip.source.end_pts), revised_source_end_pts: proposedSource.end.value, trim_amount_pts: trimAmount, timescale: Number(firstCutClip.source.timescale), trim_duration_seconds: trimAmount / Number(firstCutClip.source.timescale) }, execution_semantic_graph_hash: feedbackExecuted.semantic_graph_hash, preview_semantic_graph_hash: preview.semantic_graph_hash, master_semantic_graph_hash: master.semantic_graph_hash, compiled_effect_digest: feedbackExecuted.compiled_effect_digest, preview_path: previewPath, preview_sha256: previewHash, master_path: masterPath, master_sha256: masterHash, qc_status: rendered.status.qc, output_probe: outputProbe, original_path: mediaPath }, null, 2));
    console.log(`INTELLIGENCE_PIPELINE_REAL_REVIEW_ROOT=${root}`);
  }

  host.undoTimeline(); assert.equal((host.readTimelineSnapshot() as any).version, 3); assert.equal(Number((host.readTimelineSnapshot() as any).tracks[0].clips[0].source.end_pts), Number(firstCutClip.source.end_pts)); assert.equal((readIntelligenceEditExecution(session, projectId, feedbackIdentity.execution_id) as any).value.compiled_effect_digest, feedbackExecuted.compiled_effect_digest); if (realMode) { const immutableLocation = session.db.prepare("SELECT asset_location_id, location_ref FROM asset_locations WHERE project_id = ? AND asset_id = ? AND location_type = 'immutable_original'").get(projectId, asset) as any; assert.ok(immutableLocation); await assert.rejects(() => host!.renderTimeline({ sources: [{ asset_ref: asset, original_ref: immutableLocation.location_ref, original_object_ref: immutableLocation.asset_location_id, source_timescale: BigInt(sourceTimescale), original_timescale: BigInt(sourceTimescale) }], profile: { name: "semantic-intent-preflight" }, executionBinding: { execution_id: feedbackExecuted.execution_id, timeline_version: feedbackExecuted.final_timeline_version, semantic_graph_hash: feedbackExecuted.semantic_graph_hash, preview_plan_id: feedbackExecuted.preview_plan_id, master_plan_id: feedbackExecuted.master_plan_id, source_identity_digest: feedbackExecuted.source_identity_digest } }), /SEMANTIC_RENDER_TIMELINE_REBOUND/); }
  host.redoTimeline(); assert.equal((host.readTimelineSnapshot() as any).version, 4); assert.equal(Number((host.readTimelineSnapshot() as any).tracks[0].clips[0].source.end_pts), proposedSource.end.value); assert.equal((readIntelligenceEditExecution(session, projectId, feedbackIdentity.execution_id) as any).value.command_edit_ir_id, feedbackExecuted.command_edit_ir_id);
  await host.close(); host = undefined;
  reopened = new ProjectHostSession(human.options); await reopened.open(root); const reopenedSession = (reopened as any).session, reopenedProjectId = reopenedSession.manifest.project_id;
  assert.equal((reopened.readTimelineSnapshot() as any).version, 4); assert.equal(Number((reopened.readTimelineSnapshot() as any).tracks[0].clips[0].source.end_pts), proposedSource.end.value); assert.equal((readIntelligenceEditExecution(reopenedSession, reopenedProjectId, feedbackIdentity.execution_id) as any).value.semantic_graph_hash, feedbackExecuted.semantic_graph_hash);
  await reopened.close(); reopened = undefined;
} finally {
  await reopened?.close().catch(() => undefined); await host?.close().catch(() => undefined); if (typeof global.gc === "function") global.gc(); await new Promise((done) => setTimeout(done, 50)); if (!realMode) await rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });
}

console.log("Intelligence pipeline and scoped feedback revision approval, rejection, atomic commit, idempotency, undo/redo and reopen checks passed");
