import assert from "node:assert/strict";
import { mkdtemp, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { createBuiltInStage2PermissionPolicySnapshot, createStage2PermissionDecision, evaluateStage2Permission, permissionRefKey, permissionRequestFingerprint, stage2PermissionEffectDigest } from "../../packages/features/permission-enforcement/src/public.ts";
import { editorialObjectDigest } from "../../packages/core/editorial-core/src/public.ts";
import { createProject, openProject, registerCreativeContractVersion, registerEvidence, registerStage2HumanApproval, registerStage2PermissionAuthorization, readStage2PermissionDecision, readStage2PermissionPolicySnapshot, listStage2PermissionDecisionEdges, runStage2AtomicMutation } from "../../packages/platform/project-storage/src/public.ts";

const root = await mkdtemp(resolve(tmpdir(), "ave-permission-storage-")), otherRoot = await mkdtemp(resolve(tmpdir(), "ave-permission-storage-other-")), renewalRoot = await mkdtemp(resolve(tmpdir(), "ave-permission-storage-renewal-"));
let session, reopened, other, renewal;
try {
  session = await createProject(root); const projectId = session.manifest.project_id;
  const contract = registerCreativeContractVersion(session, projectId, { schema_version: 2, contract_id: "contract-storage-permission", project_id: projectId, object_version: 1, status: "approved", created_at: "2026-08-24T01:00:00Z" });
  const subject = { object_type: "creative_contract", object_id: contract.value.contract_id, object_version: 1, digest: contract.object_hash }, snapshot = createBuiltInStage2PermissionPolicySnapshot(), policyRef = { object_id: snapshot.snapshot_id, object_version: snapshot.object_version, digest: editorialObjectDigest(snapshot) }, request = { schema_version: 1, request_id: "storage-query", actor: { actor_id: "project-host", actor_kind: "project_host" }, action: "creative_context.query", subject_ref: subject, context_refs: [], policy_snapshot_ref: policyRef, effect_digest: stage2PermissionEffectDigest("creative_context.query", { subject }), requested_data_fields: ["digest", "object_id", "object_version"], affected_scope: [], reason: "bounded storage query", requested_at: "2026-08-24T02:00:00Z" };
  const authority = { current_ref_keys: new Set([permissionRefKey(subject)]), authoritative_scope: [], protected_refs: [], now_ms: Date.parse("2026-08-24T02:00:00Z") }, decision = createStage2PermissionDecision(request, snapshot, evaluateStage2Permission(request, snapshot, authority));
  const counts = (db) => ({ objectStore: db.prepare("SELECT COUNT(*) count FROM object_store").get().count, objects: db.prepare("SELECT COUNT(*) count FROM object_refs").get().count, policies: db.prepare("SELECT COUNT(*) count FROM permission_policy_snapshots").get().count, decisions: db.prepare("SELECT COUNT(*) count FROM permission_decisions").get().count, edges: db.prepare("SELECT COUNT(*) count FROM permission_decision_edges").get().count, events: db.prepare("SELECT COUNT(*) count FROM project_events").get().count, timelines: db.prepare("SELECT COUNT(*) count FROM timeline_versions").get().count });
  const persisted = registerStage2PermissionAuthorization(session, projectId, snapshot, decision); assert.equal(persisted.value.decision_id, decision.decision_id); assert.equal(readStage2PermissionPolicySnapshot(session, projectId, snapshot.snapshot_id, snapshot.object_version).object_hash, decision.policy_snapshot_ref.digest); assert.equal(listStage2PermissionDecisionEdges(session, projectId, decision.decision_id).length, 2);
  const retryCounts = counts(session.db); assert.equal(registerStage2PermissionAuthorization(session, projectId, snapshot, decision).object_hash, persisted.object_hash); assert.deepEqual(counts(session.db), retryCounts);
  const objectFiles = async () => { const files = []; for (const shard of await readdir(resolve(root, "objects", "sha256"), { withFileTypes: true })) if (shard.isDirectory()) for (const file of await readdir(resolve(root, "objects", "sha256", shard.name))) files.push(`${shard.name}/${file}`); return files.sort(); };
  const fullSnapshot = async () => { const tables = session.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map((row) => row.name); return { tables: Object.fromEntries(tables.map((table) => [table, session.db.prepare(`SELECT * FROM \"${table}\" ORDER BY rowid`).all()])), files: await objectFiles() }; };
  const beforeStagedObjectFault = await fullSnapshot(); assert.throws(() => runStage2AtomicMutation(session, () => { registerEvidence(session, projectId, { evidence_id: "asr:atomic-fault", analysis_type: "asr", asset_id: `asset:sha256:${"5".repeat(64)}`, start_pts: 0, end_pts: 1, evidence_version: 1, review_status: "candidate", text: "must be rolled back" }); throw new Error("INJECTED_AFTER_OBJECT_STAGING"); }), /INJECTED_AFTER_OBJECT_STAGING/); assert.deepEqual(await fullSnapshot(), beforeStagedObjectFault, "outer Stage 2 rollback must restore every table and remove newly staged object files");
  const humanBase = { schema_version: 1, request_id: "storage-human-contract", actor: { actor_id: "reviewer-storage", actor_kind: "human_user" }, action: "creative_contract.approve", subject_ref: subject, context_refs: [], policy_snapshot_ref: policyRef, effect_digest: stage2PermissionEffectDigest("creative_contract.approve", { contract_id: subject.object_id, object_version: subject.object_version, review_digest: subject.digest, outcome: "approved" }), requested_data_fields: ["reason", "review_digest"], affected_scope: [permissionRefKey(subject)], reason: "approve exact storage Contract", requested_at: "2026-08-24T02:00:00Z" }, humanApproval = { approval_id: "approval-storage-contract", action: humanBase.action, actor_id: humanBase.actor.actor_id, actor_kind: "human_user", request_fingerprint: permissionRequestFingerprint(humanBase), subject_ref: subject, context_refs: [], policy_snapshot_ref: policyRef, effect_digest: humanBase.effect_digest, affected_scope: humanBase.affected_scope, review_digest: humanBase.effect_digest, approved_at: "2026-08-24T01:59:00Z", expires_at: "2026-08-24T03:00:00Z" }, humanRequest = { ...humanBase, approval: (({ action: _action, ...embedded }) => embedded)(humanApproval) }, humanDecision = createStage2PermissionDecision(humanRequest, snapshot, evaluateStage2Permission(humanRequest, snapshot, { ...authority, authoritative_scope: humanBase.affected_scope }));
  const beforeMissingTrustedApproval = await fullSnapshot(); assert.throws(() => registerStage2PermissionAuthorization(session, projectId, snapshot, humanDecision), /embedded approval is missing/); assert.deepEqual(await fullSnapshot(), beforeMissingTrustedApproval, "self-consistent embedded approval without a trusted approval row must write nothing"); registerStage2HumanApproval(session, projectId, humanApproval); const persistedHumanDecision = registerStage2PermissionAuthorization(session, projectId, snapshot, humanDecision); assert.equal(persistedHumanDecision.value.approval.approval_id, humanApproval.approval_id);
  const reboundHumanDecision = { ...humanDecision, decision_id: "permission:storage-human-rebound", approval: { ...humanDecision.approval, expires_at: "2026-08-24T04:00:00Z" } }, beforeApprovalRebind = await fullSnapshot(); assert.throws(() => registerStage2PermissionAuthorization(session, projectId, snapshot, reboundHumanDecision), /embedded approval is missing or rebound/); assert.deepEqual(await fullSnapshot(), beforeApprovalRebind, "embedded approval must exactly equal its trusted approval record");
  const { input_fingerprint: _snapshotFingerprint, ...alternateBaseSeed } = snapshot, alternateBase = { ...alternateBaseSeed, snapshot_id: "stage2-permission-policy-alternate" }, alternateSnapshot = { ...alternateBase, input_fingerprint: editorialObjectDigest(alternateBase) }, alternatePolicyRef = { object_id: alternateSnapshot.snapshot_id, object_version: 1, digest: editorialObjectDigest(alternateSnapshot) }, alternateRequest = { ...request, request_id: "storage-query-alternate", policy_snapshot_ref: alternatePolicyRef }, alternateDecision = { ...decision, decision_id: "permission:storage-query-alternate", policy_snapshot_ref: alternatePolicyRef, input_fingerprint: permissionRequestFingerprint(alternateRequest), provenance: { ...decision.provenance, input_refs: [alternatePolicyRef.digest, subject.digest] } }, filesBeforePolicyConflict = await objectFiles(), countsBeforePolicyConflict = counts(session.db); assert.throws(() => registerStage2PermissionAuthorization(session, projectId, alternateSnapshot, alternateDecision), /internally inconsistent|policy version conflict/); assert.deepEqual(counts(session.db), countsBeforePolicyConflict); assert.deepEqual(await objectFiles(), filesBeforePolicyConflict, "preflight policy rejection must not leave orphan object files");
  for (const invalid of [
    { ...decision, decision_id: "wrong-digest", input_fingerprint: "1".repeat(64), subject_ref: { ...subject, digest: "0".repeat(64) } },
    { ...decision, decision_id: "wrong-version", input_fingerprint: "2".repeat(64), subject_ref: { ...subject, object_version: 2 } },
    { ...decision, decision_id: "wrong-policy", input_fingerprint: "3".repeat(64), policy_snapshot_ref: { ...decision.policy_snapshot_ref, digest: "4".repeat(64) } },
  ]) { const before = counts(session.db); assert.throws(() => registerStage2PermissionAuthorization(session, projectId, snapshot, invalid), /rebound|missing|inconsistent/); assert.deepEqual(counts(session.db), before); }
  const conflictRequest = { ...request, reason: "conflicting semantic retry" }, conflict = createStage2PermissionDecision(conflictRequest, snapshot, evaluateStage2Permission(conflictRequest, snapshot, authority)); const beforeConflict = counts(session.db); assert.throws(() => registerStage2PermissionAuthorization(session, projectId, snapshot, conflict), /decision conflict/); assert.deepEqual(counts(session.db), beforeConflict);
  other = await createProject(otherRoot); const otherBefore = counts(other.db); assert.throws(() => registerStage2PermissionAuthorization(other, other.manifest.project_id, snapshot, decision), /missing or rebound/); assert.deepEqual(counts(other.db), otherBefore); await other.close(); other = undefined;
  const original = readStage2PermissionDecision(session, projectId, decision.decision_id), originalEdges = listStage2PermissionDecisionEdges(session, projectId, decision.decision_id); await session.close(); session = undefined; reopened = await openProject(root); const reopenedDecision = readStage2PermissionDecision(reopened, projectId, decision.decision_id); assert.equal(reopenedDecision.object_hash, original.object_hash); assert.deepEqual(reopenedDecision.value, original.value); assert.deepEqual(listStage2PermissionDecisionEdges(reopened, projectId, decision.decision_id), originalEdges); await reopened.close(); reopened = undefined;
  renewal = await createProject(renewalRoot); const renewalProjectId = renewal.manifest.project_id, firstApproval = { ...humanApproval, approval_id: "approval-current-first", subject_ref: { ...humanApproval.subject_ref, object_id: "current-renewal-subject" }, request_fingerprint: "9".repeat(64) }; registerStage2HumanApproval(renewal, renewalProjectId, firstApproval); const renewedApproval = { ...firstApproval, approval_id: "approval-current-renewed", approved_at: "2026-08-24T02:01:00Z", expires_at: "2026-08-24T04:00:00Z" }; registerStage2HumanApproval(renewal, renewalProjectId, renewedApproval); assert.equal(renewal.db.prepare("SELECT COUNT(*) count FROM permission_human_approvals WHERE project_id = ? AND request_fingerprint = ?").get(renewalProjectId, firstApproval.request_fingerprint).count, 2, "current baseline must allow a renewed approval with the same semantic fingerprint"); await renewal.close(); renewal = undefined; renewal = await openProject(renewalRoot); assert.equal(renewal.db.prepare("SELECT format_version FROM project_format").get().format_version, 2); assert.equal(renewal.db.prepare("SELECT COUNT(*) count FROM permission_human_approvals WHERE project_id = ?").get(renewalProjectId).count, 2);
} finally { await renewal?.close().catch(() => undefined); await other?.close().catch(() => undefined); await reopened?.close().catch(() => undefined); await session?.close().catch(() => undefined); await rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); await rm(otherRoot, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); await rm(renewalRoot, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); }
console.log("Stage 2 permission storage exact refs, atomic idempotency, renewal and v2 reopen checks passed");
