import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile, mkdir, rm, symlink, realpath } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import type { BrowserWindow } from "electron";
import { ProjectHostSession } from "../../packages/platform/project-host/src/public.js";
import { RecentProjects } from "../../apps/desktop/src/main/recent-projects.js";
import { ProjectSessionManager } from "../../apps/desktop/src/main/project-session-manager.js";
import { registerProjectHandlers } from "../../apps/desktop/src/main/ipc/project.handlers.js";
import { creationErrorResult } from "../../apps/desktop/src/main/ipc/creation-errors.js";
import { validateSender } from "../../apps/desktop/src/main/validate-sender.js";
import { createEventBus } from "../../packages/platform/project-api/src/public.js";
import type { DesktopContext } from "../../apps/desktop/src/main/types.js";
import { readCreationLearningObject } from "../../packages/platform/project-storage/src/public.js";

const root=await mkdtemp(resolve(tmpdir(),"ave-stage3-recents-")), index=resolve(root,"user-a/recent-projects.json"), credential={};
let clock=0;
const recents=new RecentProjects(index,()=>new Date(Date.UTC(2026,8,28,0,0,clock++))), host=new ProjectHostSession({creationRequestChannels:[{credential,actor_id:"test-user"}]});
const profile={close:async()=>undefined}, sessions=new ProjectSessionManager(host,profile);
const window={webContents:{id:41,send(){}}} as unknown as BrowserWindow;sessions.registerWindow(window);
const event={sender:{id:41},senderFrame:{url:"app://renderer/index.html"}} as any;
let selected: {canceled:boolean;filePaths:string[]}={canceled:true,filePaths:[]}, deferredDialog:Promise<typeof selected>|null=null;
const context={host,recents,sessions,profile,creationCredential:credential,events:createEventBus(),dialog:{}} as unknown as DesktopContext;
const queries=new Map<string,any>(), commands=new Map<string,any>();
registerProjectHandlers(queries,commands,context,(_context,_event,operation)=>sessions.waitForDialog(operation,()=>deferredDialog??Promise.resolve(selected)));
const invoke=async(name:string,payload:unknown={})=>{validateSender(event,sessions);const operation=sessions.capture(41,sessions.activeProjectId(),false);return sessions.run(operation,()=>commands.get(name)({payload},event,operation));};
const query=async(payload:unknown={})=>{validateSender(event,sessions);const operation=sessions.capture(41,sessions.activeProjectId(),false);return sessions.run(operation,()=>queries.get("app.projects.recent")({payload},event,operation));};
const code=(expected:string)=>(error:any)=>error.code===expected;
try {
  assert.deepEqual(await query(),{items:[]});assert.equal(host.status().project,"not-open");
  await assert.rejects(queries.get("app.projects.recent")({}),code("DESKTOP_RECENT_INPUT_INVALID"));
  for(const payload of [null,[],{path:"private"}])await assert.rejects(query(payload),code("DESKTOP_RECENT_INPUT_INVALID"));
  assert.throws(()=>validateSender({...event,senderFrame:{url:"https://evil.example/"}},sessions),/untrusted/);
  assert.throws(()=>validateSender({...event,sender:{id:999}},sessions),/untrusted/);
  const target=resolve(root,"physical"),alias=resolve(root,"native-selected-alias");await mkdir(target);
  await symlink(target,alias,process.platform==="win32"?"junction":"dir");
  const a=resolve(alias,"真实作品 A"),b=resolve(root,"真实作品 B");
  selected={canceled:false,filePaths:[a]};const aStatus=await invoke("project.create");
  selected={canceled:false,filePaths:[b]};const bStatus=await invoke("project.create");
  const list=await query();assert.equal(list.items.length,2);assert.deepEqual(list.items.map((item:any)=>item.display_name),["真实作品 B","真实作品 A"]);
  for(const item of list.items)assert.deepEqual(Object.keys(item).sort(),["display_name","id","last_opened_at"]);
  assert.equal(JSON.stringify(list).includes(root),false);assert.equal(JSON.stringify(list).includes("project.sqlite"),false);
  const aId=list.items.find((item:any)=>item.display_name==="真实作品 A").id;
  assert.notEqual(await realpath(a),a,"fixture must exercise a real filesystem alias");
  assert.equal((await recents.lookup(aId)).path,a,"navigation preserves the successfully opened Host path, not realpath");
  await invoke("project.close");assert.equal(host.status().project,"not-open");assert.equal((await query()).items.length,2);
  const opened=await invoke("project.open-recent",{id:aId});assert.equal(opened.project,aStatus.project);
  const aSession=(host as any).session, timelineRow=aSession.db.prepare("SELECT relation_key,version FROM object_refs WHERE object_type='timeline_snapshot' ORDER BY version DESC LIMIT 1").get();
  assert.ok(readCreationLearningObject(aSession,aStatus.project,"timeline_snapshot",timelineRow.relation_key,timelineRow.version),"strict learning reference remains readable after A to B to recent A");
  // An index written by the old canonicalizing implementation is repaired only
  // after an explicit successful native open; no project object is rewritten.
  const legacy=JSON.parse(await readFile(index,"utf8"));legacy.entries.find((item:any)=>item.id===aId).path=await realpath(a);await writeFile(index,JSON.stringify(legacy));
  selected={canceled:false,filePaths:[a]};await invoke("project.open");
  assert.equal((await recents.lookup(aId)).path,a);assert.equal((await query()).items.length,2);
  assert.equal((await new RecentProjects(index).list()).items[0]!.id,aId,"restart preserves opaque ID and recent ordering");
  const otherUser=new RecentProjects(resolve(root,"user-b/recent-projects.json"));assert.deepEqual(await otherUser.list(),{items:[]});await assert.rejects(otherUser.lookup(aId),code("DESKTOP_RECENT_NOT_FOUND"));
  const before=await readFile(index,"utf8");
  for(const payload of [{id:aId,path:b},{path:b},{id:""},null])await assert.rejects(invoke("project.open-recent",payload),code("DESKTOP_RECENT_INPUT_INVALID"));
  await assert.rejects(invoke("project.open-recent",{id:"unknown"}),code("DESKTOP_RECENT_NOT_FOUND"));assert.equal(host.status().project,aStatus.project);
  selected={canceled:true,filePaths:[]};await assert.rejects(invoke("project.open"),/没有选择/);assert.equal(await readFile(index,"utf8"),before);
  selected={canceled:false,filePaths:[resolve(root,"missing-project")]};await assert.rejects(invoke("project.open"));assert.equal(await readFile(index,"utf8"),before,"failed Host open never creates a recent reference");
  selected={canceled:false,filePaths:[a]};await invoke("project.open");
  const saved=await readFile(index,"utf8"), parsed=JSON.parse(saved);parsed.entries.find((item:any)=>item.id===aId).project_id=bStatus.project;await writeFile(index,JSON.stringify(parsed));
  let recoveries=0;const originalRecover=host.recoverOpenJobs.bind(host);host.recoverOpenJobs=()=>{recoveries++;return originalRecover();};
  await assert.rejects(invoke("project.open-recent",{id:aId}),code("DESKTOP_RECENT_PROJECT_CHANGED"));assert.equal(recoveries,0);assert.equal(host.status().project,"not-open");
  selected={canceled:false,filePaths:[a]};await invoke("project.open");const replacement=(await query()).items.find((item:any)=>item.display_name==="真实作品 A");assert.notEqual(replacement.id,aId,"native reconfirmation of another project identity must allocate a new opaque ID");await assert.rejects(invoke("project.open-recent",{id:aId}),code("DESKTOP_RECENT_NOT_FOUND"));
  await writeFile(index,saved);
  const originalSave=(recents as any).save.bind(recents);(recents as any).save=async()=>{throw new Error("controlled storage failure PRIVATE_PATH");};
  selected={canceled:false,filePaths:[b]};await assert.rejects(invoke("project.open"),(error:any)=>{assert.equal(error.code,"DESKTOP_RECENT_SAVE_FAILED_AFTER_OPEN");const safe=creationErrorResult("COMMAND_FAILED",error);assert.match(safe.error.message,/已成功打开/);assert.doesNotMatch(safe.error.message,/PRIVATE_PATH/);return true;});assert.equal(host.status().project,bStatus.project);assert.equal(await readFile(index,"utf8"),saved);(recents as any).save=originalSave;
  await writeFile(index,"{broken");await assert.rejects(query(),code("DESKTOP_RECENT_INDEX_INVALID"));
  selected={canceled:false,filePaths:[a]};await assert.rejects(invoke("project.open"),code("DESKTOP_RECENT_SAVE_FAILED_AFTER_OPEN"));assert.equal(host.status().project,aStatus.project);assert.equal(await readFile(index,"utf8"),"{broken","corrupt index is never silently reset");await writeFile(index,saved);
  let finishDialog!:(value:typeof selected)=>void;deferredDialog=new Promise(resolve=>{finishDialog=resolve;});
  const pending=invoke("project.open"), cancelled=assert.rejects(pending,code("DESKTOP_SESSION_STALE"));
  await new Promise(resolve=>setImmediate(resolve));await invoke("project.close");await cancelled;finishDialog({canceled:false,filePaths:[b]});await new Promise(resolve=>setImmediate(resolve));
  assert.equal(host.status().project,"not-open");assert.equal(await readFile(index,"utf8"),saved,"late native selection cannot enter Host or mutate recents");deferredDialog=null;
  console.log("Recent projects: real Host/native-bound registration, opaque projection, userData isolation, identity-before-recovery, strict index/write failures and stale lifecycle passed",root);
} finally { await host.close(); await rm(root,{recursive:true,force:true}); }
