import { strict as assert } from "node:assert";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { ProfileError, ProfileRepository, type EditingPrinciple } from "../../packages/platform/user-profile-store/src/public.js";

const root = await mkdtemp(resolve(tmpdir(), "ave-stage3-profile-"));
const credential = {}, now = () => Date.parse("2026-09-18T01:00:00Z");
let repository: ProfileRepository | undefined;
const query = { project_id: "held-out-project-1", contexts: ["daily"], except_principle_ids: [] };
const consent = { source_project_ids: ["history-project"], data_types: ["feedback" as const], retention_until: "2027-01-01T00:00:00Z", external_provider: "configured-provider", enabled: true };
const event = { source_project_id: "history-project", source_event_id: "feedback-1", content_digest: "a".repeat(64), correction_digest: null, data_type: "feedback" as const, evidence_refs: ["feedback-1"] };
const principle: EditingPrinciple = { principle_id: "principle-1", source_project_id: event.source_project_id, source_event_id: event.source_event_id, source_digest: event.content_digest, data_type: "feedback", dimension: "caption", statement: "PRIVATE_FIXTURE_PREFERENCE_no_imposed_closing_moral", contexts: ["daily"], exceptions: ["explicit poetic request"], status: "hypothesis", evidence_refs: ["feedback-1"], created_at: "2026-09-18T00:00:00Z" };
const code = (expected: string) => (error: unknown) => error instanceof ProfileError && error.code === expected;
try {
  repository = new ProfileRepository(root, "user-1", credential, now);
  assert.equal((await repository.snapshot(query)).mode, "unconfigured");
  await assert.rejects(repository.prepareLearning(event, consent.external_provider, null), code("PROFILE_LEARNING_DENIED"));
  assert.throws(() => new ProfileRepository(root, "user-1", {}, now), /database is locked/);
  await assert.rejects(repository.configure({}, consent), code("PROFILE_CHANNEL_DENIED"));
  await repository.configure(credential, consent);
  assert.equal((await repository.snapshot(query)).mode, "empty");
  await assert.rejects(repository.prepareLearning(event, "unauthorized-provider", null), code("PROFILE_EXTERNAL_DENIED"));
  await assert.rejects(repository.prepareLearning({ ...event, data_type: "manual_diff" }, consent.external_provider, null), code("PROFILE_DATA_DENIED"));
  await assert.rejects(repository.prepareLearning({ ...event, source_project_id: "held-out-project-1" }, consent.external_provider, null), code("PROFILE_SOURCE_EXCLUDED"));
  const permit = await repository.prepareLearning(event, consent.external_provider, null), outcome = { principles: [principle], no_inference_reason: null };
  let learningSends = 0;
  await assert.rejects(repository.dispatchLearning({ ...permit, provider: "unauthorized-provider" }, () => { learningSends++; return { response: Promise.resolve("bad") }; }), code("PROFILE_EXTERNAL_DENIED"));
  await assert.rejects(repository.dispatchLearning(permit, (async () => { learningSends++; }) as any), code("PROFILE_ASYNC_SEND_DENIED"));
  assert.equal(learningSends, 0, "empty-profile learning checks provider and immediate-send shape before any send");
  await assert.rejects(repository.learn(permit, { ...outcome, principles: [{ ...principle, evidence_refs: ["invented"] }] }), code("PROFILE_PROVENANCE_INVALID"));
  assert.equal(await repository.readLearningRegistration(event), null);
  const learned = await repository.learn(permit, outcome);
  assert.deepEqual(await repository.learn(permit, outcome), learned, "replayed learning event is idempotent");
  assert.deepEqual(await repository.readLearningRegistration(event), learned);
  await assert.rejects(repository.learn(permit, { ...outcome, principles: [{ ...principle, statement: "changed output" }] }), code("PROFILE_EVENT_CONFLICT"));
  const noSignal = { ...event, source_event_id: "no-signal" }, noSignalPermit = await repository.prepareLearning(noSignal, consent.external_provider, null);
  await assert.rejects(repository.learn(noSignalPermit, { principles: [], no_inference_reason: null }), code("PROFILE_LEARNING_OUTCOME_INVALID"));
  const noSignalOutcome = { principles: [], no_inference_reason: "The selected material does not establish a personal preference." };
  const noSignalRegistration = await repository.learn(noSignalPermit, noSignalOutcome);
  assert.deepEqual(noSignalRegistration.principle_ids, []); assert.equal(noSignalRegistration.no_inference_reason, noSignalOutcome.no_inference_reason);
  assert.deepEqual(await repository.learn(noSignalPermit, noSignalOutcome), noSignalRegistration);
  const personalized = await repository.snapshot(query);
  assert.equal(personalized.mode, "personalized"); assert.equal(personalized.principles[0].statement, principle.statement);
  assert.equal((await repository.snapshot({ ...query, project_id: "held-out-project-2", contexts: ["performance"] })).mode, "no_match");
  assert.equal((await repository.snapshot({ ...query, except_principle_ids: [principle.principle_id] })).principles.length, 0);
  assert.equal((await repository.snapshot(query)).principles.length, 1, "one-off exception does not erase long-term data");
  await repository.configure(credential, { ...consent, data_types: ["manual_diff"] });
  assert.equal((await repository.snapshot(query)).principles.length, 0, "narrowed current consent excludes older feedback data");
  await repository.configure(credential, consent);
  const badPermit = await repository.prepareLearning({ ...event, source_event_id: "bad-explicit" }, consent.external_provider, null);
  await assert.rejects(repository.learn(badPermit, { principles: [{ ...principle, source_event_id: "bad-explicit", status: "explicit" }], no_inference_reason: null }), code("PROFILE_EXPLICIT_DENIED"));
  const interruptedEvent = { ...event, source_event_id: "registration-ack" }, interruptedPermit = await repository.prepareLearning(interruptedEvent, consent.external_provider, null);
  const database = (repository as any).database, write = database.write.bind(database);
  database.write = () => { throw Object.assign(new Error("profile write fixture"), { code: "EIO" }); };
  await assert.rejects(repository.learn(interruptedPermit, noSignalOutcome), /profile write fixture/);
  assert.equal(await repository.readLearningRegistration(interruptedEvent), null, "failed write must not claim registration");
  database.write = (...args: any[]) => { write(...args); throw Object.assign(new Error("profile commit acknowledgement fixture"), { code: "EIO" }); };
  await assert.rejects(repository.learn(interruptedPermit, noSignalOutcome), /profile commit acknowledgement fixture/);
  database.write = write;
  const recoveredRegistration = await repository.readLearningRegistration(interruptedEvent);
  assert.ok(recoveredRegistration, "a committed result survives an acknowledgement failure");
  assert.deepEqual(await repository.learn(interruptedPermit, noSignalOutcome), recoveredRegistration);
  const currentSnapshot = await repository.snapshot(query);
  let commits = 0;
  await repository.withSnapshot(currentSnapshot, () => { commits += 1; });
  let releaseRemote!: (value: string) => void;
  await assert.rejects(repository.withSnapshot(currentSnapshot, (async () => { commits += 1; }) as any), code("PROFILE_ASYNC_COMMIT_DENIED"));
  assert.equal(commits, 1, "declared async commit is rejected before invoking user code");
  const remote = repository.dispatch(currentSnapshot, "configured-provider", () => ({ response: new Promise<string>(resolveResponse => { releaseRemote = resolveResponse; }) }));
  // A following read passes once send is started; the unresolved remote promise must not hold the queue.
  await repository.control();
  const latePermit = await repository.prepareLearning({ ...event, source_event_id: "late" }, consent.external_provider, null);
  let releaseLearning!: (value: string) => void;
  const learningRemote = repository.dispatchLearning(latePermit, () => { learningSends++; return { response: new Promise<string>(resolveResponse => { releaseLearning = resolveResponse; }) }; });
  await repository.control();
  const deletionScope = ["history-project"];
  const deletion = repository.forgetSources(credential, deletionScope);
  deletionScope[0] = "another-project";
  const oldCommit = repository.withSnapshot(currentSnapshot, () => { commits += 1; });
  const oldAssertion = assert.rejects(oldCommit, code("PROFILE_SNAPSHOT_STALE"));
  const receipt = await deletion; await oldAssertion;
  assert.deepEqual(receipt.excluded_sources, ["history-project"], "queued deletion owns the originally selected scope");
  assert.equal(receipt.removed_principles, 1); assert.equal(commits, 1, "delete-before-commit must reject old snapshot");
  releaseRemote("already sent, may be billed"); assert.equal(await remote, "already sent, may be billed");
  releaseLearning("late learning response"); assert.equal(await learningRemote, "late learning response");
  await assert.rejects(repository.dispatchLearning(latePermit, () => { learningSends++; return { response: Promise.resolve("bad") }; }), code("PROFILE_GENERATION_STALE"));
  await assert.rejects(repository.withLearning(latePermit, () => { commits++; }), code("PROFILE_GENERATION_STALE"));
  await assert.rejects(repository.learn(latePermit, noSignalOutcome), code("PROFILE_GENERATION_STALE"));
  assert.equal(learningSends, 1); assert.equal(commits, 1); assert.equal(await repository.readLearningRegistration(noSignal), null);
  await assert.rejects(repository.withSnapshot(currentSnapshot, () => { commits += 1; }), code("PROFILE_SNAPSHOT_STALE"));
  await assert.rejects(repository.learn(permit, outcome), code("PROFILE_GENERATION_STALE"));
  await assert.rejects(repository.prepareLearning(event, consent.external_provider, null), code("PROFILE_SOURCE_EXCLUDED"));
  assert.equal((await repository.snapshot({ ...query, project_id: "new-after-forget" })).principles.length, 0);
  await repository.close(); repository = undefined;
  const bytes = await readFile(resolve(root, "user-profile.sqlite"));
  assert.equal(bytes.includes(Buffer.from(principle.statement)), false, "secure delete removes reusable principle body from live database");
  repository = new ProfileRepository(root, "user-1", credential, now);
  assert.equal((await repository.snapshot(query)).principles.length, 0);
  await assert.rejects(repository.prepareLearning(event, consent.external_provider, null), code("PROFILE_SOURCE_EXCLUDED"));
  await repository.configure(credential, { ...consent, enabled: false });
  assert.equal((await repository.snapshot(query)).mode, "disabled");
  await repository.close(); repository = undefined;
  const corrupt = new DatabaseSync(resolve(root, "user-profile.sqlite"));
  corrupt.prepare("UPDATE profile_state SET digest=?").run("0".repeat(64)); corrupt.close();
  assert.throws(() => new ProfileRepository(root, "user-1", credential, now), /PROFILE_DIGEST_INVALID/);
  console.log("Stage3 exclusive profile owner, learning scopes, exceptions, deletion/send/commit order, physical removal and reopen passed (fixtures only)");
} finally { await repository?.close(); if (typeof global.gc === "function") global.gc(); await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); }
