import assert from "node:assert/strict";
import {readFile,writeFile,mkdir,readdir} from "node:fs/promises";
import {resolve,basename} from "node:path";
import {createRequire} from "node:module";
import {pathToFileURL} from "node:url";
import {buildRealDesktop,launchRealDesktop,armExactFileSelection,armExactExport} from "../fixtures/stage3/real-electron.js";
import {armConfirmation,readConfirmationAudit,readProjectProof} from "../fixtures/stage3/real-journey.js";
import {timelineFacts,validateRenderedProof,saveRenderedReview} from "../fixtures/stage3/real-journey-continue.js";
import {digestFile} from "../fixtures/stage3/real-public-media.js";

// Opt-in real services and licensed source files. Never run as a synthetic test.
const mode=process.argv[2];assert.ok(mode==="browser"||mode==="electron");
const repository=process.cwd(),reviewRoot=resolve(process.env.AVE_REAL_REVIEW_ROOT??""),outer=resolve(process.env.AVE_P5_ROOT??""),configPath=resolve(process.env.AVE_MODEL_CONFIG??"");
assert.ok(process.env.AVE_P5_ROOT&&process.env.AVE_REAL_REVIEW_ROOT&&process.env.AVE_MODEL_CONFIG);
const config=JSON.parse(await readFile(configPath,"utf8")),attempt=resolve(outer,`${mode}-${Date.now()}`),projectName=`Mixed-${mode}`,mediaRoot=resolve(outer,"media"),paths=["coast-visitors.mp4","coast-landscape.mp4","coast-photo.png","independent-narration.wav"].map(x=>resolve(mediaRoot,x));
await mkdir(attempt,{recursive:true});
const prompt="用上传的两段真实海边视频、海边照片和独立采访录音制作一个12秒的自然观察素材演示，至少4个画面片段，两段视频与照片都要使用，照片展示2秒。录音是独立解说素材，不要暗示画面人物说这些话；使用原录音前6秒，保持内容真实，不编造或翻译对白。启用免费音频库自动选择纯音乐，声音轻一些，在独立人声下压低音乐。所有画面统一使用竖屏 contain 完整显示模式，保持真实画面，不变色。不要写AI字幕；我会手动添加一句说明。直接交付完整可播放初稿。";
const feedback="只把音乐音量再降低3dB。保留当前全部画面源范围、顺序、位置、照片时长与构图、音效、独立人声以及手动字幕的原文、时间、样式。保持12秒时长和当前手动精修，不增加曲目或重新选择素材。这只是本次作品修改。";
const report:any={warnings:[],http_failures:[],mode,started_at:new Date().toISOString(),identity:"isolated-public-media-creator",prompt,feedback,human_acceptance:"pending",operations:[],errors:[],sources:[]};
for(const path of paths)report.sources.push({file:basename(path),sha256:await digestFile(path)});
await writeFile(resolve(attempt,"frozen-journey.json"),JSON.stringify(report,null,2),{flag:"wx"});
const localRequire=createRequire(resolve(reviewRoot,"tooling/package.json")),playwright=localRequire("playwright");
const resumeRoot=process.env.AVE_P5_RESUME?resolve(process.env.AVE_P5_RESUME):null;
let app:any,browser:any,context:any,page:any,server:any,projectRoot=resumeRoot??"",entrypoint="",generated:any;
const save=async()=>writeFile(resolve(attempt,"result.json"),JSON.stringify(report,null,2));
const log=async(action:string,value:any=null)=>{report.operations.push({action,value,at:new Date().toISOString()});await save();console.log(`${mode}: ${action} ${attempt}`);};
const capture=async(name:string)=>{await page.screenshot({path:resolve(attempt,`${name}.png`)});};
const bridge=(name:string)=>page.locator("dialog.browser-dialog").filter({has:page.getByRole("heading",{name,exact:true})});
const view=async(name:string)=>{const button=page.getByRole("navigation",{name:"工作台导航"}).getByRole("button",{name,exact:true});if(await button.getAttribute("aria-pressed")!=="true")await button.click();};
const proof=()=>readProjectProof(projectRoot);
const waitDraft=async(previous:string|null,rendered:boolean)=>{const until=Date.now()+25*60*1000;while(Date.now()<until){const p=await proof(),request=p.requests.at(-1),draft=request?.drafts.find((d:any)=>d.draft_id===request.latest_draft_id);if(request?.status==="failed"){await writeFile(resolve(attempt,`failed-proof-${Date.now()}.json`),JSON.stringify(p,null,2));throw new Error(`REAL_CREATION_FAILED: ${request.authorization.request_id}; ${await page.locator('[role="status"]').innerText()}`);}if(draft&&draft.draft_id!==previous&&(!rendered||p.objects.some((o:any)=>o.object_type==="creation_render"&&o.value.draft_id===draft.draft_id))){await writeFile(resolve(attempt,`proof-v${draft.timeline_version}.json`),JSON.stringify(p,null,2));return {p,draft};}await page.waitForTimeout(1000);}throw new Error("REAL_DRAFT_TIMEOUT");};
const latest=async()=>{const p=await proof(),r=p.requests.at(-1);return {p,r,draft:r.drafts.find((d:any)=>d.draft_id===r.latest_draft_id)};};
const watch=async()=>{const {p,draft}=await latest();await view("对话");await page.locator('[data-creation-view="drafts"]').click();await page.locator(`[data-creation-draft="${draft.draft_id}"]`).click();const render=page.getByRole("button",{name:"制作预览与成片",exact:true});if(await render.isVisible()){await render.click();const until=Date.now()+120000;while(Date.now()<until){const state=await latest();if(state.p.objects.some((o:any)=>o.object_type==="creation_render"&&o.value.draft_id===state.draft.draft_id))break;if(state.r.status==="failed")throw new Error("REAL_MANUAL_RENDER_FAILED");await page.waitForTimeout(500);}}
 const current=await latest();await page.getByRole("button",{name:"观看此版",exact:true}).click();const player=page.locator(`video[aria-label="作品 v${current.draft.timeline_version} 预览"]:not([aria-hidden="true"]):visible`);await player.waitFor();assert.equal(await player.count(),1,"exactly one current preview is visible");await page.waitForFunction(()=>[...document.querySelectorAll("video")].some(v=>v.readyState>=2&&v.videoWidth>0),undefined,{timeout:60000});await player.evaluate((v:HTMLVideoElement)=>{v.currentTime=0;});await page.getByRole("button",{name:"播放作品",exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll("video")].some(v=>!v.paused&&v.currentTime>0.1));await player.evaluate((v:HTMLVideoElement)=>v.pause());return current;};
const precise=async(kind:string,target:readonly string[],fields:Record<string,string>)=>{const prior=(await latest()).draft.draft_id;await page.getByRole("navigation",{name:"工作台导航"}).getByRole("button",{name:"精修",exact:true}).click();const form=page.locator('[data-creation-form="precision"]');await form.locator('[name="kind"]').selectOption(kind);await form.locator('[name="target"]').selectOption(JSON.stringify(target));for(const [key,value]of Object.entries(fields))await form.locator(`[name="${key}"]`).fill(value);await form.locator('[name="raw_text"]').fill(`明确手动${kind}，保留其他内容。`);await form.getByRole("button",{name:"保存精修版本",exact:true}).click();const next=await waitDraft(prior,false);await watch();await log(`precision-${kind}`,{timeline_version:next.draft.timeline_version});return next;};
try{
 process.env.AVE_PROFILE_ROOT=resumeRoot?resolve(resumeRoot,mode==="browser"?"../..":"..","profile/creator-profile"):resolve(attempt,"profile/creator-profile");
 if(mode==="browser"){
  process.env.AVE_PROJECT_ROOT=resumeRoot?resolve(resumeRoot,".."):resolve(attempt,"projects");process.env.AVE_UPLOAD_ROOT=resolve(attempt,"uploads");process.env.AVE_EXPORT_ROOT=resolve(attempt,"exports");process.env.AVE_BROWSER_PORT="6091";
  entrypoint=await buildRealDesktop(repository,attempt);const {startBrowserHost}=await import(pathToFileURL(resolve(attempt,"app/apps/web/src/server.js")).href);server=await startBrowserHost(6091);
  browser=await playwright.chromium.launch({channel:"msedge",headless:true});context=await browser.newContext({recordVideo:{dir:resolve(attempt,"recordings"),size:{width:1440,height:960}},viewport:{width:1440,height:960},acceptDownloads:true});page=await context.newPage();page.on("console",(message:any)=>{if(message.type()==="error"){const item={boundary:"browser-console",message:message.text(),location:message.location()};(item.location.url.endsWith("/favicon.ico")?report.warnings:report.errors).push(item);}});page.on("pageerror",(error:Error)=>report.errors.push({boundary:"startup",message:error.message,stack:error.stack}));page.on("response",async(response:any)=>{if(response.status()>=400)report.http_failures.push({url:response.url(),status:response.status(),body:(await response.text()).slice(0,500)});});await page.goto("http://127.0.0.1:6091");
 }else{entrypoint=await buildRealDesktop(repository,attempt);app=await launchRealDesktop(repository,reviewRoot,attempt,entrypoint,resolve(attempt,"test-user-data"),configPath);page=await app.firstWindow();await page.waitForURL("app://renderer/index.html");}
 page.on("pageerror",(error:Error)=>report.errors.push({message:error.message,stack:error.stack}));await capture("01-empty");
 if(resumeRoot){
  if(mode==="electron")await armExactFileSelection(app,["openDirectory"],[projectRoot]);
  await page.getByRole("button",{name:"打开作品",exact:true}).click();
  if(mode==="browser"){const open=bridge("打开作品");await open.getByLabel("选择作品").selectOption({label:basename(projectRoot)});await open.getByRole("button",{name:"确定",exact:true}).click();}
  const p=await proof(),request=p.requests.at(-1),first=request.drafts.find((d:any)=>d.source.kind==="model");assert.ok(first&&request.drafts.length>=2&&request.revisions.length>=1&&request.latest_draft_id===request.drafts.at(-1).draft_id,"resume only the retained first gain edit, without replacing its actual original generation");
  assert.ok(p.objects.some((o:any)=>o.object_type==="creation_render"&&o.value.draft_id===first.draft_id));generated={p,draft:first};report.resume={projectRoot,authorization:request.authorization,first_draft:first.draft_id,retained_manual:request.latest_draft_id};await log("normal-open-retained-real-first-generation");
 }else{
 if(mode==="electron"){projectRoot=resolve(attempt,"project");await mkdir(projectRoot);await armExactFileSelection(app,["openDirectory","createDirectory"],[projectRoot]);}
 await page.getByRole("button",{name:"新建作品",exact:true}).click();
 if(mode==="browser"){const dialog=bridge("新建作品");await dialog.getByLabel("作品名称").fill(projectName);await dialog.getByRole("button",{name:"确定",exact:true}).click();await dialog.waitFor({state:"detached"});const dirs=await readdir(resolve(attempt,"projects"));assert.equal(dirs.length,1);projectRoot=resolve(attempt,"projects",dirs[0]!);}

 await log("project-created",{projectRoot});await view("素材");if(mode==="electron")await armExactFileSelection(app,["openFile","multiSelections"],paths,true);await page.getByRole("button",{name:"导入素材",exact:true}).click();
 if(mode==="browser"){const dialog=bridge("上传素材");await dialog.getByLabel("选择本机素材文件").setInputFiles(paths);await dialog.getByRole("button",{name:"上传并导入",exact:true}).click();await dialog.waitFor({state:"detached",timeout:120000});}
 for(const path of paths)await page.getByRole("button",{name:new RegExp(basename(path).replaceAll(".","\\."))}).waitFor({timeout:120000});await capture("02-imported");await log("mixed-imported");
 await view("对话");const begin=page.locator('[data-creation-form="begin"]');await begin.locator('[name="original_text"]').fill(prompt);await begin.locator("summary").click();await begin.getByRole("button",{name:"选择全部已导入素材"}).click();const allowed=["request","timeline","evidence","frames","audio","transcript"];for(const name of allowed)await begin.locator(`[name="${name}"]`).check();await begin.locator('[name="audio_library"]').check();
 if(mode==="electron"){
  const assets=await begin.locator('[name="asset_ids"]').evaluate((select:HTMLSelectElement)=>[...select.selectedOptions].map(o=>o.value)),provider=await begin.locator('[name="provider"]').inputValue(),model=await begin.locator('[name="model"]').inputValue(),expires=new Date(await begin.locator('[name="expires_at"]').inputValue()).toISOString(),manifest=JSON.parse(await readFile(resolve(projectRoot,"project.json"),"utf8")),pack=JSON.parse(await readFile(resolve(repository,"resources/audio/free-audio-2026.10.02.1.json"),"utf8")),endpoint=(url:string)=>new URL(url).href.replace(/\/$/,"");
  const routes=["vision","transcription","sound","planner"].map(role=>`${role}: ${config[role].provider} / ${config[role].model} → ${endpoint(config[role].base_url)}`);
  const detail=[`项目：${manifest.project_id} · 当前版本 v0`,`要求原文：\n${prompt}`,`授权素材：\n${assets.join("\n")}`,`免费音频库：${pack.pack_id} / ${pack.pack_version}\n允许规划模型从本版目录选择音乐，下载精确选中资源并自动安排配乐；音效仅手动或明确请求插入。只保存实际选中音频；未使用试听可清理。`,`模型服务：${provider} / ${model}`,`接收端：${endpoint(config.planner.base_url)}`,"可发送的数据：本次要求、当前作品与时间线、素材观察与证据、素材抽帧、素材音频、转写",`分工接收端：\n${routes.join("\n")}`,"不得改变：未指定保护对象",`有效期：${expires}`,"本次授权包含范围内的素材分析和创作修改；扩大范围需重新授权。"].join("\n\n");
  await armConfirmation(app,{type:"warning",title:"AVE 创作请求授权",message:"确认素材、数据范围与模型服务",detail,buttons:["取消","授权本次创作"],defaultId:0,cancelId:0,noLink:true});report.authorization=detail;
 }
 await begin.getByRole("button",{name:"授权并开始制作",exact:true}).click();if(mode==="browser"){const dialog=bridge("AVE 创作请求授权");const detail=await dialog.locator("pre").innerText();assert.ok(detail.includes("2026.10.02.1")&&detail.includes("允许规划模型"));report.authorization=detail;await capture("03-authorization");await dialog.getByRole("button",{name:"授权本次创作",exact:true}).click();}
 if(mode==="electron")report.native_authorizations=await readConfirmationAudit(app);
 await capture("04-producing");generated=await waitDraft(null,true);
 }
 const facts=timelineFacts(generated.p,generated.draft.draft_id);assert.ok(facts.video.some((c:any)=>c.kind==="image"));assert.ok(facts.video.filter((c:any)=>c.kind!=="image").length>=2);const spoken=facts.timeline.tracks.filter((t:any)=>["audio-narration","audio-dialogue"].includes(t.track_id)).flatMap((t:any)=>t.clips);const voiceAsset=`asset:sha256:${report.sources.find((s:any)=>s.file==="independent-narration.wav").sha256}`;assert.ok(spoken.some((c:any)=>c.source.asset_id===voiceAsset),"the actual independent recording must be audible on a spoken-voice bus");const musicTrack=facts.timeline.tracks.find((t:any)=>t.track_id==="audio-music");assert.ok(musicTrack?.clips.length);assert.equal(facts.seconds,12);const calls=generated.p.requests.at(-1).model_calls.filter((c:any)=>c.target?.role==="planner"&&c.run_id===generated.draft.source.run_id);assert.equal(calls.length,2,"exactly two real planning calls");
 await validateRenderedProof(projectRoot,generated.p,generated.draft);await saveRenderedReview(projectRoot,attempt,facts,await validateRenderedProof(projectRoot,generated.p,generated.draft));await watch();await capture("05-auto-soundtrack");await log("real-auto-mixed-watchable",{draft:generated.draft,source_map:facts.source_map,planner_calls:calls.map((c:any)=>({role:c.target.role,status:c.settlement.status}))});
 await view("素材");await page.getByRole("button",{name:/coast-photo\.png/}).click();await page.getByRole("button",{name:"预览图片",exact:true}).click();const thumb=page.getByAltText("素材缩略图",{exact:true});await thumb.waitFor();assert.ok(await thumb.evaluate((i:HTMLImageElement)=>i.naturalWidth>0));await capture("05a-photo-source-preview");
 await page.getByRole("button",{name:/independent-narration\.wav/}).click();await page.getByRole("button",{name:"预览音频",exact:true}).click();const waveform=page.getByAltText("音频波形",{exact:true});await waveform.waitFor();assert.ok(await waveform.evaluate((i:HTMLImageElement)=>i.naturalWidth>0));const audioPreview=page.locator("audio");await audioPreview.waitFor();await audioPreview.evaluate(async(a:HTMLAudioElement)=>a.play());await page.waitForFunction(()=>[...document.querySelectorAll("audio")].some(a=>!a.paused&&a.currentTime>0.1));await audioPreview.evaluate((a:HTMLAudioElement)=>a.pause());await capture("05b-independent-source-waveform");await log("actual-photo-thumbnail-and-voice-waveform-audition");
 const alreadyContinued=resumeRoot&&(await latest()).draft.source.kind==="model"&&(await latest()).draft.revision>1;
 if(!alreadyContinued){
 const photo=facts.video.find((c:any)=>c.kind==="image"),music=musicTrack.clips[0];if(!resumeRoot)await precise("gain",[musicTrack.track_id,music.clip_id],{gain_db:"-21"});else{const current=timelineFacts((await latest()).p);assert.equal(current.timeline.tracks.find((t:any)=>t.track_id===musicTrack.track_id).clips.find((c:any)=>c.clip_id===music.clip_id).gain_db,-21);await log("retained-gain-new-dual-qc-passed");}if(!resumeRoot||timelineFacts((await latest()).p).video.find((c:any)=>c.clip_id===photo.clip_id).transform?.scale_x!==1.1)await precise("transform",["video-main",photo.clip_id],{x:"0",y:"0",scale_x:"1.1",scale_y:"1.1",rotation:"0"});
 if(!timelineFacts((await latest()).p).timeline.tracks.flatMap((t:any)=>t.captions??[]).some((c:any)=>c.text==="Public source study · 海边素材练习"))await precise("caption",["video-main",photo.clip_id],{caption_text:"Public source study · 海边素材练习",at:"0",duration:"2",safe_y_ratio:"0.8"});
 if(!timelineFacts((await latest()).p).timeline.tracks.find((t:any)=>t.track_id==="audio-sfx")?.clips.length){await view("素材");const library=page.locator("details").filter({has:page.locator("summary").filter({hasText:"免费音频库"})});await library.locator("summary").click();await library.getByLabel("音频类型").selectOption("sfx");await library.getByLabel("搜索音频库").fill("bong_001");await library.getByLabel("加入位置（秒）").fill("1");await library.getByLabel("使用时长（秒）").fill("0.1");const row=library.locator("article").filter({has:page.locator('[data-audio-preview="kenney:d21d0f0b782445db"]')});await row.getByRole("button",{name:"试听前 15 秒",exact:true}).click();await row.locator("audio").waitFor({timeout:120000});await row.locator("audio").evaluate(async(a:HTMLAudioElement)=>{await a.play();});await page.waitForTimeout(250);await library.getByRole("button",{name:"停止试听",exact:true}).click();const beforeSound=(await latest()).draft.draft_id;await row.getByRole("button",{name:"加入作品",exact:true}).click();await waitDraft(beforeSound,false);await watch();await log("manual-original-site-sfx-added");await capture("06-manual-refinement");}
 if(timelineFacts((await latest()).p).timeline.tracks.find((t:any)=>t.track_id==="audio-music").clips.find((c:any)=>c.clip_id===music.clip_id).source.asset_id!=="asset:sha256:"+JSON.parse(await readFile(resolve(repository,"resources/audio/free-audio-2026.10.02.1.json"),"utf8")).items.find((i:any)=>i.resource_id==="oga:8a83b97f06cad105").content_sha256){
 await page.locator(`button[data-track-id="audio-music"][data-clip-id="${music.clip_id}"]`).click();await view("素材");const replaceLibrary=page.locator("details").filter({has:page.locator("summary").filter({hasText:"免费音频库"})});if(!await replaceLibrary.evaluate((d:HTMLDetailsElement)=>d.open))await replaceLibrary.locator("summary").click();await replaceLibrary.getByLabel("音频类型").selectOption("music");await replaceLibrary.getByLabel("搜索音频库").fill("A New Town");await replaceLibrary.getByLabel("增益 dB").fill("-21");const replacement=replaceLibrary.locator("article").filter({has:page.locator('[data-audio-preview="oga:8a83b97f06cad105"]')});const priorReplacement=(await latest()).draft.draft_id;await replacement.getByRole("button",{name:"替换所选音频",exact:true}).click();const replaced=await waitDraft(priorReplacement,false);const replacedMusic=timelineFacts(replaced.p).timeline.tracks.find((t:any)=>t.track_id==="audio-music").clips.find((c:any)=>c.clip_id===music.clip_id);assert.equal(replacedMusic.source.asset_id,"asset:sha256:"+JSON.parse(await readFile(resolve(repository,"resources/audio/free-audio-2026.10.02.1.json"),"utf8")).items.find((i:any)=>i.resource_id==="oga:8a83b97f06cad105").content_sha256);await watch();await log("manual-original-site-music-replacement",{clip_id:music.clip_id,asset_id:replacedMusic.source.asset_id});}
 const preFeedback=await latest();const revise=page.locator('[data-creation-form="revise"]');await view("对话");await page.locator('[data-creation-view="request"]').click();await revise.locator('[name="raw_text"]').fill(feedback);const protection=revise.locator("details.composer-settings");if(!await protection.evaluate((d:HTMLDetailsElement)=>d.open))await protection.locator("summary").click();await revise.locator('[name="preserve_refs"]').selectOption([photo.clip_id]);await revise.getByRole("button",{name:"提交并继续制作",exact:true}).click();const corrected=await waitDraft(preFeedback.draft.draft_id,true);await watch();const finalFacts=timelineFacts(corrected.p);assert.equal(finalFacts.seconds,12);assert.ok(finalFacts.timeline.tracks.find((t:any)=>t.track_id==="audio-sfx")?.clips.length);assert.ok(finalFacts.timeline.tracks.flatMap((t:any)=>t.captions??[]).some((c:any)=>c.text==="Public source study · 海边素材练习"));await capture("07-language-continued");await log("manual-then-real-language-continuation",{draft:corrected.draft});}
 else{const retained=await latest();assert.equal(retained.r.revisions.at(-1).raw_text,feedback);const calls=retained.r.model_calls.filter((c:any)=>c.run_id===retained.draft.source.run_id&&c.target?.role==="planner");assert.equal(calls.length,2);assert.ok(calls.every((c:any)=>c.settlement.status==="response"));const facts=timelineFacts(retained.p);assert.equal(facts.seconds,12);assert.ok(facts.timeline.tracks.find((t:any)=>t.track_id==="audio-sfx")?.clips.length);assert.ok(facts.timeline.tracks.flatMap((t:any)=>t.captions??[]).some((c:any)=>c.text==="Public source study · 海边素材练习"));await watch();await capture("07-language-continued");await log("retained-real-language-continuation",{draft:retained.draft,planner_calls:calls.length});}
 const exported=await latest(),receipt=await validateRenderedProof(projectRoot,exported.p,exported.draft),downloads:any[]=[];const downloadJobs:Promise<void>[]=[];
 if(mode==="browser")page.on("download",(download:any)=>{const target=resolve(attempt,download.suggestedFilename());downloadJobs.push(download.saveAs(target).then(async()=>{downloads.push({file:basename(target),sha256:await digestFile(target)});}));});
 const nativeExport=resolve(attempt,`AVE-v${exported.draft.timeline_version}.mp4`);if(mode==="electron")await armExactExport(app,{title:"导出所选作品",defaultPath:`AVE-v${exported.draft.timeline_version}.mp4`,filters:[{name:"MP4 视频",extensions:["mp4"]}]},nativeExport);
 await page.getByRole("button",{name:"导出所选作品",exact:true}).click();const overlay=page.getByRole("dialog",{name:"导出作品",exact:true});await overlay.getByRole("button",{name:mode==="browser"?"下载成片":"选择位置并导出",exact:true}).click();
 if(mode==="browser"){const saveDialog=bridge("下载作品");await saveDialog.getByRole("button",{name:"下载成片",exact:true}).click();}
 await overlay.getByText("导出操作已完成。",{exact:true}).waitFor({timeout:120000});await page.waitForTimeout(1000);await Promise.all(downloadJobs);
 if(mode==="electron")for(const file of [nativeExport,nativeExport+".audio.json",nativeExport+".credits.txt"])downloads.push({file:basename(file),sha256:await digestFile(file)});
 assert.equal(downloads.length,3);assert.equal(downloads.find(d=>d.file.endsWith(".mp4")).sha256,receipt.master.output_hash);report.exports=downloads;await overlay.getByRole("button",{name:"关闭导出",exact:true}).click();await log("master-and-credits-exported",downloads);
 await view("素材");const cache=page.locator("details").filter({has:page.locator("summary").filter({hasText:"免费音频库"})});if(!await cache.evaluate((d:HTMLDetailsElement)=>d.open))await cache.locator("summary").click();await cache.getByRole("button",{name:"清理未使用的试听缓存",exact:true}).click();await cache.locator("p").filter({hasText:/^已清理 .* 个缓存/}).waitFor();await log("unused-audition-cache-cleared");
 // Reopen through the normal product entry, then reject all Host network fetches.
 if(mode==="browser"){const closingServer=server;server=undefined;await closingServer.close();await context.close();context=undefined;const {startBrowserHost}=await import(pathToFileURL(resolve(attempt,"app/apps/web/src/server.js")).href);server=await startBrowserHost(6091);context=await browser.newContext({recordVideo:{dir:resolve(attempt,"recordings"),size:{width:1440,height:960}},viewport:{width:1440,height:960},acceptDownloads:true});page=await context.newPage();await page.goto("http://127.0.0.1:6091");}
 else{await app.close();app=await launchRealDesktop(repository,reviewRoot,attempt,entrypoint,resolve(attempt,"test-user-data"),configPath);page=await app.firstWindow();await page.waitForURL("app://renderer/index.html");await armExactFileSelection(app,["openDirectory"],[projectRoot]);}
 page.on("pageerror",(error:Error)=>report.errors.push({message:error.message,stack:error.stack}));await page.getByRole("button",{name:"打开作品",exact:true}).click();
 if(mode==="browser"){const open=bridge("打开作品");await open.getByLabel("选择作品").selectOption({label:basename(projectRoot)});await open.getByRole("button",{name:"确定",exact:true}).click();}await watch();await capture("08-reopened");
 const beforeOffline=await proof(),jobsBefore=beforeOffline.jobs.length,originalFetch=globalThis.fetch;let networkAttempts=0;
 if(mode==="browser")globalThis.fetch=async()=>{networkAttempts++;throw new Error("P5_OFFLINE_NETWORK_DENIED");};else assert.deepEqual(await app.evaluate(()=>{const scope=globalThis as any;scope.__p5Fetch=globalThis.fetch;scope.__p5NetworkAttempts=0;globalThis.fetch=async()=>{scope.__p5NetworkAttempts++;process.stdout.write("AVE_P5_OFFLINE_FETCH_DENIED\n");throw new Error("P5_OFFLINE_NETWORK_DENIED");};return {installed:true};}),{installed:true},"native network deny must be installed before offline encoding");
 try{const r=await page.evaluate(async({projectId,requestId,draftId}:any)=>{return (window as any).projectApi.command({api_version:1,command_type:"project.creation.render",command_id:crypto.randomUUID(),idempotency_key:crypto.randomUUID(),project_id:projectId,payload:{request_id:requestId,draft_id:draftId,operation_id:`p5-offline:${crypto.randomUUID()}`}});},{projectId:beforeOffline.requests.at(-1).project_id,requestId:beforeOffline.requests.at(-1).authorization.request_id,draftId:exported.draft.draft_id});assert.equal(r.ok,true,JSON.stringify(r.error));}finally{if(mode==="browser")globalThis.fetch=originalFetch;else networkAttempts=(await readFile(resolve(attempt,"electron-stdout.log"),"utf8")).split("AVE_P5_OFFLINE_FETCH_DENIED").length-1;}
 const offline=await proof();assert.ok(offline.jobs.length>jobsBefore,"new offline encode jobs, not a saved receipt replay");assert.equal(networkAttempts,0);const offlineReceipt=await validateRenderedProof(projectRoot,offline,exported.draft);assert.equal(offlineReceipt.semantic_graph_hash,receipt.semantic_graph_hash);await writeFile(resolve(attempt,"offline-proof.json"),JSON.stringify(offline,null,2));await capture("09-offline-reencoded");await log("offline-new-dual-render",{new_jobs:offline.jobs.length-jobsBefore,networkAttempts,render_id:offlineReceipt.render_id});
 assert.deepEqual(report.errors,[]);report.result=`real-${mode}-mixed-journey-passed-human-pending`;
}catch(error){report.result="failed";report.failure={message:String(error),stack:error instanceof Error?error.stack:null};if(page){report.playback_failure=await page.evaluate(()=>({notice:document.querySelector(".notice")?.textContent,players:[...document.querySelectorAll("video")].map(v=>({label:v.getAttribute("aria-label"),time:v.currentTime,duration:v.duration,paused:v.paused,ready:v.readyState,hidden:v.hidden,ended:v.ended,error:v.error?.message})),control:document.querySelector('[aria-label="播放作品"], [aria-label="暂停作品"]')?.outerHTML})).catch(()=>null);await save();}if(page)await capture("failure").catch(e=>report.errors.push({message:String(e)}));throw error;
}finally{if(app)await app.close();if(server){const closingServer=server;server=undefined;await closingServer.close();}if(context)await context.close();if(browser)await browser.close();if(projectRoot)await writeFile(resolve(attempt,"closed-project-proof.json"),JSON.stringify(await proof(),null,2));report.finished_at=new Date().toISOString();await save();console.log(`P5_REAL_EVIDENCE=${attempt}`);}
