import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { ProjectHostSession } from "../../packages/platform/project-host/src/public.js";
import { registerMediaAsset } from "../../packages/platform/project-storage/src/public.js";
import { ProfileError, ProfileRepository } from "../../packages/platform/user-profile-store/src/public.js";
import { compileCreationPlan, type CreationCompileContext } from "../../packages/core/edit-ir/src/public.js";
import type { CreationState, CreationTicket } from "../../packages/platform/project-host/src/stage3-request.js";
import type { Timeline } from "../../packages/core/timeline-core/src/public.js";

// Controlled plans exercise the actual compiler/Host/SQLite seams. No model or real-media claim.
const root = await mkdtemp(resolve(tmpdir(), "ave-stage3-creation-"));
const credential = {}, now = () => Date.parse("2026-09-18T01:00:00Z");
const options = { now, creationRequestChannels: [{ credential, actor_id: "user-1" }] };
let host: ProjectHostSession | undefined, profile: ProfileRepository | undefined;
const time = (value: number, timescale = 30) => ({ schema_version: 1 as const, value, timescale });
try {
  profile = new ProfileRepository(resolve(root, "profile"), "user-1", credential, now);
  await profile.configure(credential, { source_project_ids: ["history"], data_types: ["feedback"], retention_until: "2027-01-01T00:00:00Z", external_provider: null, enabled: true });
  host = new ProjectHostSession(options); await host.create(resolve(root, "project"));
  host.initializeTimeline([], { sequence_id: "main", timebase: { value: 1n, timescale: 30n }, tracks: [] });
  const fixture = JSON.parse(readFileSync("contracts/examples/valid/editorial/creation-session.v1.json", "utf8")) as CreationState;
  const plan = JSON.parse(readFileSync("contracts/examples/valid/editorial/creation-plan.v1.json", "utf8"));
  const { actor_id: _actor, project_id: _project, deployment: _deployment, ...input } = fixture.authorization;
  const asset = `asset:sha256:${"a".repeat(64)}`;
  input.asset_ids = [asset];
  const session = (host as any).session;
  registerMediaAsset(session, session.manifest.project_id, { asset_id: asset, algorithm: "sha256", digest: "a".repeat(64), byte_length: 100, stream_facts: {} });
  host.beginCreationRequest(credential, input);
  plan.request_id = input.request_id; plan.shots[0].source.asset_id = asset;
  plan.shots.push({ ...structuredClone(plan.shots[0]), shot_id: "reaction", source: { ...plan.shots[0].source, start: time(90), end: time(180) } });
  plan.captions = [{ caption_id: "opening-caption", shot_id: "shot-1", offset: time(0), duration: time(30), text: "actual opening", kind: "verbatim", evidence_ids: ["opening-quote"], audio_anchor: { kind: "embedded", id: "shot-1" } }, { caption_id: "reaction-caption", shot_id: "reaction", offset: time(0), duration: time(30), text: "actual reaction", kind: "verbatim", evidence_ids: ["reaction-quote"], audio_anchor: { kind: "embedded", id: "reaction" } }];
  plan.audio = [{ audio_id: "sound", shot_id: "reaction", source: { ...plan.shots[0].source, start: time(60), end: time(150) }, offset: time(-30), role: "dialogue", gain_db: -3, fade_in: time(0), fade_out: time(0), purpose: "source sound follows reaction" }];
  const spans: CreationCompileContext["spans"] = [{ span_id: "evidence-1", asset_id: asset as any, start_pts: 0n, end_pts: 240n, timescale: 30n, has_video: true, has_audio: true, observations: [{ evidence_id: "visual", kind: "visual", start_pts: 0n, end_pts: 240n, timescale: 30n, text: "Fixture picture", uncertain: false }, { evidence_id: "audio", kind: "audio", start_pts: 0n, end_pts: 240n, timescale: 30n, text: "Fixture sound", uncertain: false }, { evidence_id: "opening-quote", kind: "transcript", start_pts: 0n, end_pts: 30n, timescale: 30n, text: "actual opening", uncertain: false }, { evidence_id: "reaction-quote", kind: "transcript", start_pts: 90n, end_pts: 120n, timescale: 30n, text: "actual reaction", uncertain: false }] }];
  const query = { project_id: session.manifest.project_id, contexts: ["daily"], except_principle_ids: [] };
  const snapshot = await profile.snapshot(query);
  const identity = { profile_id: snapshot.profile_id, version: snapshot.version, consent_generation: snapshot.consent_generation, deletion_generation: snapshot.deletion_generation, digest: snapshot.digest };
  const prepare = (digest: string) => (host as any).prepareCreationRun(input.request_id, digest, identity) as CreationTicket;
  const compile = (ticket: CreationTicket) => {
    plan.revision = ticket.revision; plan.base_timeline_version = ticket.base_timeline_version; plan.input_digest = ticket.input_digest;
    return compileCreationPlan(plan, host!.readTimelineSnapshot() as Timeline, { request_id: input.request_id, revision: ticket.revision, input_digest: ticket.input_digest, authorized_asset_ids: [asset], protected_refs: plan.preserve_refs, principle_ids: [], spans });
  };
  let ticket = prepare("1".repeat(64));
  await profile.withSnapshot(snapshot, () => (host as any).commitCreationEdit(ticket, compile(ticket), identity));
  const first = host.readTimelineSnapshot() as Timeline;
  assert.equal(first.version, 1); assert.equal(first.tracks.find(t => t.kind === "audio")!.clips[0].boundary_fades, undefined);
  host.reviseCreationRequest(credential, input.request_id, 1, { raw_text: "Tighten the opening, keep reaction and its caption unchanged.", viewed_timeline_version: 1, preserve_refs: ["reaction", "reaction-caption"] });
  plan.preserve_refs = ["reaction", "reaction-caption"]; plan.shots[0].source.end = time(45);
  ticket = prepare("2".repeat(64));
  await profile.withSnapshot(snapshot, () => (host as any).commitCreationEdit(ticket, compile(ticket), identity));
  const second = host.readTimelineSnapshot() as Timeline, video = second.tracks.find(t => t.kind === "video")!;
  assert.equal(video.clips[1].timeline_start, 45n); assert.equal(video.captions![1].timeline_start, 45n);
  assert.deepEqual(video.clips[1].source, first.tracks.find(t => t.kind === "video")!.clips[1].source);
  assert.equal(second.tracks.find(t => t.kind === "audio")!.clips[0].timeline_start, 15n);
  host.applyTimelineCommand({ type: "lock_range", track_id: "video-main", lock: { lock_id: "ending-lock", start: 75n, end: 135n, owner: "user" } } as any, 2);
  host.reviseCreationRequest(credential, input.request_id, 2, { raw_text: "Change only opening caption, keep locked ending.", viewed_timeline_version: 3, preserve_refs: plan.preserve_refs });
  plan.captions[0].text = "opening"; plan.captions[0].kind = "editorial"; plan.captions[0].audio_anchor = null;
  ticket = prepare("3".repeat(64));
  await profile.withSnapshot(snapshot, () => (host as any).commitCreationEdit(ticket, compile(ticket), identity));
  assert.equal((host.readTimelineSnapshot() as Timeline).version, 4, "unrelated locked ending does not block local caption edit");
  host.reviseCreationRequest(credential, input.request_id, 3, { raw_text: "A new draft after source deletion must be denied.", viewed_timeline_version: 4, preserve_refs: plan.preserve_refs });
  ticket = prepare("4".repeat(64));
  const before = JSON.stringify(session.db.prepare("SELECT * FROM project_events").all());
  await profile.forgetSources(credential, ["history"]);
  await assert.rejects(profile.withSnapshot(snapshot, () => (host as any).commitCreationEdit(ticket, compile(ticket), identity)), error => error instanceof ProfileError && error.code === "PROFILE_SNAPSHOT_STALE");
  assert.equal(JSON.stringify(session.db.prepare("SELECT * FROM project_events").all()), before);
  const draftState = host.readCreationRequest(input.request_id);
  assert.equal(draftState.drafts.length, 3); assert.equal(draftState.adopted_draft_id, null);
  await host.close(); host = new ProjectHostSession(options); await host.open(resolve(root, "project"));
  assert.deepEqual((host.readTimelineSnapshot() as Timeline).sequence!.timebase, { value: 1n, timescale: 30n });
  assert.equal(host.readCreationRequest(input.request_id).status, "paused");
  assert.equal(host.readCreationRequest(input.request_id).drafts.length, 3);
  console.log("Stage3 compiler → Host IR → atomic drafts/profile deletion/reopen passed (controlled fixtures; no real model/media)");
} finally { await host?.close(); await profile?.close(); if (typeof global.gc === "function") global.gc(); await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); }
