import type { AssetId } from "../../../core/media-identity/src/public.js";
import type { Clip, Timeline, Track } from "../../../core/timeline-core/src/public.js";

export type AdapterIssue = Readonly<{ code: string; message: string; id?: string }>;
export type OtioDocument = Readonly<{ format: "otio"; schema_version: 1; tracks: readonly unknown[]; semantic_sidecar: unknown; issues: readonly AdapterIssue[] }>;
const encode = (value: unknown): unknown => JSON.parse(JSON.stringify(value, (_key, item) => typeof item === "bigint" ? `${item}n` : item));
const decode = (value: unknown): unknown => typeof value === "string" && /^-?\d+n$/.test(value) ? BigInt(value.slice(0, -1)) : Array.isArray(value) ? value.map(decode) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, item]) => [key, decode(item)])) : value;
function issuesFor(timeline: Timeline): AdapterIssue[] { const issues: AdapterIssue[] = []; for (const track of timeline.tracks) { for (const clip of track.clips) { if (clip.effects?.length) issues.push({ code: "UNSUPPORTED_EFFECT", message: "OTIO sidecar cannot execute custom effects", id: clip.clip_id }); if (clip.keyframes?.length) issues.push({ code: "UNSUPPORTED_KEYFRAME", message: "OTIO sidecar cannot execute keyframes", id: clip.clip_id }); } } return issues; }
export function exportOtio(timeline: Timeline): OtioDocument { return { format: "otio", schema_version: 1, tracks: timeline.tracks.map((track) => ({ track_id: track.track_id, kind: track.kind, clips: track.clips.map((clip) => ({ clip_id: clip.clip_id, asset_id: clip.source.asset_id, source_start_pts: clip.source.start_pts, source_end_pts: clip.source.end_pts, source_timescale: clip.source.timescale, timeline_start: clip.timeline_start, timeline_duration: clip.timeline_duration, semantic_sidecar: clip.semantic_sidecar ?? null })) })), semantic_sidecar: encode(timeline.semantic_sidecar ?? null), issues: issuesFor(timeline) }; }
export function importOtio(document: OtioDocument): Timeline { if (document.format !== "otio" || document.schema_version !== 1) throw new Error("unsupported OTIO document"); const tracks = (document.tracks as Array<any>).map((track): Track => ({ track_id: track.track_id, kind: track.kind, clips: (track.clips ?? []).map((clip: any): Clip => ({ clip_id: clip.clip_id, source: { asset_id: clip.asset_id as AssetId, start_pts: BigInt(clip.source_start_pts), end_pts: BigInt(clip.source_end_pts), timescale: BigInt(clip.source_timescale) }, timeline_start: BigInt(clip.timeline_start), timeline_duration: BigInt(clip.timeline_duration), semantic_sidecar: decode(clip.semantic_sidecar) as any })) })); return { version: 0, tracks, semantic_sidecar: decode(document.semantic_sidecar) as any }; }
export function validateOtioRoundtrip(original: Timeline, imported: Timeline): readonly AdapterIssue[] { const issues: AdapterIssue[] = []; if (original.tracks.length !== imported.tracks.length) issues.push({ code: "TRACK_COUNT", message: "OTIO roundtrip changed track count" }); for (const [index, track] of original.tracks.entries()) { const candidate = imported.tracks[index]; if (!candidate || candidate.track_id !== track.track_id || candidate.kind !== track.kind) issues.push({ code: "TRACK_MISMATCH", message: `OTIO roundtrip changed track ${track.track_id}`, id: track.track_id }); if (candidate?.clips.length !== track.clips.length) issues.push({ code: "CLIP_COUNT", message: `OTIO roundtrip changed clips on ${track.track_id}`, id: track.track_id }); } return issues; }
