import type { Timeline } from "../../../core/timeline-core/src/public.js";

export type PreviewDocument = Readonly<{ format: "ave-web-preview"; schema_version: 1; timeline: unknown; semantic_sidecar: unknown }>;
export type AdapterIssue = Readonly<{ code: string; message: string; id?: string }>;
const encode = (value: unknown): unknown => JSON.parse(JSON.stringify(value, (_key, item) => typeof item === "bigint" ? `${item}n` : item));
export function exportWebPreview(timeline: Timeline): PreviewDocument { return { format: "ave-web-preview", schema_version: 1, timeline: encode(timeline), semantic_sidecar: encode(timeline.semantic_sidecar ?? null) }; }
export function validateWebPreview(document: PreviewDocument): readonly AdapterIssue[] { return document.format !== "ave-web-preview" || document.schema_version !== 1 || !document.timeline ? [{ code: "INVALID_DOCUMENT", message: "web preview document is invalid" }] : []; }
export function validateTimelineRoundtrip(original: Timeline, imported: Timeline): readonly AdapterIssue[] { const issues: AdapterIssue[] = []; if (original.tracks.length !== imported.tracks.length) issues.push({ code: "TRACK_COUNT", message: "roundtrip changed track count" }); for (const [index, track] of original.tracks.entries()) { const candidate = imported.tracks[index]; if (!candidate || candidate.track_id !== track.track_id || candidate.kind !== track.kind) issues.push({ code: "TRACK_MISMATCH", message: `roundtrip changed track ${track.track_id}`, id: track.track_id }); if (candidate?.clips.length !== track.clips.length) issues.push({ code: "CLIP_COUNT", message: `roundtrip changed clips on ${track.track_id}`, id: track.track_id }); for (const [clipIndex, clip] of track.clips.entries()) { const output = candidate?.clips[clipIndex]; if (!output || output.clip_id !== clip.clip_id || output.source.asset_id !== clip.source.asset_id || output.source.start_pts !== clip.source.start_pts || output.source.end_pts !== clip.source.end_pts || output.source.timescale !== clip.source.timescale || output.timeline_start !== clip.timeline_start || output.timeline_duration !== clip.timeline_duration) issues.push({ code: "CLIP_MISMATCH", message: `roundtrip changed clip ${clip.clip_id}`, id: clip.clip_id }); } } return issues; }
export function previewDocumentPayload(document: PreviewDocument): string { return JSON.stringify(document); }
