import { command, query, subscribe } from "../api/project-api.js";
import { projectPanel } from "../features/project-panel.js";
import { timelinePanel } from "../features/timeline-panel.js";
import { mediaPanel } from "../features/media-panel.js";
import { jobsPanel } from "../features/jobs-panel.js";
import { editorialPanel } from "../features/editorial-panel.js";
import { playerPanel } from "../features/player-panel.js";
import { diffPanel } from "../features/diff-panel.js";
import { prepareStage2ContractDraft, prepareStage2FeedbackRequest, stage2Workspace } from "../features/stage2-workspace.js";
import { createWorkbenchState, setState } from "../state/workbench-state.js";
import { statusCard } from "../components/status-card.js";

export function mountWorkbench(root) {
  const state = createWorkbenchState();
  const selectedClip = () => state.timeline?.tracks?.flatMap((track) => track.clips ?? []).find((clip) => clip.clip_id) ?? null;
  const selectedMedia = () => state.media.find((item) => item.asset_id === state.selectedAssetId) ?? state.media[0] ?? null;
  const mediaRange = (item) => { const streams = item?.metadata?.probe?.timing?.streams ?? {}; const video = Object.values(streams).find((stream) => stream?.time_base && stream?.duration_ts); if (!video) throw new Error("素材缺少可用于 Timeline 的视频时间基"); const match = String(video.time_base).match(/^(\d+)\/(\d+)$/); if (!match) throw new Error("素材时间基格式无效"); return { start_pts: 0n, end_pts: BigInt(video.duration_ts), timescale: BigInt(match[2]) }; };
  const clearLoadedPreview = () => { if (state.previewUrl) URL.revokeObjectURL(state.previewUrl); state.previewUrl = ""; state.stage2Preview = null; };
  const refresh = async () => {
    const previousProjectId = state.status.project === "not-open" ? "" : state.status.project;
    const previousTimelineVersion = state.timeline?.version ?? null;
    const status = await query("app.status");
    if (status.ok) {
      const projectId = status.data.project === "not-open" ? "" : status.data.project;
      if (projectId !== previousProjectId) { clearLoadedPreview(); Object.assign(state, { timeline: null, timelineDiff: null, media: [], jobs: [], storyPlans: [], reviewArtifacts: [], deliveryRecords: [], exports: [], modelRuns: [], qcIssues: [], storyCandidate: null, renderLatest: null, renderResults: [], stage2Workspace: null, selectedDirectionId: "", selectedStoryId: "", selectedAssetId: "" }); }
      setState(state, { status: status.data, notice: "" });
      const results = await Promise.all(["project.timeline.current", "project.timeline.diff", "project.media.list", "project.jobs.list", "project.story.list", "project.review.list", "project.delivery.list", "project.export.list", "project.model.runs", "project.qc.issues", "project.render.latest", "project.render.results", "project.stage2.workspace"].map((type) => query(type, projectId)));
      const [timeline, timelineDiff, media, jobs, storyPlans, reviewArtifacts, deliveryRecords, exports, modelRuns, qcIssues, renderLatest, renderResults, stage2] = results;
      if (timeline.ok) { if (previousProjectId === projectId && previousTimelineVersion !== null && timeline.data?.version !== previousTimelineVersion) clearLoadedPreview(); state.timeline = timeline.data; }
      if (timelineDiff.ok) state.timelineDiff = timelineDiff.data; if (media.ok) state.media = media.data; if (jobs.ok) state.jobs = jobs.data; if (storyPlans.ok) state.storyPlans = storyPlans.data; if (reviewArtifacts.ok) state.reviewArtifacts = reviewArtifacts.data; if (deliveryRecords.ok) state.deliveryRecords = deliveryRecords.data; if (exports.ok) state.exports = exports.data; if (modelRuns.ok) state.modelRuns = modelRuns.data; if (qcIssues.ok) state.qcIssues = qcIssues.data; if (renderLatest.ok) state.renderLatest = renderLatest.data; if (renderResults.ok) state.renderResults = renderResults.data;
      if (stage2.ok) { state.stage2Workspace = stage2.data; if (state.stage2Preview && state.stage2Preview.base_timeline_version !== stage2.data.timeline?.version) state.stage2Preview = null; } else if (projectId) state.notice = stage2.error.message;
    } else setState(state, { notice: status.error.message });
    render();
  };
  const run = async (operation) => { setState(state, { busy: true, notice: "正在同步 Project Host…" }); render(); try { const result = await operation(); if (!result.ok) throw new Error(result.error.message); await refresh(); } catch (error) { setState(state, { notice: error instanceof Error ? error.message : String(error) }); render(); } finally { setState(state, { busy: false }); render(); } };
  const actions = {
    create: () => run(() => command("project.create")), open: () => run(() => command("project.open")), close: () => run(() => command("project.close", state.status.project)), importMedia: () => run(() => command("project.media.import", state.status.project)), selectAsset: (assetId) => { state.selectedAssetId = assetId; render(); },
    refresh: () => run(refresh), initialize: () => run(() => command("project.timeline.initialize", state.status.project, { tracks: [{ track_id: "video-main", kind: "video", clips: [] }] }, 0)),
    add: () => run(() => { const item = selectedMedia(); if (!item) throw new Error("请先导入素材"); const source = mediaRange(item); const clip = { clip_id: `clip-${crypto.randomUUID()}`, source: { asset_id: item.asset_id, ...source }, timeline_start: 0n, timeline_duration: source.end_pts - source.start_pts, media_kind: "video" }; return command("project.timeline.command", state.status.project, { command: { type: "add_clip", track_id: "video-main", clip }, base_version: state.timeline.version }, state.timeline.version); }),
    move: () => run(() => { const clip = selectedClip(); if (!clip) throw new Error("请先添加片段"); const value = window.prompt("新的时间线起点（整数 PTS）", String(clip.timeline_start)); if (value === null) return { ok: true, data: null }; return command("project.timeline.command", state.status.project, { command: { type: "move_clip", track_id: "video-main", clip_id: clip.clip_id, timeline_start: BigInt(value) }, base_version: state.timeline.version }, state.timeline.version); }),
    trim: () => run(() => { const clip = selectedClip(); if (!clip) throw new Error("请先添加片段"); const value = window.prompt("新的源结束 PTS", String(clip.source.end_pts)); if (value === null) return { ok: true, data: null }; return command("project.timeline.command", state.status.project, { command: { type: "trim_source", track_id: "video-main", clip_id: clip.clip_id, source: { ...clip.source, end_pts: BigInt(value) } }, base_version: state.timeline.version }, state.timeline.version); }),
    undo: () => run(() => command("project.timeline.undo", state.status.project)), redo: () => run(() => command("project.timeline.redo", state.status.project)),
    loadPreview: async () => { const workspace = state.stage2Workspace, stage2Authority = Boolean(workspace?.contract || workspace?.executions?.length || workspace?.intents?.length), binding = stage2Authority ? workspace?.review?.render : null; if (stage2Authority && binding?.binding_status !== "current") { clearLoadedPreview(); setState(state, { notice: "当前 Preview 已过期，请重新执行与渲染。" }); render(); return; } const result = stage2Authority ? await query("project.stage2.preview.current", state.status.project, { workspace_digest: workspace.workspace_digest }) : await query("project.preview.latest", state.status.project); if (!result.ok) { clearLoadedPreview(); setState(state, { notice: result.error.message }); render(); return; } if (!result.data) { clearLoadedPreview(); setState(state, { notice: "暂无 Preview" }); render(); return; } if (stage2Authority && (result.data.workspace_digest !== state.stage2Workspace?.workspace_digest || result.data.timeline_version !== state.stage2Workspace?.timeline?.version)) { clearLoadedPreview(); setState(state, { notice: "Preview 绑定的工作区已变化。" }); render(); return; } if (state.previewUrl) URL.revokeObjectURL(state.previewUrl); const bytes = result.data.bytes instanceof Uint8Array ? result.data.bytes : new Uint8Array(result.data.bytes); setState(state, { previewUrl: URL.createObjectURL(new Blob([bytes], { type: result.data.mime })) }); render(); },
    story: (value) => run(() => value ? command("project.story.approve", state.status.project, value) : Promise.resolve({ ok: true, data: null })), propose: (value) => run(async () => { const result = await command("project.story.propose", state.status.project, value ?? {}); if (result.ok) state.storyCandidate = result.data; return result; }), compare: (value) => run(() => value ? command("project.review.compare", state.status.project, value) : Promise.resolve({ ok: true, data: null })), delivery: (value) => run(() => value ? command("project.delivery.manifest", state.status.project, value) : Promise.resolve({ ok: true, data: null })), render: () => { const value = window.prompt("QC 要求 JSON（可含 loudness/subtitle_bounds/missing_effects/sponsor/privacy）", "{}"); if (value === null) return Promise.resolve({ ok: true, data: null }); let qc_requirements; try { qc_requirements = JSON.parse(value); } catch { throw new Error("QC 要求 JSON 格式无效"); } return run(() => command("project.render", state.status.project, { qc_requirements })); }, export: () => run(() => { const deliveryId = window.prompt("Delivery ID"); const qcReportId = window.prompt("QC Report ID"); const exportId = window.prompt("Export ID"); if (!deliveryId || !qcReportId || !exportId) return Promise.resolve({ ok: true, data: null }); return command("project.export.register", state.status.project, { delivery_id: deliveryId, qc_report_id: qcReportId, export_id: exportId }); }),
    stage2View: (view) => { state.stage2View = view; render(); }, selectDirection: (id) => { state.selectedDirectionId = id; render(); }, selectStory: (id) => { state.selectedStoryId = id; render(); },
    createContract: (values) => run(() => command("project.stage2.contract.create", state.status.project, prepareStage2ContractDraft(state.stage2Workspace, values))),
    stage2Action: (action, values = {}) => run(() => { const workspace = state.stage2Workspace; if (!workspace) throw new Error("Stage 2 工作区尚未加载"); const reason = window.prompt("说明这次决定的原因", values.reason ?? "我已核对当前版本与预期效果"); if (!reason?.trim()) return Promise.resolve({ ok: true, data: null }); return command("project.stage2.action", state.status.project, { action, workspace_digest: workspace.workspace_digest, reason, ...values }); }),
    renderStage2Execution: (executionId) => run(() => { const workspace = state.stage2Workspace; if (!workspace || workspace.review?.current_execution_id !== executionId) throw new Error("当前执行已变化，请刷新后重试"); return command("project.stage2.execution.render", state.status.project, { workspace_digest: workspace.workspace_digest, execution_id: executionId }); }),
    createFeedback: (feedbackText, trimSeconds, targetKey) => run(() => command("project.stage2.feedback.create", state.status.project, prepareStage2FeedbackRequest(state.stage2Workspace, feedbackText, trimSeconds, targetKey, crypto.randomUUID()))),
    previewFeedback: (intentId) => run(async () => { const result = await query("project.stage2.feedback.preview", state.status.project, { intent_id: intentId }); if (result.ok) state.stage2Preview = result.data; return result; }),
  };
  const render = () => { root.replaceChildren(); const shell = document.createElement("div"); shell.className = "workbench-shell"; shell.innerHTML = `<header class="topbar"><div><p class="eyebrow">AVE / LOCAL EDITOR</p><h1>AI Vlog 工作台</h1></div><span class="connection"><i></i> Project Host 在线</span></header>`; const cards = document.createElement("div"); cards.className = "status-grid"; for (const [label, value] of [["项目", state.status.project], ["时间线", state.status.timeline], ["渲染", state.status.render], ["QC", state.status.qc]]) cards.append(statusCard(label, value)); shell.append(cards); shell.append(stage2Workspace(actions, state)); const grid = document.createElement("div"); grid.className = "panel-grid legacy-workbench"; grid.append(projectPanel(actions, state), mediaPanel(actions, state), timelinePanel(actions, state), jobsPanel(state), playerPanel(actions, state), diffPanel(state), editorialPanel(actions, state)); shell.append(grid); if (state.notice) { const notice = document.createElement("p"); notice.className = "notice"; notice.textContent = state.notice; shell.append(notice); } root.append(shell); };
  subscribe(() => void refresh()); render(); void refresh(); return { refresh };
}
