import type { AssetId } from "../../media-identity/src/public.js";
export type Observation = Readonly<{ schema_version: 1; observation_id: string; asset_id: AssetId; start_pts: bigint; end_pts: bigint; statement: string }>;
export type Interpretation = Readonly<{ schema_version: 1; interpretation_id: string; evidence_ids: readonly string[]; statement: string; confidence: number; review_status: "candidate" | "approved" | "rejected" }>;
export type CreativeRequirement = Readonly<{ requirement_id: string; kind: "hard" | "preference"; statement: string }>;
export type CreativeContract = Readonly<{ schema_version: 1; contract_id: string; status: "draft" | "review" | "approved"; requirements: readonly CreativeRequirement[] }>;
export type Moment = Readonly<{ schema_version: 1; moment_id: string; evidence_ids: readonly string[]; label: string }>;
export type Event = Readonly<{ schema_version: 1; event_id: string; evidence_ids: readonly string[]; statement: string; status: "candidate" | "approved" | "rejected" }>;
export type MaterialSufficiency = Readonly<{ schema_version: 1; sufficiency_id: string; status: "sufficient" | "insufficient" | "unknown"; missing_requirements: readonly string[]; evidence_ids: readonly string[] }>;
export type CoverageRow = Readonly<{ requirement_id: string; evidence_ids: readonly string[]; status: "covered" | "missing" | "conflict" }>;
export type CoverageMatrix = Readonly<{ schema_version: 1; matrix_id: string; rows: readonly CoverageRow[] }>;
export type AnalysisSegment = Readonly<{ schema_version: 1; segment_id: string; asset_id: AssetId; start_pts: bigint; end_pts: bigint; text: string; source: "asr" | "ocr" | "scene" }>;
export type StoryBeat = Readonly<{ beat_id: string; evidence_ids: readonly string[]; purpose: string }>;
export type StoryProposal = Readonly<{ schema_version: 1; proposal_id: string; evidence_ids: readonly string[]; coverage_matrix_id: string; beats: readonly StoryBeat[]; status: "candidate" | "rejected" }>;
export type ApprovedStoryPlan = Readonly<{ schema_version: 1; plan_id: string; proposal_id: string; approved_by: string; approved_at: string; beats: readonly StoryBeat[] }>;
export type AssemblyClip = Readonly<{ clip_id: string; beat_id: string; evidence_ids: readonly string[]; asset_id: AssetId; start_pts: bigint; end_pts: bigint }>;
export type AssemblyCut = Readonly<{ schema_version: 1; assembly_id: string; approved_plan_id: string; clips: readonly AssemblyClip[]; status: "candidate" | "validated" | "rejected" }>;
export type AssemblyEditOperation = Readonly<{ operation: "add"; clip_id: string; asset_id: AssetId; start_pts: bigint; end_pts: bigint; evidence_ids: readonly string[]; beat_id: string }>;
export type ReviewIssue = Readonly<{ schema_version: 1; issue_id: string; category: "pacing" | "coverage" | "continuity" | "audio" | "visual" | "requirement"; statement: string; target_clip_ids: readonly string[]; status: "open" | "accepted" | "rejected" | "resolved" }>;
export type FeedbackDiagnosis = Readonly<{ schema_version: 1; diagnosis_id: string; feedback_text: string; issue_ids: readonly string[]; status: "candidate" | "reviewed" | "rejected" }>;
export type CompareResult = Readonly<{ schema_version: 1; compare_id: string; left_version: number; right_version: number; selection: "left" | "right" | "neither" | "both"; reason: string }>;
export type ReactionTiming = Readonly<{ schema_version: 1; reaction_id: string; compare_id: string; timeline_pts: bigint; reaction: "positive" | "negative" | "confused" | "neutral"; source: "user" | "reviewer" }>;
export type RoughCutOperation = Readonly<{ operation: "replace" | "remove" | "j_cut" | "l_cut"; clip_id: string; source_start_pts?: bigint; source_end_pts?: bigint; audio_offset_pts?: bigint }>;
export type RoughCutPatch = Readonly<{ schema_version: 1; patch_id: string; base_version: number; operations: readonly RoughCutOperation[] }>;
export type DeliveryGates = Readonly<{ qc: "passed" | "blocked"; privacy: "passed" | "blocked" | "not_required"; rights: "passed" | "blocked" | "unknown"; original_link: "verified" | "blocked" }>;
export type DeliveryManifest = Readonly<{ schema_version: 1; delivery_id: string; timeline_version: number; master_render_id: string; gates: DeliveryGates; status: "ready" | "blocked" | "exported" }>;
export type PrivacyLedgerEntry = Readonly<{ schema_version: 1; entry_id: string; asset_id: AssetId; classification: "public" | "personal" | "sensitive"; action: "none" | "redact" | "blur" | "exclude"; status: "pending" | "approved" | "applied" }>;
export type RightsLedgerEntry = Readonly<{ schema_version: 1; entry_id: string; asset_id: AssetId; license_id: string; status: "unknown" | "pending" | "approved" | "expired" }>;
export type ExportRegistration = Readonly<{ schema_version: 1; export_id: string; delivery_id: string; path: string; sha256: string; media_type: "video/mp4"; qc_report_id: string }>;
export type ExportCapability = Readonly<{ schema_version: 1; capability_id: string; container: "mp4"; video_codec: "h264"; audio_codec: "aac"; min_width: number; max_width: number; min_height: number; max_height: number; min_fps: number; max_fps: number; audio_sample_rates: readonly number[] }>;
export type ExportProfile = Readonly<{ container: "mp4"; video_codec: "h264"; audio_codec: "aac"; width: number; height: number; fps: number; audio_sample_rate: number }>;

export type VersionedObjectRef = Readonly<{ object_id: string; object_version: number; digest: string }>;
export type CreativeContractV2 = Readonly<{
  schema_version: 2;
  contract_id: string;
  project_id: string;
  object_version: number;
  status: "draft" | "review" | "approved" | "superseded";
  creator_goal: string;
  audience: readonly string[];
  platforms: readonly string[];
  target_duration: Readonly<{ schema_version: 1; value: number; timescale: number }>;
  requirements: readonly Readonly<{ requirement_id: string; kind: "hard" | "preference"; statement: string; priority: number }>[];
  voice_and_identity: Readonly<{ desired_traits: readonly string[]; forbidden_misrepresentation: readonly string[] }>;
  privacy_policy_ref: VersionedObjectRef;
  rights_policy_ref: VersionedObjectRef;
  approval_policy: Readonly<{ mode: "explicit_user" | "explicit_policy"; actor_kind: "user" | "policy" }>;
  protected_refs: readonly string[];
  allowed_transformations: readonly string[];
  forbidden_outcomes: readonly string[];
  created_at: string;
  supersedes_ref?: VersionedObjectRef;
  approval?: Readonly<{ actor_id: string; actor_kind: "user" | "policy"; approved_at: string; review_digest: string }>;
  provenance: Readonly<{ producer: "user" | "interview" | "adapter" | "policy"; source_id: string; source_version?: string; policy_version: string; input_refs: readonly string[]; unresolved_assumptions: readonly string[] }>;
}>;
export type MaterialEvidenceRef = Readonly<{ evidence_id: string; evidence_type: "asr" | "ocr" | "scene" | "observation" | "interpretation" | "moment" | "event"; evidence_version: number; asset_id: AssetId; range: Readonly<{ start: Readonly<{ schema_version: 1; value: number; timescale: number }>; end: Readonly<{ schema_version: 1; value: number; timescale: number }> }>; review_status: "approved"; content_digest: string }>;
export type MaterialAvailability = Readonly<{ asset_id: AssetId; original_identity: AssetId; proxy_identity?: AssetId; permission_state: "authorized" | "denied" | "unknown" | "unavailable"; verified_at: string }>;
export type MaterialEvidencePackV1 = Readonly<{
  schema_version: 1;
  pack_id: string;
  project_id: string;
  object_version: number;
  status: "sufficient" | "insufficient" | "stale" | "superseded";
  contract_ref: VersionedObjectRef;
  timeline_version?: number;
  evidence_refs: readonly MaterialEvidenceRef[];
  moment_refs: readonly VersionedObjectRef[];
  event_refs: readonly VersionedObjectRef[];
  coverage_matrix_ref: VersionedObjectRef;
  sufficiency: Readonly<{ covered_requirement_ids: readonly string[]; missing_requirement_ids: readonly string[]; conflicting_requirement_ids: readonly string[] }>;
  availability: readonly MaterialAvailability[];
  policy_snapshot: Readonly<{ policy_version: string; privacy_policy_ref: VersionedObjectRef; rights_policy_ref: VersionedObjectRef }>;
  input_fingerprint: string;
  created_at: string;
  expires_at?: string;
  stale_reason?: string;
  supersedes_ref?: VersionedObjectRef;
  provenance: Readonly<{ producer: "project-host"; source_version: string; policy_version: string; input_refs: readonly string[]; unresolved_assumptions: readonly string[] }>;
}>;

export { CREATIVE_SKILL_EVALUATOR_VERSION, CREATIVE_SKILL_POLICY_VERSION, assertCreativeSkillKnowledgeOnly, builtInCreativeSkillDefinitions, canonicalCreativeSkill, creativeSkillDefinitionDigest, evaluateCreativeSkill, validateCreativeSkillDefinition, validateSkillEvaluationInput } from "./knowledge/skill/public.js";
export type { CreativeSkillDefinitionV1, SkillEvaluationInput, SkillEvaluationV1, SkillScalar } from "./knowledge/skill/public.js";
export { DURATION_ALLOCATOR_VERSION, DURATION_MATERIAL_POLICY_VERSION, DURATION_POLICY_VERSION, builtInDurationBlueprints, canonicalDurationBlueprint, durationBlueprintDigest, evaluateDurationFeasibility, validateDurationBlueprint, validateDurationFeasibilityInput } from "./knowledge/duration/public.js";
export type { DurationBlueprintV1, DurationFeasibilityInput, DurationFeasibilityV1 } from "./knowledge/duration/public.js";
export { STORY_APPROVAL_VERSION, STORY_EVALUATOR_VERSION, STORY_POLICY_VERSION, approveStoryProposalV2, canonicalEditorialObject, createDirectionCard, editorialObjectDigest, evaluateStoryProposal, rankStoryProposals, selectDirectionCard } from "./knowledge/story/public.js";
export type { ApprovedStoryPlanV2, DecisionRecordV1, DirectionCardInput, DirectionCardV1, DirectionSelectionInput, StoryApprovalInput, StoryBeatCandidate, StoryProposalInput, StoryProposalV2 } from "./knowledge/story/public.js";
export { isStrictComparableDateTime } from "./knowledge/date-time.js";
