import type { AssetId } from "../../media-identity/src/public.js";
export type Observation = Readonly<{ schema_version: 1; observation_id: string; asset_id: AssetId; start_pts: bigint; end_pts: bigint; statement: string }>;
export type Interpretation = Readonly<{ schema_version: 1; interpretation_id: string; evidence_ids: readonly string[]; statement: string; confidence: number; review_status: "candidate" | "approved" | "rejected" }>;
export type CreativeRequirement = Readonly<{ requirement_id: string; kind: "hard" | "preference"; statement: string }>;
export type CreativeContract = Readonly<{ schema_version: 1; contract_id: string; status: "draft" | "review" | "approved"; requirements: readonly CreativeRequirement[] }>;
export type Moment = Readonly<{ schema_version: 1; moment_id: string; evidence_ids: readonly string[]; label: string }>;
export type Event = Readonly<{ schema_version: 1; event_id: string; evidence_ids: readonly string[]; statement: string; status: "candidate" | "approved" | "rejected" }>;
export type MaterialSufficiency = Readonly<{ schema_version: 1; sufficiency_id: string; status: "sufficient" | "insufficient" | "unknown"; missing_requirements: readonly string[]; evidence_ids: readonly string[] }>;
export type CoverageRow = Readonly<{ requirement_id: string; evidence_ids: readonly string[]; status: "covered" | "missing" | "conflict" }>;
export type CoverageMatrix = Readonly<{ schema_version: 1; matrix_id: string; rows: readonly CoverageRow[] }>;
export type AnalysisSegment = Readonly<{ schema_version: 1; segment_id: string; asset_id: AssetId; start_pts: bigint; end_pts: bigint; text: string; source: "asr" | "ocr" | "scene" }>;
export type StoryBeat = Readonly<{ beat_id: string; evidence_ids: readonly string[]; purpose: string }>;
export type StoryProposal = Readonly<{ schema_version: 1; proposal_id: string; evidence_ids: readonly string[]; coverage_matrix_id: string; beats: readonly StoryBeat[]; status: "candidate" | "rejected" }>;
export type ApprovedStoryPlan = Readonly<{ schema_version: 1; plan_id: string; proposal_id: string; approved_by: string; approved_at: string; beats: readonly StoryBeat[] }>;
export type AssemblyClip = Readonly<{ clip_id: string; beat_id: string; evidence_ids: readonly string[]; asset_id: AssetId; start_pts: bigint; end_pts: bigint }>;
export type AssemblyCut = Readonly<{ schema_version: 1; assembly_id: string; approved_plan_id: string; clips: readonly AssemblyClip[]; status: "candidate" | "validated" | "rejected" }>;
export type AssemblyEditOperation = Readonly<{ operation: "add"; clip_id: string; asset_id: AssetId; start_pts: bigint; end_pts: bigint; evidence_ids: readonly string[]; beat_id: string }>;
export type ReviewIssue = Readonly<{ schema_version: 1; issue_id: string; category: "pacing" | "coverage" | "continuity" | "audio" | "visual" | "requirement"; statement: string; target_clip_ids: readonly string[]; status: "open" | "accepted" | "rejected" | "resolved" }>;
export type FeedbackDiagnosis = Readonly<{ schema_version: 1; diagnosis_id: string; feedback_text: string; issue_ids: readonly string[]; status: "candidate" | "reviewed" | "rejected" }>;
export type CompareResult = Readonly<{ schema_version: 1; compare_id: string; left_version: number; right_version: number; selection: "left" | "right" | "neither" | "both"; reason: string }>;
export type ReactionTiming = Readonly<{ schema_version: 1; reaction_id: string; compare_id: string; timeline_pts: bigint; reaction: "positive" | "negative" | "confused" | "neutral"; source: "user" | "reviewer" }>;
export type RoughCutOperation = Readonly<{ operation: "replace" | "remove" | "j_cut" | "l_cut"; clip_id: string; source_start_pts?: bigint; source_end_pts?: bigint; audio_offset_pts?: bigint }>;
export type RoughCutPatch = Readonly<{ schema_version: 1; patch_id: string; base_version: number; operations: readonly RoughCutOperation[] }>;
export type DeliveryGates = Readonly<{ qc: "passed" | "blocked"; privacy: "passed" | "blocked" | "not_required"; rights: "passed" | "blocked" | "unknown"; original_link: "verified" | "blocked" }>;
export type DeliveryManifest = Readonly<{ schema_version: 1; delivery_id: string; timeline_version: number; master_render_id: string; gates: DeliveryGates; status: "ready" | "blocked" | "exported" }>;
export type PrivacyLedgerEntry = Readonly<{ schema_version: 1; entry_id: string; asset_id: AssetId; classification: "public" | "personal" | "sensitive"; action: "none" | "redact" | "blur" | "exclude"; status: "pending" | "approved" | "applied" }>;
export type RightsLedgerEntry = Readonly<{ schema_version: 1; entry_id: string; asset_id: AssetId; license_id: string; status: "unknown" | "pending" | "approved" | "expired" }>;
export type ExportRegistration = Readonly<{ schema_version: 1; export_id: string; delivery_id: string; path: string; sha256: string; media_type: "video/mp4"; qc_report_id: string }>;
export type ExportCapability = Readonly<{ schema_version: 1; capability_id: string; container: "mp4"; video_codec: "h264"; audio_codec: "aac"; min_width: number; max_width: number; min_height: number; max_height: number; min_fps: number; max_fps: number; audio_sample_rates: readonly number[] }>;
export type ExportProfile = Readonly<{ container: "mp4"; video_codec: "h264"; audio_codec: "aac"; width: number; height: number; fps: number; audio_sample_rate: number }>;
export const exportCapabilities: Readonly<Record<string, ExportCapability>> = { social_1080p: { schema_version: 1, capability_id: "social-1080p", container: "mp4", video_codec: "h264", audio_codec: "aac", min_width: 1280, max_width: 1920, min_height: 720, max_height: 1080, min_fps: 23.976, max_fps: 60, audio_sample_rates: [44100, 48000] }, archive_4k: { schema_version: 1, capability_id: "archive-4k", container: "mp4", video_codec: "h264", audio_codec: "aac", min_width: 3840, max_width: 3840, min_height: 2160, max_height: 2160, min_fps: 23.976, max_fps: 60, audio_sample_rates: [48000] }, vertical_short: { schema_version: 1, capability_id: "vertical-short", container: "mp4", video_codec: "h264", audio_codec: "aac", min_width: 1080, max_width: 1080, min_height: 1920, max_height: 1920, min_fps: 24, max_fps: 60, audio_sample_rates: [44100, 48000] } };
export function validateObservation(observation: Observation): void { if (observation.end_pts <= observation.start_pts) throw new Error("observation range must be positive"); if (!observation.statement.trim()) throw new Error("observation statement is required"); }
export function validateInterpretation(interpretation: Interpretation, observations: ReadonlySet<string>): void { if (interpretation.evidence_ids.length === 0 || interpretation.evidence_ids.some((id) => !observations.has(id))) throw new Error("interpretation requires known evidence"); if (interpretation.confidence < 0 || interpretation.confidence > 1) throw new Error("confidence must be between 0 and 1"); }
export function approveInterpretation(interpretation: Interpretation, observations: ReadonlySet<string>): Interpretation { validateInterpretation(interpretation, observations); return { ...interpretation, review_status: "approved" }; }
export function validateEvidenceReferences(evidenceIds: readonly string[], knownEvidence: ReadonlySet<string>): void { if (evidenceIds.length === 0 || evidenceIds.some((id) => !knownEvidence.has(id))) throw new Error("all evidence references must be known"); }
export function approveEvent(event: Event, knownEvidence: ReadonlySet<string>, sufficiency: MaterialSufficiency): Event { validateEvidenceReferences(event.evidence_ids, knownEvidence); if (sufficiency.status !== "sufficient") throw new Error("insufficient material blocks event approval"); return { ...event, status: "approved" }; }
export function canGenerateStory(sufficiency: MaterialSufficiency): boolean { return sufficiency.status === "sufficient" && sufficiency.missing_requirements.length === 0; }
export function validateCoverage(matrix: CoverageMatrix, contract: CreativeContract, approvedEvidence: ReadonlySet<string>): void { const hard = new Set(contract.requirements.filter((requirement) => requirement.kind === "hard").map((requirement) => requirement.requirement_id)); for (const requirementId of hard) { const row = matrix.rows.find((candidate) => candidate.requirement_id === requirementId); if (!row || row.status !== "covered" || row.evidence_ids.some((evidenceId) => !approvedEvidence.has(evidenceId))) throw new Error(`hard requirement is not covered: ${requirementId}`); } }
export function observationFromAnalysis(segment: AnalysisSegment): Observation { if (segment.end_pts <= segment.start_pts) throw new Error("analysis segment range must be positive"); if (!segment.text.trim()) throw new Error("analysis segment must contain explicit output"); return { schema_version: 1, observation_id: `${segment.source}:${segment.segment_id}`, asset_id: segment.asset_id, start_pts: segment.start_pts, end_pts: segment.end_pts, statement: segment.text }; }
export function approveStoryProposal(proposal: StoryProposal, approvedEvidence: ReadonlySet<string>, matrix: CoverageMatrix, contract: CreativeContract, approvedBy: string, approvedAt: string): ApprovedStoryPlan { if (proposal.status !== "candidate") throw new Error("only candidate proposals can be approved"); if (proposal.beats.length === 0) throw new Error("story proposal has no beats"); validateCoverage(matrix, contract, approvedEvidence); validateEvidenceReferences(proposal.evidence_ids, approvedEvidence); for (const beat of proposal.beats) validateEvidenceReferences(beat.evidence_ids, approvedEvidence); if (!approvedBy || !approvedAt) throw new Error("approval identity and time are required"); return { schema_version: 1, plan_id: `${proposal.proposal_id}:approved`, proposal_id: proposal.proposal_id, approved_by: approvedBy, approved_at: approvedAt, beats: proposal.beats }; }
export function validateAssemblyCut(cut: AssemblyCut, plan: ApprovedStoryPlan, approvedEvidence: ReadonlySet<string>): AssemblyCut { if (cut.approved_plan_id !== plan.plan_id) throw new Error("assembly plan mismatch"); const beatIds = new Set(plan.beats.map((beat) => beat.beat_id)); if (cut.clips.some((clip) => !beatIds.has(clip.beat_id))) throw new Error("assembly clip references unknown beat"); for (const clip of cut.clips) { validateEvidenceReferences(clip.evidence_ids, approvedEvidence); if (clip.end_pts <= clip.start_pts) throw new Error("assembly clip range must be positive"); } return { ...cut, status: "validated" }; }
export function compileAssemblyToEditIR(cut: AssemblyCut): readonly AssemblyEditOperation[] { if (cut.status !== "validated") throw new Error("only validated assembly cuts can compile"); return cut.clips.map((clip) => { if (clip.end_pts <= clip.start_pts) throw new Error("assembly clip range must be positive"); return { operation: "add", clip_id: clip.clip_id, asset_id: clip.asset_id, start_pts: clip.start_pts, end_pts: clip.end_pts, evidence_ids: clip.evidence_ids, beat_id: clip.beat_id }; }); }
export function reviewFeedback(diagnosis: FeedbackDiagnosis, issues: readonly ReviewIssue[]): FeedbackDiagnosis { if (!diagnosis.feedback_text.trim()) throw new Error("feedback is required"); const ids = new Set(issues.map((issue) => issue.issue_id)); if (diagnosis.issue_ids.some((id) => !ids.has(id))) throw new Error("feedback references unknown issue"); if (diagnosis.status !== "candidate") throw new Error("only candidate diagnosis can be reviewed"); return { ...diagnosis, status: "reviewed" }; }
export function validateCompare(result: CompareResult): void { if (result.left_version === result.right_version) throw new Error("compare requires two different versions"); if (!result.reason.trim()) throw new Error("compare reason is required"); }
export function validateReactionTiming(reaction: ReactionTiming, compare: CompareResult): void { validateCompare(compare); if (reaction.compare_id !== compare.compare_id) throw new Error("reaction compare mismatch"); if (reaction.timeline_pts < 0n) throw new Error("reaction time must not be negative"); }
export function validateRoughCutPatch(patch: RoughCutPatch, currentVersion: number, knownClipIds: ReadonlySet<string>): void { if (patch.base_version !== currentVersion) throw new Error("rough cut base version conflict"); if (patch.operations.length === 0) throw new Error("rough cut patch is empty"); for (const operation of patch.operations) { if (!knownClipIds.has(operation.clip_id)) throw new Error("rough cut target clip is unknown"); if ((operation.operation === "replace" || operation.operation === "j_cut" || operation.operation === "l_cut") && (operation.source_start_pts === undefined || operation.source_end_pts === undefined || operation.source_end_pts <= operation.source_start_pts)) throw new Error("rough cut source range is invalid"); if ((operation.operation === "j_cut" || operation.operation === "l_cut") && operation.audio_offset_pts === undefined) throw new Error("J/L cut requires audio offset"); } }
export function validateDelivery(manifest: DeliveryManifest): DeliveryManifest { const gates = manifest.gates; if (gates.qc !== "passed" || gates.privacy === "blocked" || gates.rights !== "passed" || gates.original_link !== "verified") throw new Error("delivery gates are not satisfied"); return { ...manifest, status: "ready" }; }
export function approvePrivacy(entry: PrivacyLedgerEntry): PrivacyLedgerEntry { if (entry.status !== "pending") throw new Error("privacy entry is not pending"); if (entry.classification !== "public" && entry.action === "none") throw new Error("non-public asset requires privacy action"); return { ...entry, status: "approved" }; }
export function approveRights(entry: RightsLedgerEntry): RightsLedgerEntry { if (entry.status !== "pending") throw new Error("rights entry is not pending"); if (!entry.license_id.trim()) throw new Error("license is required"); return { ...entry, status: "approved" }; }
export function validateExportRegistration(registration: ExportRegistration, delivery: DeliveryManifest, qcReportId: string): void { if (registration.delivery_id !== delivery.delivery_id) throw new Error("export delivery mismatch"); if (delivery.status !== "ready") throw new Error("delivery is not ready"); if (registration.qc_report_id !== qcReportId) throw new Error("export QC report mismatch"); if (!/^[0-9a-f]{64}$/.test(registration.sha256)) throw new Error("export hash is invalid"); }
export function validateExportProfile(profile: ExportProfile, capability: ExportCapability): void { if (profile.container !== capability.container || profile.video_codec !== capability.video_codec || profile.audio_codec !== capability.audio_codec) throw new Error("export format is unsupported"); if (profile.width < capability.min_width || profile.width > capability.max_width || profile.height < capability.min_height || profile.height > capability.max_height) throw new Error("export dimensions are unsupported"); if (profile.fps < capability.min_fps || profile.fps > capability.max_fps) throw new Error("export frame rate is unsupported"); if (!capability.audio_sample_rates.includes(profile.audio_sample_rate)) throw new Error("export audio sample rate is unsupported"); }
