import { mkdir, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { resolve } from "node:path";
const run = promisify(execFile); const root = resolve(import.meta.dirname, "../.."); const master = resolve(root, "tests/fixtures/generated/renders/master.mp4"); const reportPath = resolve(root, "tests/fixtures/generated/renders/master-qc.json"); const issues = [];
try { const { stdout } = await run("ffprobe", ["-v", "error", "-show_streams", "-show_format", "-of", "json", master]); const data = JSON.parse(stdout); if (!data.streams.some((stream) => stream.codec_type === "video")) issues.push({ code: "DECODE_FAILED", severity: "error", message: "no video stream" }); if (!data.streams.some((stream) => stream.codec_type === "audio")) issues.push({ code: "DECODE_FAILED", severity: "error", message: "no audio stream" }); } catch (error) { issues.push({ code: "DECODE_FAILED", severity: "error", message: String(error) }); }
for (const [filter, code, message, stream] of [["blackdetect=d=0.5", "BLACK_FRAME", "black frame detected", "video"], ["freezedetect=n=0.003:d=0.5", "FREEZE_FRAME", "freeze frame detected", "video"], ["silencedetect=n=-50dB:d=0.5", "SILENCE", "silence detected", "audio"], ["volumedetect", "CLIPPING", "audio clipping detected", "audio"]]) { try { const args = ["-hide_banner", "-i", master, stream === "video" ? "-vf" : "-af", filter, "-f", "null", "-"]; const result = await run("ffmpeg", args, { maxBuffer: 1024 * 1024 * 8 }); const combined = `${result.stdout}\n${result.stderr}`; if ((filter.startsWith("blackdetect") && combined.includes("black_start")) || (filter.startsWith("freezedetect") && combined.includes("freeze_start")) || (filter.startsWith("silencedetect") && combined.includes("silence_start")) || (filter === "volumedetect" && combined.includes("max_volume: -0.0 dB"))) issues.push({ code, severity: "warning", message }); } catch { issues.push({ code: "DECODE_FAILED", severity: "error", message: `filter failed: ${filter}` }); } }
try { const result = await run("ffmpeg", ["-hide_banner", "-i", master, "-af", "ebur128=framelog=verbose", "-f", "null", "-"], { maxBuffer: 1024 * 1024 * 8 }); const match = `${result.stdout}\n${result.stderr}`.match(/I:\s*(-?\d+(?:\.\d+)?)\s+LUFS/); if (!match || Number(match[1]) < -70 || Number(match[1]) > -5) issues.push({ code: "LOUDNESS", severity: "error", message: `integrated loudness outside -70..-5 LUFS: ${match?.[1] ?? "missing"}` }); } catch { issues.push({ code: "LOUDNESS", severity: "error", message: "loudness measurement failed" }); }
if (master.toLowerCase().includes("proxy")) issues.push({ code: "PROXY_USAGE", severity: "error", message: "master path contains proxy" });
const report = { schema_version: 1, render_id: "master", status: issues.some((issue) => issue.severity === "error") ? "blocked" : "passed", issues }; await mkdir(resolve(root, "tests/fixtures/generated/renders"), { recursive: true }); await writeFile(reportPath, JSON.stringify(report, null, 2) + "\n"); if (report.status === "blocked") throw new Error(`master QC blocked: ${JSON.stringify(issues)}`); console.log("master QC passed (decode, streams, proxy usage)");
