import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { rm } from "node:fs/promises";
import { resolve } from "node:path";
import { createProject, putObject } from "./project-storage.mjs";

const root = resolve(process.env.TEMP ?? ".", "ai-vlog-storage-smoke");
await rm(root, { recursive: true, force: true });
const session = await createProject(root);
if (session.manifest.project_format_version !== 2) throw new Error("project format v2 was not initialized");
if (session.db.prepare("SELECT format_version FROM project_format").get().format_version !== 2) throw new Error("database format v2 was not recorded");
if (session.db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'schema_migrations'").get()) throw new Error("migration ledger must not exist");
if (session.db.prepare("PRAGMA journal_mode").get().journal_mode !== "wal") throw new Error("WAL is not enabled");
const bytes = Buffer.from("object-store-smoke");
const stored = await putObject(root, bytes);
if (stored.hash !== createHash("sha256").update(bytes).digest("hex") || !existsSync(stored.path)) throw new Error("atomic object write failed");
if (session.db.prepare("PRAGMA integrity_check").get().integrity_check !== "ok") throw new Error("SQLite integrity check failed");
await session.close();
await rm(root, { recursive: true, force: true });
console.log("storage check passed (format v2, WAL, object atomic write, integrity)");
