export const featureId = "story-planning" as const;
import type { ApprovedStoryPlan, CreativeContract, CoverageMatrix, StoryProposal } from "../../../core/editorial-core/src/public.js";
export type StoryPlanningCommand = Readonly<{ type: string; payload: unknown }>;
export type StoryPlanningQuery = Readonly<{ type: string; parameters?: Readonly<Record<string, unknown>> }>;
export type StoryPlanningFeatureDescriptor = Readonly<{ feature_id: typeof featureId; label: "story planning"; owner: "project-host"; layers: readonly ["commands", "queries", "use-cases", "policies", "validators", "prompts", "ports"] }>;
export const descriptor: StoryPlanningFeatureDescriptor = Object.freeze({ feature_id: featureId, label: "story planning", owner: "project-host", layers: ["commands", "queries", "use-cases", "policies", "validators", "prompts", "ports"] as const });
export function validateStoryProposal(proposal: StoryProposal): void {
  if (proposal.schema_version !== 1 || !proposal.proposal_id || !proposal.coverage_matrix_id || proposal.status !== "candidate") throw new Error("invalid story proposal metadata");
  if (!Array.isArray(proposal.evidence_ids) || proposal.evidence_ids.length === 0 || proposal.evidence_ids.some((id) => typeof id !== "string" || !id)) throw new Error("story proposal evidence is invalid");
  if (!Array.isArray(proposal.beats) || proposal.beats.length === 0) throw new Error("story proposal beats are required");
  for (const beat of proposal.beats) if (!beat.beat_id || !beat.purpose || !Array.isArray(beat.evidence_ids) || beat.evidence_ids.length === 0 || beat.evidence_ids.some((id: string) => typeof id !== "string" || !id)) throw new Error("story proposal beat is invalid");
}
function validateCoverage(matrix: CoverageMatrix, contract: CreativeContract, approvedEvidence: ReadonlySet<string>): void { const hard = new Set(contract.requirements.filter((requirement) => requirement.kind === "hard").map((requirement) => requirement.requirement_id)); for (const requirementId of hard) { const row = matrix.rows.find((candidate) => candidate.requirement_id === requirementId); if (!row || row.status !== "covered" || row.evidence_ids.some((evidenceId) => !approvedEvidence.has(evidenceId))) throw new Error(`hard requirement is not covered: ${requirementId}`); } }
export function approveStoryProposal(proposal: StoryProposal, approvedEvidence: ReadonlySet<string>, matrix: CoverageMatrix, contract: CreativeContract, approvedBy: string, approvedAt: string): ApprovedStoryPlan { validateStoryProposal(proposal); if (proposal.status !== "candidate") throw new Error("only candidate proposals can be approved"); validateCoverage(matrix, contract, approvedEvidence); const evidenceIds = new Set(approvedEvidence); if (proposal.evidence_ids.length === 0 || proposal.evidence_ids.some((id) => !evidenceIds.has(id))) throw new Error("all evidence references must be known"); for (const beat of proposal.beats) if (beat.evidence_ids.length === 0 || beat.evidence_ids.some((id) => !evidenceIds.has(id))) throw new Error("all evidence references must be known"); if (!approvedBy || !approvedAt) throw new Error("approval identity and time are required"); return { schema_version: 1, plan_id: `${proposal.proposal_id}:approved`, proposal_id: proposal.proposal_id, approved_by: approvedBy, approved_at: approvedAt, beats: proposal.beats }; }
